export const character = {
    vl_templete: {
        enable: false,
        name: '🐺名字',
        title: '头衔',
        gender: 'male',
        bloc: '势力',
        hp: 3,
        intro: `简要介绍`,
        prefix: "🐺",
        skills: [],
        addition: [],
        pack: '武将包',
        vp: 0,
        sort: '分类',
        rank: '评级'
    },
    vl_fangsuan: {
        enable: true,
        name: 'SP钫酸',
        title: '无畏暴君',
        gender: 'male',
        bloc: 'vl_hulizu',
        hp: 3,
        vp: 3,
        intro: `
钫酸出生于瓦尔亚纳大陆北部的一个小公国。他的父亲是那片领地的公爵，母亲来自一个没落的精灵家族。他幼年时便显露出异于常人的天赋——左眼能看穿谎言的纹理，右眼能捕捉魔法的流动。十岁那年，他当着宫廷法师的面，用目光让一头狂暴的狮鹫安静下来，随后命令它撞死在城墙上。这件事被记录为他的第一次“催眠”。公爵没有感到欣慰，而是恐惧。他试图将儿子送往边境的修道院，但车队在途中遭遇山匪，随行的护卫全部死亡，钫酸独自返回城堡，身后跟着那伙山匪的头颅。公爵当晚暴毙，死因不明。十三岁的钫酸继承了爵位，随后用三年时间吞并了周边六个领地。
<br>他的扩张从未停止。他没有盟友，只有暂时未被征服的敌人。他使用军队、魔法、暗杀，也使用他自己的眼睛。只要与他对视，对方就无法拒绝他的命令。这种能力让他绕过所有谈判桌，直接抵达结果。二十岁时，他已经控制了大陆北部三分之一的土地。他继续向南推进，遭遇了精灵联军、矮人王国和人类帝国的联合抵抗。这场战争持续了七年。钫酸在战争末期独自进入精灵的圣殿，与当时掌管大陆神力的十二位神祇对峙。他用了三天时间，逐一撕碎了那些神的化身。神祇陨落时，整个大陆的地脉都发生了震颤。第四天，他走出圣殿，宣布自己为唯一的王。
<br>统一后的第八年，钫酸颁布了“犬令”。所有臣民，不论贵族或平民，都被要求佩戴项圈，行为规范由皇家法典统一规定。他废除了原有的法律体系，将所有权力收归王座。反抗者被投入地牢，或直接由他的骑士处决。他的四位骑士——望朔、小c、阿然、阿早——各自掌管审判、传讯、死亡与治愈，形成一套完整的统治架构。第五位骑士莱恩曾是他最信任的将领，但在一场由钫酸亲自设计的构陷中，莱恩被迫杀死自己的挚友，精神崩溃，被囚禁于王宫地底深处。钫酸保留了莱恩的骑士头衔，但不再允许他踏出牢笼。
<br>钫酸的性格中有一种冷静的残酷。他从不因愤怒而杀人，也不因快感而折磨。他的行动基于效率和必要性。当他认为某件事没有价值时，他会直接终结它。他很少提高音量，眼神的变化足以传递指令。他的臣民学会在他注视时低头，因为直视他的双眼意味着失去自我。他很少使用催眠能力，因为他觉得让一个人清醒地服从更有趣。
<br>统治稳定后，钫酸开始感到一种持续的乏味。战争、征服、立法，这些事都结束了。他拥有一切，但一切都在预期之内。这种状态持续了数月，直到一位自称泡芙的术士从王宫的穹顶降落。泡芙带来了一套名为“挑担的游戏”的规则，用卡牌的形式制造困境与抉择。钫酸接受了这个游戏，因为游戏本身不可预测，而不可预测是他唯一尚未体验的事物。他将游戏的执行权交给旁人，自己作为观察者坐在王座上。游戏开始后，他的时间才重新流动起来。他不会亲自参与卡牌的判定，但他会介入游戏变得乏味的时刻——以他自己的方式。
<br>他被称为“阴鸷神王”。这个称号源于他对神祇的屠杀，也源于他那种深藏不露的、近乎残酷的冷静。他的额头那枚红色印记，是他在撕碎最后一位神祇时，对方临死前烙下的诅咒烙印。神祇说，这印记会让他永远记着“被注视”的滋味。钫酸没有去除它，因为他觉得这印记让他看起来更威严。他是瓦尔亚纳唯一的王，也是这片大陆最后的神。`,
        prefix: "SP",
        skills: ['vl_fangsuan_ximing', 'vl_fangsun_mishe', 'vl_fangsuan_kuangluan'],
        addition: ['zhu'],
        pack: 'Valyana',
        sort: 'vl_tiaodan',
        rank: 'legend'
    },
    vl_wangshuo: {
        enable: true,
        name: 'SP望朔',
        title: '守护之骑',
        gender: 'male',
        bloc: 'vl_shizu',
        hp: '3/4',
        intro: `
望朔是钫酸座下的第一位骑士，掌管审判。他是狮子兽人，头顶一对白色龙角，身上常年带着竹子的清淡气息。他的铠甲为白色，披挂为绿色，手持一柄被称为“圣剑”的长剑。这柄剑并不以锋利著称，而是能感应谎言与罪责，在审判时显现光芒。望朔的形象通常被描述为正义与光明的化身，他在公开场合的行为也符合这一描述——他主持法庭，裁决争端，从不徇私。
<br>他与钫酸签订了永世不得背叛的契约。这份契约并非出于恐惧或利益，而是基于他对秩序的认同。望朔认为，钫酸虽然手段残酷，但建立了大陆千年以来唯一统一的法度。他忠于钫酸，忠于王座，也忠于自己内心对“审判”的定义。他会在公开场合严格执行钫酸的命令，但在私下场合，他有时会延长审问的时间，或允许犯人申诉。这种行为并未违反契约，钫酸也从未过问。
<br>望朔的性格中有一种近乎固执的正直。他相信规则本身的意义，而非规则制定者的意志。如果钫酸的命令明显违背他认定的法理，他会先执行，然后请求复议。钫酸偶尔会驳回他的请求，但多数时候会调整指令。两人之间形成了一种微妙的制衡——望朔是唯一一个能在王座前提出异议而不被惩罚的骑士。其他骑士对此心知肚明，但从未有人点破。
<br>他的龙角是幼年时被一头白龙抚养留下的痕迹。那头龙在他成年时死去，将角留给了他。望朔从不谈论这件事，也不允许其他人提及。他将那段过往锁在记忆深处，像对待一道陈年旧伤一样，不触碰，不展示。`,
        prefix: "SP",
        skills: ['vl_wangshuo_shouwang', 'vl_wangshuo_maofang'],
        addition: [],
        pack: 'Valyana',
        sort: 'vl_tiaodan',
        rank: 'epic'
    },
    vl_buline: {
        enable: true,
        name: "布莱恩",
        title: "邪恶法师",
        gender: "male",
        bloc: "vl_maozu",
        hp: 4,
        intro: "布莱恩是来自地狱的无上法术的咏唱者（自称），他做过的坏事数不胜数，包括但不限于：赶走偷吃鸡的黄鼠狼，杀死袭击村民的强盗，强迫受保护费的官兵学狗叫之类，因此其深受百姓憎恶（自称）。他致力于成为整个兽人王国最邪恶的黑魔法师，并为此努力着。《瓦尔亚那百科》中曾预言布莱恩有着黑暗生物的血统与两幅面孔，但似乎其本身并不知情。",
        prefix: "",
        skills: ["vl_buline_qm", "vl_buline_yt"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "wanling",
        rank: "junk",
    },
    vl_sisk: {
        enable: true,
        name: "西斯科",
        title: "嗜血狂徒",
        gender: "male",
        bloc: "vl_huzu",
        hp: "4/5",
        intro: "西斯科，罕见的狮兽人与吸血鬼的后代。拥有极其强力的身体素质与高超的种族天赋。后来被苍月狼兽所救，加入了「流亡者」雇佣兵团。其对血液极为敏感，些许的血腥味也会导致其进入狂暴。",
        prefix: "",
        skills: ["vl_sisk_yx", "vl_sisk_wg", "vl_sisk_jx"],
        addition: [],
        pack: "FurryExt",
        vp: "2/5",
        sort: "yongbing",
        rank: "epic",
    },
    vl_aerte: {
        enable: true,
        name: "阿尔特",
        title: "缴械武解",
        gender: "male",
        bloc: "vl_langzu",
        hp: 4,
        intro: "阿尔特，出身于克拉北境的狼族骑士团。他身披白甲，常以巨剑立于阵前，却并不以杀戮为荣。北境旧俗中，决斗的胜负往往在第一击前便已决定——谁能先夺下对方的武器，谁便取得审判的权力。阿尔特正是在这种严苛训练中成长起来的骑士。<br>他曾在边境战争中独自拦下一支掠夺队，没有斩下任何一人的头颅，只是逐一卸去他们手中的刀剑，再将缴获的武器分给身后的民兵。自那以后，人们开始称他为“缴械武解”。阿尔特相信武器本身没有善恶，真正需要被制止的是握住武器的人。因此，他常常夺下敌人的杀意，再把新的力量交到更值得信任的人手中。",
        prefix: "",
        skills: ["vl_aerte_jw"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "vl_furry_migration",
        rank: "epic",
    },
    vl_hars: {
        enable: true,
        name: "哈尔斯",
        title: "全知之神",
        gender: "male",
        bloc: "shen",
        hp: 4,
        intro: "哈尔斯，兽人的智慧之神。其拥有惑人心魄的能力。根据矮人族与部分兽人族内部记录。哈尔斯能够直接降临到任何一人身上，据此观察世界。而被降临的人则被称为「神降者」。由于任何人都有可能成为「神降者」。因此，哈尔斯的眼线遍布整个大陆，而其本人也被称为「全知之神」。",
        prefix: "",
        skills: ["vl_hars_sj", "vl_hars_hr"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "shoushen",
        rank: "rare",
    },
    vl_yada: {
        enable: true,
        name: "亚达",
        title: "百变千面",
        gender: "male",
        bloc: "vl_huzu",
        hp: 4,
        intro: "亚达，暗影刺杀队的化妆师，在刺杀行动中，为了避免被其他人发现，如何伪装自己就是小队最大的难题。而亚达他凭着一手出人意料的易容技巧得到了队长斯克瑞的青睐，并在斯克瑞刺杀国王的那次行动中提供了伪装。",
        prefix: "",
        skills: ["vl_yada_yl", "vl_yada_yy"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "franying",
        rank: "rare",
    },
    vl_hundun: {
        enable: true,
        name: "混沌",
        title: "死亡使者",
        gender: "male",
        bloc: "shen",
        hp: 4,
        intro: "混沌，虽然他的知名度不如尧和洛一般，但是他确实是瓦尔亚那大陆上极为重要的神明之一。在尧和洛将灵魂拘回冥界后，混沌则会根据他们生前的事迹裁决是否对他们执行惩罚或奖励。混沌手中的双镰名为死魂幽镰，可以无视物理法则直接对灵体产生伤害。",
        prefix: "",
        skills: ["vl_hundun_sy", "vl_hundun_sl", "vl_hundun_sp"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "shoushen",
        rank: "legend",
    },
    vl_xiaomo: {
        enable: true,
        name: "泡芙",
        title: "破击无声",
        gender: "male",
        bloc: "vl_maozu",
        hp: 3,
        intro: "泡芙，是一名行踪不定的猫族旅者，也是将“挑担的游戏”带到钫酸王座前的人。与他轻巧的外表不同，泡芙对危险有着近乎本能的判断。他很少正面承受攻击，总能在刀锋落下前错开半步，让伤害像掠过水面的风一样消散。<br>据说泡芙曾在某个异界战场中学习过把护甲化作冲击力的技巧。他平日看似懒散，真正出手时却极快，能够将积蓄的防护一次性压进短促的突袭之中，因此得名“闪击”。他不喜欢解释自己的来历，只说自己是在寻找一场足够有趣、足够危险，也足够不讲道理的游戏。",
        skills: ["vl_xiaomo_sj", "vl_xiaomo_ld"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "vl_furry_migration",
        rank: "legend",
    },
    vl_froh: {
        enable: true,
        name: "钫",
        title: "命运书写者",
        gender: "male",
        bloc: "shen",
        hp: 3,
        intro: "钫，传说中执掌一切生物命运的神祇，在《瓦尔亚那百科》中记载，他是现存的唯一的「自然神」。有传言称，《瓦尔亚那百科》便是在他的授意下委托精灵族长者写成。作为神族的他，常常以蒙眼的姿态出现并为众人降下祝福。目前还没有人看见过他睁眼的样子，据说当他睁眼，便是昭告毁灭的来临。",
        prefix: "",
        skills: ["vl_froh_sz", "vl_froh_qn", "vl_froh_sn"],
        addition: ["zhu"],
        pack: "FurryExt",
        vp: 0,
        sort: "vl_furry_migration",
        rank: "legend",
    },
    vl_ala: {
        enable: true,
        name: "阿拉安",
        title: "睚眦必报",
        gender: "male",
        bloc: "vl_niuzu",
        hp: 4,
        intro: "阿拉安，米兰寺的大弟子，在其二十四岁时出师，后四处游历。目前正在矮人之心洞穴附近修行。奥拉类似于林和炎的哥哥的存在，从小对他们多有照顾。",
        prefix: "",
        skills: ["vl_ala_dy", "vl_ala_gm"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "milan",
        rank: "epic",
    },
    vl_delagu: {
        enable: true,
        name: "德古拉",
        title: "鲜血祭祀",
        gender: "male",
        bloc: "vl_guaiwu",
        hp: "2/4",
        intro: "德古拉，出生于克拉王国东南侧的禁忌之地——被人们称为“深渊”的无人区。他是深渊的产物，属于血族，身负着长生不老的神秘特性，也有着对血液的病态执着。<br>如同深渊中潜伏的巨鲨，德古拉散发着一股无法忽视的阴森氛围。他对血液的执念像是无尽的深海，吞噬着他的理智。即便微不足道的血腥气息，也足以将他引入狂热的疯狂状态。<br>德古拉的存在就如同深渊的黑暗，克拉的人们对他心生畏惧。他的身影如鲨鱼般游走在深渊的边缘，时刻准备着向那些无知者展开致命的袭击。血液是他的媒介，也是他无法自拔的诱因，将他引向一条充满危险和疯狂的不归之路。正如那深渊入口所镌刻的石碑所言：<br>克拉之地，深渊之间，<br>伺藏恶鬼，诱人缠绵。<br>身躯长生，鲜血沐浴，<br>教诲谨记，勿贪而妄言。<br><br>魔鬼常潜，深渊长眠，<br>恶鬼既出，血光乍现，<br>若为欲求，半步黄泉。<br>教诲谨记，勿痴而妄言。<br><br>克拉众民，心当警戒，<br>守此规劝，莫贪邪谶。<br>刻骨铭心，避入此间，<br>教诲谨记，勿嗔而妄言。",
        prefix: "",
        skills: ["vl_delagu_xj", "vl_delagu_xy", "vl_delagu_bm"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "vl_furry_migration",
        rank: "legend",
    },
    vl_fate: {
        enable: true,
        name: "法特",
        title: "命运之手",
        gender: "male",
        bloc: "vl_quanzu",
        hp: 3,
        intro: "法特，生于兽人王国“克拉”南部的贫民窟中，幼年时其父母因卷入债务纠纷而死，其一人独自生活。法特十二岁时，曾尝试寻找杀死父母的仇人，未果，后在游历各处的剑术大师米亚的帮助下终于成功。法特有着天生的赌博天赋，纵横各大赌场且百战百胜，被各大赌场称为“命运之手”。",
        prefix: "",
        skills: ["vl_fate_tm", "vl_fate_ss"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "kela",
        rank: "epic",
    },
    vl_mika: {
        enable: true,
        name: "米卡",
        title: "但求浪息",
        gender: "male",
        bloc: "vl_maozu",
        hp: 4,
        intro: "米卡(6151A.W.-6342A.W.)，人鱼之海著名的“胡子”海盗团的第一任船长，作为一位海盗，她一年大部分时间都生活在海上，而营养的需求则是通过与人鱼族进行贸易获得。米卡能够成为船长，除了特殊的个人魅力以外，能够控制天气的能力也是其中之一。她能够让大海变得平静无波，保证航行的顺利进行。在她死后，许多生活在人鱼之海的船员们都以他为信仰，并自发为其建立雕塑。生活在人鱼之海的靠航行生存的人们，在航行之前或者每年的“「海行日」”，都会举行盛大的祭祀，以求得航行的顺利。",
        prefix: "",
        skills: ["vl_mika_lx", "vl_mika_pl"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "renyu",
        rank: "epic",
    },
    vl_mile: {
        enable: true,
        name: "米勒",
        title: "自然之灵",
        gender: "male",
        bloc: "vl_maozu",
        hp: 3,
        intro: "米勒，生于贵族家庭，但因为意外在十岁时，就和兄长分离。作为米尔克的弟弟，不像自己兄长一样出口成章，他认为修辞学只是无用指鹿为马。相反，他甚至说话有些结巴，这给他带来了许多困扰，他曾经因为这个毛病被其他人嘲笑。因此，他一怒之下逃到了万灵之森。<br>后来，他发现自己能够和其他人看不见的自然之灵交流，自然之灵们也很欢迎这个小家伙，他们因此结下了深厚的友谊。",
        prefix: "",
        skills: ["vl_mile_tl", "vl_mile_ly"],
        addition: ["zhu"],
        pack: "FurryExt",
        vp: 0,
        sort: "vl_furry_migration",
        rank: "epic",
    },
    vl_milism: {
        enable: true,
        name: "米里森",
        title: "黔水之灵",
        gender: "male",
        bloc: "vl_langzu",
        hp: 4,
        intro: "米里森，虎兽人与狮兽人的后代，就读于「魔法学院」。尤善水性，拥有水元素魔法天赋。而且能够转移他人的疼痛到自己，被誉为「治愈魔法师」。",
        prefix: "",
        skills: ["vl_milism_ql", "vl_milism_th", "vl_milism_gn"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "xueyuan",
        rank: "legend",
    },
    vl_muen: {
        enable: true,
        name: "牧恩",
        title: "窃贼巧手",
        gender: "male",
        bloc: "vl_langzu",
        hp: 3,
        intro: "牧恩，色塔卡荒原上的盗贼，或者说是向导。这取决于你怎么看他。熟悉沙地的人都知道，色塔卡的路从不只属于地图：风会改写沙丘，烈日会抹去足迹，夜里的寒冷则会让最坚强的旅人失去判断。牧恩就在这样的地方长大，学会了用笑容问路，也学会了在别人低头看水囊时取走腰间的钱袋。<br>他并不喜欢把自己的手艺称作偷窃。在牧恩看来，能被他悄无声息拿走的东西，本就没有被主人好好看管。他总能在最拮据的时候从缝隙中找到机会，也总能从敌人的袖口、刀鞘或马鞍旁摸出能救命的东西。有人雇他带路，有人悬赏抓他，而牧恩通常会在两边都收钱之后，选一条只有自己知道的路离开。",
        prefix: "",
        skills: ["vl_muen_tx", "vl_muen_jb"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "setaka",
        rank: "common",
    },
    vl_sangdi: {
        enable: true,
        name: "桑迪",
        title: "深巷探风者",
        gender: "male",
        bloc: "vl_quanzu",
        hp: 3,
        intro: "桑迪，出生于迦奈尔联邦，他曾因他敏锐的嗅觉和出色的直觉，在数不清的罪犯抓捕行动中积累了杰出的战绩，但终究选择了离开。原因很简单——他感觉不自由。<br>于是，桑迪决定创办自己的侦探事务所，追求他所钟爱的独立生活。然而，在平日里，客户并不是那么多，这留给了他大量的空闲时间和自主权。这种自由是宝贵的，但三三两两的案件远不能满足他的经济需求，甚至无法支付房租。桑迪常常陷入深思，如何平衡自由与生计之间的权衡。<br><br>客串原型：染柒",
        prefix: "",
        skills: ["vl_sangdi_at", "vl_sangdi_bf", "vl_sangdi_zy"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "vl_furry_migration",
        rank: "epic",
    },
    vl_yinlong: {
        enable: true,
        name: "印龙",
        title: "游龙影绰",
        gender: "female",
        bloc: "vl_longzu",
        hp: 3,
        intro: "印龙，随着一阵强烈的白光突然出现在龙之谷中的神秘龙族，受到了智慧之神哈尔斯的亲自接见。据说印龙是来自于另一平行时空的旅者，她天生热爱自然，不像其他龙族一样蔑视其他种族，而且具有媲美商业精英的经商知识，因此其在龙之谷中担任了与其他种族贸易和沟通的职务。<br><br>联动拓展：星穹防线-印龙",
        prefix: "",
        skills: ["vl_yinlong_cb", "vl_yinlong_jh"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "tuozhanliandong",
        rank: "epic",
    },
    vl_sainit: {
        enable: true,
        name: "塞涅特",
        title: "月华指引者",
        gender: "female",
        bloc: "shen",
        hp: 3,
        intro: "塞涅特，被远古神月神黛安娅的祝福的少女，体内流淌着神祇的血脉，她能够调动月光的力量。即使是清冷的月，在她的引导下，也能爆发灿烂的光芒。",
        prefix: "",
        skills: ["vl_sainit_yj", "vl_sainit_jh"],
        addition: [],
        pack: "Valyana",
        vp: 0,
        sort: "vl_furry_migration",
        rank: "epic",
    },
    vl_skry: {
        enable: true,
        name: "斯克瑞",
        title: "毒计百出",
        gender: "male",
        bloc: "vl_quanzu",
        hp: 3,
        intro: "斯克瑞，「暗影」刺杀队的队长，擅长于通过下毒的方式来完成任务，他最著名的一次刺杀任务，就是接受哈拉尔的雇佣刺杀国王盖尔德鲁。在斯克瑞几近成功时被盖尔德鲁发现，被抓住并关押进地牢。后来哈拉尔即位后释放了斯克瑞，而这次刺杀也让他名声大噪。",
        prefix: "",
        skills: ["vl_skery_ds", "vl_skery_yj"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "franying",
        rank: "epic",
    },
    vl_fox: {
        enable: true,
        name: "狐克斯",
        title: "幻梦一场",
        gender: "male",
        bloc: "vl_hulizu",
        hp: 4,
        intro: "狐克斯，来自狐人一族的年轻旅人。与大多数狐人擅长化形和迷惑不同，他的能力更接近“梦的回声”：凡是经由他亲手施展过的动作，都会在短暂的时间里留下虚幻的影子。等到夕阳沉下，影子便会沿着原本的轨迹再度显现，像一场已经醒来的梦重新发生。<br>狐克斯常戴着护目镜，背着轻便的行装在大陆各处旅行。他说自己只是喜欢看不同地方的天空，但不少赏金公会的记录都提到过同一个红狐青年：他会在战斗中先以轻松的笑容试探对手，再让先前的牌局、刀光与术式于黄昏时分接连重现。和他交手的人往往分不清哪一次是真实，哪一次只是幻梦遗留的余温。",
        prefix: "",
        skills: ["vl_fox_hm"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "vl_furry_migration",
        rank: "epic",
    },
    vl_molis: {
        enable: true,
        name: "莫莉斯",
        title: "时空跳跃者",
        gender: "female",
        bloc: "vl_hulizu",
        hp: 3,
        intro: "莫莉斯，神秘的占星术士“希顿”的女儿，受到智慧之神哈尔斯的青睐，获得了能够在时空中跳跃的能力，作为交换，莫莉斯要为哈尔斯记录各个时空发生的事情并汇报。",
        prefix: "",
        skills: ["vl_molis_hs", "vl_molis_sy"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "vl_furry_migration",
        rank: "legend",
    },
    vl_whitewolf: {
        enable: true,
        name: "华特",
        title: "固若金汤",
        gender: "male",
        bloc: "vl_langzu",
        hp: 4,
        intro: "华特，生于兽人王国“克拉”南部的贫民窟沐恩城中，是华兹的哥哥。在兽人王国最重要的巡游——“火灵日大典”被前任国王盖尔德鲁相中，与华兹一同进入王宫成为侍卫。华特的能力：“不动如山，动如雷震”，更加擅长防御与保护。在某次刺杀中因保护国王有功，被提拔为贴身侍卫，但是遭华兹嫉妒，二人反目。盖尔德鲁垮台后二人不知所踪。",
        prefix: "",
        skills: ["vl_whitewolf_wl", "vl_whitewolf_fz"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "kela",
        rank: "epic",
    },
    vl_blackwolf: {
        enable: true,
        name: "华兹",
        title: "浪潮汹涌",
        gender: "male",
        bloc: "vl_langzu",
        hp: 4,
        intro: "华兹，生于兽人王国“克拉”南部的贫民窟沐恩城中，从小与华特相依为命。在“火灵日大典”被国王盖尔德鲁相中，与华特一同进入王宫成为侍卫，后因嫉妒华特的能力，与其反目。华兹与华特不同，更擅长狂暴而快速的攻击，世人谓之：“一剑斩不摧,双刃去如来”，又赞曰：“势如涛浪汹涌，形如雨打秋风”。盖尔德鲁垮台后二人不知所踪。",
        prefix: "",
        skills: ["vl_blackwolf_cy", "vl_blackwolf_nb"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "kela",
        rank: "epic",
    },
    vl_dmoa: {
        enable: true,
        name: "多默尔",
        title: "日夜笙歌",
        gender: "female",
        bloc: "vl_hulizu",
        hp: 3,
        intro: "多默尔(7154A.W.-7366A.W.)，诞生于传统的一个兽人贵族家庭，她的父亲是宫廷的乐师，因此多默尔幼年时就展现出了惊人的乐器天赋，她能够将多种乐器组装起来进行演奏，一个人就能够达到一个乐团的演出效果。但是多默尔并不满足于接替父亲的工作。在20岁时，恰巧遇上库伦引发的魔网崩溃，当时法师人心涣散，多默尔自发的作为吟游诗人游历各国，用音乐的力量抚慰人心。",
        prefix: "",
        skills: ["vl_dmoa_sg", "vl_dmoa_yh"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "vl_furry_migration",
        rank: "epic",
    },
    vl_luwu: {
        enable: true,
        name: "陆伍",
        title: "兵圣",
        gender: "male",
        bloc: "vl_langzu",
        hp: 3,
        intro: "",
        prefix: "",
        skills: ["vl_luwu_kd", "vl_luwu_yj"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "vl_furry_migration",
        rank: "epic",
    },
    vl_liping: {
        enable: true,
        name: "李冯",
        title: "救世神医",
        gender: "male",
        bloc: "vl_langzu",
        hp: 3,
        intro: "李冯，字安民，战国前期名医。辰国兽。中元前3549年，生于辰立李家。在少时经历瘟疫，与家人别离后，寄宿在城外一户人家。期间，李冯学习从家中带出的医书，苦学医术，为附近的百姓治病，立志成为一名医者。随后，李冯游历四方，习尝百药，沿途为百姓治病，逐渐有了神医的称号。李冯总结出望闻问切的诊法，并编成《辰医书》，将千年来的医术总结，彻底形成了一套完整且科学的医学体系，开创了中医学的先河。中元前3348年，李冯在给季惠王治病上山采药中，被季国贵族派来的刺客刺杀身亡。",
        prefix: "",
        skills: ["vl_liping_ys", "vl_liping_sz", "vl_liping_yl"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "vl_furry_migration",
        rank: "legend",
    },
    vl_zhanggu: {
        enable: true,
        name: "张蛊",
        title: "蛊鸩毒医",
        gender: "male",
        bloc: "vl_langzu",
        hp: 3,
        intro: "张蛊，字季阴，战国前期毒医，辰国兽，中原前3531年于辰立生。少时随辰宣王南迁。15岁时，母亲大病，张蛊不远千里去请李冯医治，后拜李冯为师。入门后，学习李冯的医术，大有所成。但行医理念与李冯不同，认为重病与生活对人来说是一种长久的痛苦，于是在一次毒死一位李冯的重病人后，被逐出师门。后半生一直追求毒术，帮一些重病或生活无望的人解脱。晚年，思念师傅，得知其在季国，于是前往并给季惠王下了轻毒，之后不久便死于季国。中元前3348年，寿终正寝。",
        prefix: "",
        skills: ["vl_zhanggu_dy", "vl_zhanggu_gs", "vl_zhanggu_yl"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "vl_furry_migration",
        rank: "legend",
    },
    vl_xit: {
        enable: true,
        name: "希特",
        title: "夜梦龙魂",
        gender: "male",
        bloc: "vl_longzu",
        hp: 4,
        intro: "希特，龙之谷少见的拥有精神系能力龙裔，它可以强迫他人进入深眠，然后对其精神体直接发动攻击。一旦目标的精神体被击溃，那么他的肉体也会随之消亡。希特不善社交，不喜喧闹，因此隐居于龙之谷东侧的山谷之中，对于希特来说，每天最愉快的时刻就是去找印龙一同前往百花山谷，当然，对印龙来说也许是最头疼的时候，因为希特总做出一些令人无语的事情。",
        prefix: "",
        skills: ["vl_xit_xm"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "dragongu",
        rank: "common",
    },
    vl_yifa: {
        enable: true,
        name: "弈法",
        title: "言灵圣者",
        gender: "female",
        bloc: "vl_hulizu",
        hp: 3,
        intro: "弈法，《瓦尔亚那百科》中曾参加了万灵之森保卫战的大英雄弈霜的后代，是弈风的妹妹。弈法天性好动活泼，其在幼时就被检测出有稀有的魔法天赋，能够通过语言来获得其他人的能力，《百科》中不曾预言过这种能力，实属世间罕见。由于此能力，其幼时便饱受困扰，许多贪婪狡诈之徒对此能力趋之若鹜。直至其十岁，父母因此而死，后与弈风共同远离兽人王国，前往精灵之森定居。",
        prefix: "",
        skills: ["vl_yifa_xs"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "wanling",
        rank: "epic",
    },
    vl_yifeng: {
        enable: true,
        name: "弈风",
        title: "执月之手",
        gender: "male",
        bloc: "vl_langzu",
        hp: 3,
        intro: "弈风，《瓦尔亚那百科》中曾参加了万灵之森保卫战的大英雄弈霜的后代，是弈法的哥哥，与弈法共同居住在万灵之森外围的不知名小村落中。弈风生性沉稳，不喜言辞，与弈法截然相反。据传，其拥有一把能够逆转因果的弓，名曰霜月，通体泛着银月丝绸般的光芒。被弓箭射中者，若其行径正义，心无不端，则平安无事，而若其为邪恶之辈，将会遭受最为严峻的痛苦，直至其为罪行忏悔。",
        prefix: "",
        skills: ["vl_kref_yz", "vl_yifeng_ml"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "wanling",
        rank: "rare",
    },
}
