export const character = {
    vl_templete: {
        enable: false,
        name: '🐺名字',
        title: '头衔',
        gender: 'male',
        bloc: '势力',
        hp: 3,
        intro: `简要介绍`,
        prefix: "🐺",
        skills: [],
        addition: [],
        pack: '武将包',
        vp: 0,
        sort: '分类',
        rank: '评级'
    },
    vl_fangsuan: {
        enable: true,
        name: 'SP钫酸',
        title: '无畏暴君',
        gender: 'male',
        bloc: 'vl_hulizu',
        hp: 3,
        vp: 3,
        intro: `
钫酸出生于瓦尔亚纳大陆北部的一个小公国。他的父亲是那片领地的公爵，母亲来自一个没落的精灵家族。他幼年时便显露出异于常人的天赋——左眼能看穿谎言的纹理，右眼能捕捉魔法的流动。十岁那年，他当着宫廷法师的面，用目光让一头狂暴的狮鹫安静下来，随后命令它撞死在城墙上。这件事被记录为他的第一次“催眠”。公爵没有感到欣慰，而是恐惧。他试图将儿子送往边境的修道院，但车队在途中遭遇山匪，随行的护卫全部死亡，钫酸独自返回城堡，身后跟着那伙山匪的头颅。公爵当晚暴毙，死因不明。十三岁的钫酸继承了爵位，随后用三年时间吞并了周边六个领地。
<br>他的扩张从未停止。他没有盟友，只有暂时未被征服的敌人。他使用军队、魔法、暗杀，也使用他自己的眼睛。只要与他对视，对方就无法拒绝他的命令。这种能力让他绕过所有谈判桌，直接抵达结果。二十岁时，他已经控制了大陆北部三分之一的土地。他继续向南推进，遭遇了精灵联军、矮人王国和人类帝国的联合抵抗。这场战争持续了七年。钫酸在战争末期独自进入精灵的圣殿，与当时掌管大陆神力的十二位神祇对峙。他用了三天时间，逐一撕碎了那些神的化身。神祇陨落时，整个大陆的地脉都发生了震颤。第四天，他走出圣殿，宣布自己为唯一的王。
<br>统一后的第八年，钫酸颁布了“犬令”。所有臣民，不论贵族或平民，都被要求佩戴项圈，行为规范由皇家法典统一规定。他废除了原有的法律体系，将所有权力收归王座。反抗者被投入地牢，或直接由他的骑士处决。他的四位骑士——望朔、小c、阿然、阿早——各自掌管审判、传讯、死亡与治愈，形成一套完整的统治架构。第五位骑士莱恩曾是他最信任的将领，但在一场由钫酸亲自设计的构陷中，莱恩被迫杀死自己的挚友，精神崩溃，被囚禁于王宫地底深处。钫酸保留了莱恩的骑士头衔，但不再允许他踏出牢笼。
<br>钫酸的性格中有一种冷静的残酷。他从不因愤怒而杀人，也不因快感而折磨。他的行动基于效率和必要性。当他认为某件事没有价值时，他会直接终结它。他很少提高音量，眼神的变化足以传递指令。他的臣民学会在他注视时低头，因为直视他的双眼意味着失去自我。他很少使用催眠能力，因为他觉得让一个人清醒地服从更有趣。
<br>统治稳定后，钫酸开始感到一种持续的乏味。战争、征服、立法，这些事都结束了。他拥有一切，但一切都在预期之内。这种状态持续了数月，直到一位自称泡芙的术士从王宫的穹顶降落。泡芙带来了一套名为“挑担的游戏”的规则，用机关与谜题制造困境和抉择。钫酸接受了这个游戏，因为游戏本身不可预测，而不可预测是他唯一尚未体验的事物。他将游戏的执行权交给旁人，自己作为观察者坐在王座上。游戏开始后，他的时间才重新流动起来。他不会亲自裁定每一道规则，但他会介入游戏变得乏味的时刻——以他自己的方式。
<br>他被称为“阴鸷神王”。这个称号源于他对神祇的屠杀，也源于他那种深藏不露的、近乎残酷的冷静。他的额头那枚红色印记，是他在撕碎最后一位神祇时，对方临死前烙下的诅咒烙印。神祇说，这印记会让他永远记着“被注视”的滋味。钫酸没有去除它，因为他觉得这印记让他看起来更威严。他是瓦尔亚纳唯一的王，也是这片大陆最后的神。`,
        prefix: "SP",
        skills: ['vl_fangsuan_ximing', 'vl_fangsun_mishe', 'vl_fangsuan_kuangluan'],
        addition: ['zhu'],
        pack: 'Valyana',
        sort: 'vl_tiaodan',
        rank: 'legend'
    },
    vl_wangshuo: {
        enable: true,
        name: 'SP望朔',
        title: '守护之骑',
        gender: 'male',
        bloc: 'vl_shizu',
        hp: '3/4',
        intro: `
望朔是钫酸座下的第一位骑士，掌管审判。他是狮子兽人，头顶一对白色龙角，身上常年带着竹子的清淡气息。他的铠甲为白色，披挂为绿色，手持一柄被称为“圣剑”的长剑。这柄剑并不以锋利著称，而是能感应谎言与罪责，在审判时显现光芒。望朔的形象通常被描述为正义与光明的化身，他在公开场合的行为也符合这一描述——他主持法庭，裁决争端，从不徇私。
<br>他与钫酸签订了永世不得背叛的契约。这份契约并非出于恐惧或利益，而是基于他对秩序的认同。望朔认为，钫酸虽然手段残酷，但建立了大陆千年以来唯一统一的法度。他忠于钫酸，忠于王座，也忠于自己内心对“审判”的定义。他会在公开场合严格执行钫酸的命令，但在私下场合，他有时会延长审问的时间，或允许犯人申诉。这种行为并未违反契约，钫酸也从未过问。
<br>望朔的性格中有一种近乎固执的正直。他相信规则本身的意义，而非规则制定者的意志。如果钫酸的命令明显违背他认定的法理，他会先执行，然后请求复议。钫酸偶尔会驳回他的请求，但多数时候会调整指令。两人之间形成了一种微妙的制衡——望朔是唯一一个能在王座前提出异议而不被惩罚的骑士。其他骑士对此心知肚明，但从未有人点破。
<br>他的龙角是幼年时被一头白龙抚养留下的痕迹。那头龙在他成年时死去，将角留给了他。望朔从不谈论这件事，也不允许其他人提及。他将那段过往锁在记忆深处，像对待一道陈年旧伤一样，不触碰，不展示。`,
        prefix: "SP",
        skills: ['vl_wangshuo_shouwang', 'vl_wangshuo_maofang'],
        addition: [],
        pack: 'Valyana',
        sort: 'vl_tiaodan',
        rank: 'epic'
    },
    vl_chen: {
        enable: true,
        name: "辰",
        title: "",
        gender: "male",
        bloc: "vl_langzu",
        hp: 3,
        intro: "辰，常年游走于边地与战场之间的狼族弓手。他沉默寡言，却总能在最合适的距离射出最致命的一箭。<br>据说辰对武器与阵势有着异于常人的敏锐直觉，凡是被他盯上的目标，往往还没看清来路，便已先失了先机。对他而言，战斗不是喧嚣的拼杀，而是一次次精准的落点与时机的压制。",
        prefix: "",
        skills: ["vl_chen_ly", "vl_chen_jx", "vl_chen_lz"],
        addition: [],
        pack: "Valyana",
        vp: 0,
        sort: "vl_tiaodan",
        rank: "epic",
    },
    vl_buline: {
        enable: true,
        name: "布莱恩",
        title: "邪恶法师",
        gender: "male",
        bloc: "vl_maozu",
        hp: 4,
        intro: "布莱恩是来自地狱的无上法术的咏唱者（自称），他做过的坏事数不胜数，包括但不限于：赶走偷吃鸡的黄鼠狼，杀死袭击村民的强盗，强迫受保护费的官兵学狗叫之类，因此其深受百姓憎恶（自称）。他致力于成为整个兽人王国最邪恶的黑魔法师，并为此努力着。《瓦尔亚那百科》中曾预言布莱恩有着黑暗生物的血统与两幅面孔，但似乎其本身并不知情。",
        prefix: "",
        skills: ["vl_buline_qm", "vl_buline_yt"],
        addition: [],
        pack: "Valyana",
        vp: 0,
        sort: "wanling",
        rank: "junk",
    },
    vl_sisk: {
        enable: true,
        name: "西斯科",
        title: "嗜血狂徒",
        gender: "male",
        bloc: "vl_huzu",
        hp: "4/5",
        intro: "西斯科，罕见的狮兽人与吸血鬼的后代。拥有极其强力的身体素质与高超的种族天赋。后来被苍月狼兽所救，加入了「流亡者」雇佣兵团。其对血液极为敏感，些许的血腥味也会导致其进入狂暴。",
        prefix: "",
        skills: ["vl_sisk_yx", "vl_sisk_wg", "vl_sisk_jx"],
        addition: [],
        pack: "Valyana",
        vp: "2/5",
        sort: "yongbing",
        rank: "epic",
    },
    vl_aerte: {
        enable: true,
        name: "阿尔特",
        title: "缴械武解",
        gender: "male",
        bloc: "vl_langzu",
        hp: 4,
        intro: "阿尔特，出身于克拉北境的狼族骑士团。他身披白甲，常以巨剑立于阵前，却并不以杀戮为荣。北境旧俗中，决斗的胜负往往在第一击前便已决定——谁能先夺下对方的武器，谁便取得审判的权力。阿尔特正是在这种严苛训练中成长起来的骑士。<br>他曾在边境战争中独自拦下一支掠夺队，没有斩下任何一人的头颅，只是逐一卸去他们手中的刀剑，再将缴获的武器分给身后的民兵。自那以后，人们开始称他为“缴械武解”。阿尔特相信武器本身没有善恶，真正需要被制止的是握住武器的人。因此，他常常夺下敌人的杀意，再把新的力量交到更值得信任的人手中。",
        prefix: "",
        skills: ["vl_aerte_jw"],
        addition: [],
        pack: "Valyana",
        vp: 0,
        sort: "kela",
        rank: "epic",
    },
    vl_hars: {
        enable: true,
        name: "哈尔斯",
        title: "全知之神",
        gender: "male",
        bloc: "shen",
        hp: 4,
        intro: "哈尔斯，兽人的智慧之神。其拥有惑人心魄的能力。根据矮人族与部分兽人族内部记录。哈尔斯能够直接降临到任何一人身上，据此观察世界。而被降临的人则被称为「神降者」。由于任何人都有可能成为「神降者」。因此，哈尔斯的眼线遍布整个大陆，而其本人也被称为「全知之神」。",
        prefix: "",
        skills: ["vl_hars_sj", "vl_hars_hr"],
        addition: [],
        pack: "Valyana",
        vp: 0,
        sort: "shoushen",
        rank: "rare",
    },
    vl_yada: {
        enable: true,
        name: "亚达",
        title: "百变千面",
        gender: "male",
        bloc: "vl_huzu",
        hp: 4,
        intro: "亚达，暗影刺杀队的化妆师，在刺杀行动中，为了避免被其他人发现，如何伪装自己就是小队最大的难题。而亚达他凭着一手出人意料的易容技巧得到了队长斯克瑞的青睐，并在斯克瑞刺杀国王的那次行动中提供了伪装。",
        prefix: "",
        skills: ["vl_yada_yl", "vl_yada_yy"],
        addition: [],
        pack: "Valyana",
        vp: 0,
        sort: "franying",
        rank: "rare",
    },
    vl_hundun: {
        enable: true,
        name: "混沌",
        title: "死亡使者",
        gender: "male",
        bloc: "shen",
        hp: 4,
        intro: "混沌，虽然他的知名度不如尧和洛一般，但是他确实是瓦尔亚那大陆上极为重要的神明之一。在尧和洛将灵魂拘回冥界后，混沌则会根据他们生前的事迹裁决是否对他们执行惩罚或奖励。混沌手中的双镰名为死魂幽镰，可以无视物理法则直接对灵体产生伤害。",
        prefix: "",
        skills: ["vl_hundun_sy", "vl_hundun_sl", "vl_hundun_sp"],
        addition: [],
        pack: "Valyana",
        vp: 0,
        sort: "shoushen",
        rank: "legend",
    },
    vl_xiaomo: {
        enable: true,
        name: "泡芙",
        title: "破击无声",
        gender: "male",
        bloc: "vl_maozu",
        hp: 3,
        intro: "泡芙，是一名行踪不定的猫族旅者，也是将“挑担的游戏”带到钫酸王座前的人。与他轻巧的外表不同，泡芙对危险有着近乎本能的判断。他很少正面承受攻击，总能在刀锋落下前错开半步，让伤害像掠过水面的风一样消散。<br>据说泡芙曾在某个异界战场中学习过把护甲化作冲击力的技巧。他平日看似懒散，真正出手时却极快，能够将积蓄的防护一次性压进短促的突袭之中，因此得名“闪击”。他不喜欢解释自己的来历，只说自己是在寻找一场足够有趣、足够危险，也足够不讲道理的游戏。",
        skills: ["vl_xiaomo_sj", "vl_xiaomo_ld"],
        addition: [],
        pack: "Valyana",
        vp: 0,
        sort: "kela",
        rank: "legend",
    },
    vl_froh: {
        enable: true,
        name: "钫",
        title: "命运书写者",
        gender: "male",
        bloc: "shen",
        hp: 3,
        intro: "钫，传说中执掌一切生物命运的神祇，在《瓦尔亚那百科》中记载，他是现存的唯一的「自然神」。有传言称，《瓦尔亚那百科》便是在他的授意下委托精灵族长者写成。作为神族的他，常常以蒙眼的姿态出现并为众人降下祝福。目前还没有人看见过他睁眼的样子，据说当他睁眼，便是昭告毁灭的来临。",
        prefix: "",
        skills: ["vl_froh_sz", "vl_froh_qn", "vl_froh_sn"],
        addition: ["zhu"],
        pack: "Valyana",
        vp: 0,
        sort: "shoushen",
        rank: "legend",
    },
    vl_ala: {
        enable: true,
        name: "阿拉安",
        title: "睚眦必报",
        gender: "male",
        bloc: "vl_niuzu",
        hp: 4,
        intro: "阿拉安，米兰寺的大弟子，在其二十四岁时出师，后四处游历。目前正在矮人之心洞穴附近修行。奥拉类似于林和炎的哥哥的存在，从小对他们多有照顾。",
        prefix: "",
        skills: ["vl_ala_dy", "vl_ala_gm"],
        addition: [],
        pack: "Valyana",
        vp: 0,
        sort: "milan",
        rank: "epic",
    },
    vl_delagu: {
        enable: true,
        name: "德古拉",
        title: "鲜血祭祀",
        gender: "male",
        bloc: "vl_guaiwu",
        hp: "2/4",
        intro: "德古拉，出生于克拉王国东南侧的禁忌之地——被人们称为“深渊”的无人区。他是深渊的产物，属于血族，身负着长生不老的神秘特性，也有着对血液的病态执着。<br>如同深渊中潜伏的巨鲨，德古拉散发着一股无法忽视的阴森氛围。他对血液的执念像是无尽的深海，吞噬着他的理智。即便微不足道的血腥气息，也足以将他引入狂热的疯狂状态。<br>德古拉的存在就如同深渊的黑暗，克拉的人们对他心生畏惧。他的身影如鲨鱼般游走在深渊的边缘，时刻准备着向那些无知者展开致命的袭击。血液是他的媒介，也是他无法自拔的诱因，将他引向一条充满危险和疯狂的不归之路。正如那深渊入口所镌刻的石碑所言：<br>克拉之地，深渊之间，<br>伺藏恶鬼，诱人缠绵。<br>身躯长生，鲜血沐浴，<br>教诲谨记，勿贪而妄言。<br><br>魔鬼常潜，深渊长眠，<br>恶鬼既出，血光乍现，<br>若为欲求，半步黄泉。<br>教诲谨记，勿痴而妄言。<br><br>克拉众民，心当警戒，<br>守此规劝，莫贪邪谶。<br>刻骨铭心，避入此间，<br>教诲谨记，勿嗔而妄言。",
        prefix: "",
        skills: ["vl_delagu_xj", "vl_delagu_xy", "vl_delagu_bm"],
        addition: [],
        pack: "Valyana",
        vp: 0,
        sort: "kela",
        rank: "legend",
    },
    vl_fate: {
        enable: true,
        name: "法特",
        title: "命运之手",
        gender: "male",
        bloc: "vl_quanzu",
        hp: 3,
        intro: "法特，生于兽人王国“克拉”南部的贫民窟中，幼年时其父母因卷入债务纠纷而死，其一人独自生活。法特十二岁时，曾尝试寻找杀死父母的仇人，未果，后在游历各处的剑术大师米亚的帮助下终于成功。法特有着天生的赌博天赋，纵横各大赌场且百战百胜，被各大赌场称为“命运之手”。",
        prefix: "",
        skills: ["vl_fate_tm", "vl_fate_ss"],
        addition: [],
        pack: "Valyana",
        vp: 0,
        sort: "kela",
        rank: "epic",
    },
    vl_mika: {
        enable: true,
        name: "米卡",
        title: "但求浪息",
        gender: "male",
        bloc: "vl_maozu",
        hp: 4,
        intro: "米卡(6151A.W.-6342A.W.)，人鱼之海著名的“胡子”海盗团的第一任船长，作为一位海盗，她一年大部分时间都生活在海上，而营养的需求则是通过与人鱼族进行贸易获得。米卡能够成为船长，除了特殊的个人魅力以外，能够控制天气的能力也是其中之一。她能够让大海变得平静无波，保证航行的顺利进行。在她死后，许多生活在人鱼之海的船员们都以他为信仰，并自发为其建立雕塑。生活在人鱼之海的靠航行生存的人们，在航行之前或者每年的“「海行日」”，都会举行盛大的祭祀，以求得航行的顺利。",
        prefix: "",
        skills: ["vl_mika_lx", "vl_mika_pl"],
        addition: [],
        pack: "Valyana",
        vp: 0,
        sort: "renyu",
        rank: "epic",
    },
    vl_mile: {
        enable: true,
        name: "米勒",
        title: "自然之灵",
        gender: "male",
        bloc: "vl_maozu",
        hp: 3,
        intro: "米勒，生于贵族家庭，但因为意外在十岁时，就和兄长分离。作为米尔克的弟弟，不像自己兄长一样出口成章，他认为修辞学只是无用指鹿为马。相反，他甚至说话有些结巴，这给他带来了许多困扰，他曾经因为这个毛病被其他人嘲笑。因此，他一怒之下逃到了万灵之森。<br>后来，他发现自己能够和其他人看不见的自然之灵交流，自然之灵们也很欢迎这个小家伙，他们因此结下了深厚的友谊。",
        prefix: "",
        skills: ["vl_mile_tl", "vl_mile_ly"],
        addition: ["zhu"],
        pack: "Valyana",
        vp: 0,
        sort: "wanling",
        rank: "epic",
    },
    vl_milism: {
        enable: true,
        name: "米里森",
        title: "黔水之灵",
        gender: "male",
        bloc: "vl_langzu",
        hp: 4,
        intro: "米里森，虎兽人与狮兽人的后代，就读于「魔法学院」。尤善水性，拥有水元素魔法天赋。而且能够转移他人的疼痛到自己，被誉为「治愈魔法师」。",
        prefix: "",
        skills: ["vl_milism_ql", "vl_milism_th", "vl_milism_gn"],
        addition: [],
        pack: "Valyana",
        vp: 0,
        sort: "xueyuan",
        rank: "legend",
    },
    vl_muen: {
        enable: true,
        name: "牧恩",
        title: "窃贼巧手",
        gender: "male",
        bloc: "vl_langzu",
        hp: 3,
        intro: "牧恩，色塔卡荒原上的盗贼，或者说是向导。这取决于你怎么看他。熟悉沙地的人都知道，色塔卡的路从不只属于地图：风会改写沙丘，烈日会抹去足迹，夜里的寒冷则会让最坚强的旅人失去判断。牧恩就在这样的地方长大，学会了用笑容问路，也学会了在别人低头看水囊时取走腰间的钱袋。<br>他并不喜欢把自己的手艺称作偷窃。在牧恩看来，能被他悄无声息拿走的东西，本就没有被主人好好看管。他总能在最拮据的时候从缝隙中找到机会，也总能从敌人的袖口、刀鞘或马鞍旁摸出能救命的东西。有人雇他带路，有人悬赏抓他，而牧恩通常会在两边都收钱之后，选一条只有自己知道的路离开。",
        prefix: "",
        skills: ["vl_muen_tx", "vl_muen_jb"],
        addition: [],
        pack: "Valyana",
        vp: 0,
        sort: "setaka",
        rank: "common",
    },
    vl_sangdi: {
        enable: true,
        name: "桑迪",
        title: "深巷探风者",
        gender: "male",
        bloc: "vl_quanzu",
        hp: 3,
        intro: "桑迪，出生于迦奈尔联邦，他曾因他敏锐的嗅觉和出色的直觉，在数不清的罪犯抓捕行动中积累了杰出的战绩，但终究选择了离开。原因很简单——他感觉不自由。<br>于是，桑迪决定创办自己的侦探事务所，追求他所钟爱的独立生活。然而，在平日里，客户并不是那么多，这留给了他大量的空闲时间和自主权。这种自由是宝贵的，但三三两两的案件远不能满足他的经济需求，甚至无法支付房租。桑迪常常陷入深思，如何平衡自由与生计之间的权衡。<br><br>客串原型：染柒",
        prefix: "",
        skills: ["vl_sangdi_at", "vl_sangdi_bf", "vl_sangdi_zy"],
        addition: [],
        pack: "Valyana",
        vp: 0,
        sort: "jianaier",
        rank: "epic",
    },
    vl_yinlong: {
        enable: true,
        name: "印龙",
        title: "游龙影绰",
        gender: "female",
        bloc: "vl_longzu",
        hp: 3,
        intro: "印龙，随着一阵强烈的白光突然出现在龙之谷中的神秘龙族，受到了智慧之神哈尔斯的亲自接见。据说印龙是来自于另一平行时空的旅者，她天生热爱自然，不像其他龙族一样蔑视其他种族，而且具有媲美商业精英的经商知识，因此其在龙之谷中担任了与其他种族贸易和沟通的职务。<br><br>联动拓展：星穹防线-印龙",
        prefix: "",
        skills: ["vl_yinlong_cb", "vl_yinlong_jh"],
        addition: [],
        pack: "Valyana",
        vp: 0,
        sort: "dragongu",
        rank: "epic",
    },
    vl_sainit: {
        enable: true,
        name: "塞涅特",
        title: "月华指引者",
        gender: "female",
        bloc: "shen",
        hp: 3,
        intro: "塞涅特，被远古神月神黛安娅的祝福的少女，体内流淌着神祇的血脉，她能够调动月光的力量。即使是清冷的月，在她的引导下，也能爆发灿烂的光芒。",
        prefix: "",
        skills: ["vl_sainit_yj", "vl_sainit_jh"],
        addition: [],
        pack: "Valyana",
        vp: 0,
        sort: "kela",
        rank: "epic",
    },
    vl_skry: {
        enable: true,
        name: "斯克瑞",
        title: "毒计百出",
        gender: "male",
        bloc: "vl_quanzu",
        hp: 3,
        intro: "斯克瑞，「暗影」刺杀队的队长，擅长于通过下毒的方式来完成任务，他最著名的一次刺杀任务，就是接受哈拉尔的雇佣刺杀国王盖尔德鲁。在斯克瑞几近成功时被盖尔德鲁发现，被抓住并关押进地牢。后来哈拉尔即位后释放了斯克瑞，而这次刺杀也让他名声大噪。",
        prefix: "",
        skills: ["vl_skery_ds", "vl_skery_yj"],
        addition: [],
        pack: "Valyana",
        vp: 0,
        sort: "franying",
        rank: "epic",
    },
    vl_fox: {
        enable: true,
        name: "狐克斯",
        title: "幻梦一场",
        gender: "male",
        bloc: "vl_hulizu",
        hp: 4,
        intro: "狐克斯，来自狐人一族的年轻旅人。与大多数狐人擅长化形和迷惑不同，他的能力更接近“梦的回声”：凡是经由他亲手施展过的动作，都会在短暂的时间里留下虚幻的影子。等到夕阳沉下，影子便会沿着原本的轨迹再度显现，像一场已经醒来的梦重新发生。<br>狐克斯常戴着护目镜，背着轻便的行装在大陆各处旅行。他说自己只是喜欢看不同地方的天空，但不少赏金公会的记录都提到过同一个红狐青年：他会在战斗中先以轻松的笑容试探对手，再让先前的步法、刀光与术式于黄昏时分接连重现。和他交手的人往往分不清哪一次是真实，哪一次只是幻梦遗留的余温。",
        prefix: "",
        skills: ["vl_fox_hm"],
        addition: [],
        pack: "Valyana",
        vp: 0,
        sort: "kela",
        rank: "epic",
    },
    vl_molis: {
        enable: true,
        name: "莫莉斯",
        title: "时空跳跃者",
        gender: "female",
        bloc: "vl_hulizu",
        hp: 3,
        intro: "莫莉斯，神秘的占星术士“希顿”的女儿，受到智慧之神哈尔斯的青睐，获得了能够在时空中跳跃的能力，作为交换，莫莉斯要为哈尔斯记录各个时空发生的事情并汇报。",
        prefix: "",
        skills: ["vl_molis_hs", "vl_molis_sy"],
        addition: [],
        pack: "Valyana",
        vp: 0,
        sort: "kela",
        rank: "legend",
    },
    vl_whitewolf: {
        enable: true,
        name: "华特",
        title: "固若金汤",
        gender: "male",
        bloc: "vl_langzu",
        hp: 4,
        intro: "华特，生于兽人王国“克拉”南部的贫民窟沐恩城中，是华兹的哥哥。在兽人王国最重要的巡游——“火灵日大典”被前任国王盖尔德鲁相中，与华兹一同进入王宫成为侍卫。华特的能力：“不动如山，动如雷震”，更加擅长防御与保护。在某次刺杀中因保护国王有功，被提拔为贴身侍卫，但是遭华兹嫉妒，二人反目。盖尔德鲁垮台后二人不知所踪。",
        prefix: "",
        skills: ["vl_whitewolf_wl", "vl_whitewolf_fz"],
        addition: [],
        pack: "Valyana",
        vp: 0,
        sort: "kela",
        rank: "epic",
    },
    vl_blackwolf: {
        enable: true,
        name: "华兹",
        title: "浪潮汹涌",
        gender: "male",
        bloc: "vl_langzu",
        hp: 4,
        intro: "华兹，生于兽人王国“克拉”南部的贫民窟沐恩城中，从小与华特相依为命。在“火灵日大典”被国王盖尔德鲁相中，与华特一同进入王宫成为侍卫，后因嫉妒华特的能力，与其反目。华兹与华特不同，更擅长狂暴而快速的攻击，世人谓之：“一剑斩不摧,双刃去如来”，又赞曰：“势如涛浪汹涌，形如雨打秋风”。盖尔德鲁垮台后二人不知所踪。",
        prefix: "",
        skills: ["vl_blackwolf_cy", "vl_blackwolf_nb"],
        addition: [],
        pack: "Valyana",
        vp: 0,
        sort: "kela",
        rank: "epic",
    },
    vl_dmoa: {
        enable: true,
        name: "多默尔",
        title: "日夜笙歌",
        gender: "female",
        bloc: "vl_hulizu",
        hp: 3,
        intro: "多默尔(7154A.W.-7366A.W.)，诞生于传统的一个兽人贵族家庭，她的父亲是宫廷的乐师，因此多默尔幼年时就展现出了惊人的乐器天赋，她能够将多种乐器组装起来进行演奏，一个人就能够达到一个乐团的演出效果。但是多默尔并不满足于接替父亲的工作。在20岁时，恰巧遇上库伦引发的魔网崩溃，当时法师人心涣散，多默尔自发的作为吟游诗人游历各国，用音乐的力量抚慰人心。",
        prefix: "",
        skills: ["vl_dmoa_sg", "vl_dmoa_yh"],
        addition: [],
        pack: "Valyana",
        vp: 0,
        sort: "kela",
        rank: "epic",
    },
    vl_luwu: {
        enable: true,
        name: "陆伍",
        title: "兵圣",
        gender: "male",
        bloc: "vl_langzu",
        hp: 3,
        intro: "陆伍，出身军伍的狼族统帅，曾以极少兵力在混战中稳住全线，因此被人称作“兵圣”。他不以蛮勇取胜，更擅长利用敌人的破绽与阵形变化，将战场一步步引入自己设下的局中。<br>在许多老兵眼里，陆伍最可怕的不是锋刃，而是他始终冷静的判断。只要他还站在阵前，敌人的退路就往往已经被悄然封死。",
        prefix: "",
        skills: ["vl_luwu_kd", "vl_luwu_yj"],
        addition: [],
        pack: "Valyana",
        vp: 0,
        sort: "dalu_lingmian",
        rank: "epic",
    },
    vl_liping: {
        enable: true,
        name: "李冯",
        title: "救世神医",
        gender: "male",
        bloc: "vl_langzu",
        hp: 3,
        intro: "李冯，字安民，战国前期名医。辰国兽。中元前3549年，生于辰立李家。在少时经历瘟疫，与家人别离后，寄宿在城外一户人家。期间，李冯学习从家中带出的医书，苦学医术，为附近的百姓治病，立志成为一名医者。随后，李冯游历四方，习尝百药，沿途为百姓治病，逐渐有了神医的称号。李冯总结出望闻问切的诊法，并编成《辰医书》，将千年来的医术总结，彻底形成了一套完整且科学的医学体系，开创了中医学的先河。中元前3348年，李冯在给季惠王治病上山采药中，被季国贵族派来的刺客刺杀身亡。",
        prefix: "",
        skills: ["vl_liping_ys", "vl_liping_sz", "vl_liping_yl"],
        addition: [],
        pack: "Valyana",
        vp: 0,
        sort: "dalu_lingmian",
        rank: "legend",
    },
    vl_zhanggu: {
        enable: true,
        name: "张蛊",
        title: "蛊鸩毒医",
        gender: "male",
        bloc: "vl_langzu",
        hp: 3,
        intro: "张蛊，字季阴，战国前期毒医，辰国兽，中原前3531年于辰立生。少时随辰宣王南迁。15岁时，母亲大病，张蛊不远千里去请李冯医治，后拜李冯为师。入门后，学习李冯的医术，大有所成。但行医理念与李冯不同，认为重病与生活对人来说是一种长久的痛苦，于是在一次毒死一位李冯的重病人后，被逐出师门。后半生一直追求毒术，帮一些重病或生活无望的人解脱。晚年，思念师傅，得知其在季国，于是前往并给季惠王下了轻毒，之后不久便死于季国。中元前3348年，寿终正寝。",
        prefix: "",
        skills: ["vl_zhanggu_dy", "vl_zhanggu_gs", "vl_zhanggu_yl"],
        addition: [],
        pack: "Valyana",
        vp: 0,
        sort: "dalu_lingmian",
        rank: "legend",
    },
    vl_xit: {
        enable: true,
        name: "希特",
        title: "夜梦龙魂",
        gender: "male",
        bloc: "vl_longzu",
        hp: 4,
        intro: "希特，龙之谷少见的拥有精神系能力龙裔，它可以强迫他人进入深眠，然后对其精神体直接发动攻击。一旦目标的精神体被击溃，那么他的肉体也会随之消亡。希特不善社交，不喜喧闹，因此隐居于龙之谷东侧的山谷之中，对于希特来说，每天最愉快的时刻就是去找印龙一同前往百花山谷，当然，对印龙来说也许是最头疼的时候，因为希特总做出一些令人无语的事情。",
        prefix: "",
        skills: ["vl_xit_xm"],
        addition: [],
        pack: "Valyana",
        vp: 0,
        sort: "dragongu",
        rank: "common",
    },
    vl_azao: {
        enable: true,
        name: "阿早",
        title: "",
        gender: "male",
        bloc: "vl_longzu",
        hp: 4,
        intro: "阿早，来自龙族边缘地带的年轻旅者，行事轻快，像总比旁人早一步醒来。别看他平日说话懒散，真到关键时刻，他的反应快得近乎本能，总能在风声未落时先护住自己想护的人。<br>他习惯把承诺看得比性命更重，也因此常被卷进一些并不轻松的麻烦里。对阿早来说，活着不只是呼吸，更是把该守的东西守到最后。",
        prefix: "",
        skills: ["vl_azao_huxi", "vl_azao_guishi"],
        addition: [],
        pack: "Valyana",
        vp: 0,
        sort: "dragongu",
        rank: "epic",
    },
    vl_yifa: {
        enable: true,
        name: "弈法",
        title: "言灵圣者",
        gender: "female",
        bloc: "vl_hulizu",
        hp: 3,
        intro: "弈法，《瓦尔亚那百科》中曾参加了万灵之森保卫战的大英雄弈霜的后代，是弈风的妹妹。弈法天性好动活泼，其在幼时就被检测出有稀有的魔法天赋，能够通过语言来获得其他人的能力，《百科》中不曾预言过这种能力，实属世间罕见。由于此能力，其幼时便饱受困扰，许多贪婪狡诈之徒对此能力趋之若鹜。直至其十岁，父母因此而死，后与弈风共同远离兽人王国，前往精灵之森定居。",
        prefix: "",
        skills: ["vl_yifa_xs"],
        addition: [],
        pack: "Valyana",
        vp: 0,
        sort: "wanling",
        rank: "epic",
    },
    vl_yifeng: {
        enable: true,
        name: "弈风",
        title: "执月之手",
        gender: "male",
        bloc: "vl_langzu",
        hp: 3,
        intro: "弈风，《瓦尔亚那百科》中曾参加了万灵之森保卫战的大英雄弈霜的后代，是弈法的哥哥，与弈法共同居住在万灵之森外围的不知名小村落中。弈风生性沉稳，不喜言辞，与弈法截然相反。据传，其拥有一把能够逆转因果的弓，名曰霜月，通体泛着银月丝绸般的光芒。被弓箭射中者，若其行径正义，心无不端，则平安无事，而若其为邪恶之辈，将会遭受最为严峻的痛苦，直至其为罪行忏悔。",
        prefix: "",
        skills: ["vl_kref_yz", "vl_yifeng_ml"],
        addition: [],
        pack: "Valyana",
        vp: 0,
        sort: "wanling",
        rank: "rare",
    },
    vl_yue: {
        enable: true,
        name: "岳",
        title: "",
        gender: "male",
        bloc: "vl_huzu",
        hp: "1/5/3",
        intro: "岳，沉默而自持的虎族战士，常以近乎苛刻的方式约束自己。他不喜欢多余的言辞，也不屑于把胜负寄托给运气，更愿意用最直接的方式迎接每一次对决。<br>在旁人看来，岳像一块难以撼动的山石；可真正交手后才会发现，他愿意把代价一并背在身上，只为换来一次足够彻底的反击。",
        prefix: "",
        skills: ["vl_yue_jd", "vl_yue_hq"],
        addition: [],
        pack: "Valyana",
        vp: 0,
        sort: "vl_tiaodan",
        rank: "legend",
    },
    vl_ranxing: {
        enable: true,
        name: "燃星",
        title: "噬业罪羊",
        gender: "male",
        bloc: "vl_yangzu",
        hp: 3,
        intro: "燃星，生来便带着异样火息的羊族青年，像一团不肯熄灭的余烬。旁人眼中的罪与业，在他身上反倒会化作更旺的火，让他在混乱中越战越烈。<br>他既像受难者，也像宣判者，总能在别人的破绽里燃起自己的锋芒。凡是被他盯上的目标，很少还能保持原本的步调。",
        prefix: "",
        skills: ["vl_ranxing_tx", "vl_ranxing_sy", "vl_ranxing_pq"],
        addition: [],
        pack: "Valyana",
        vp: 0,
        sort: "vl_tiaodan",
        rank: "legend",
    },
    vl_bofeng: {
        enable: true,
        name: "迟风",
        title: "玄色一剑",
        gender: "male",
        bloc: "vl_langzu",
        hp: 4,
        intro: "迟风，出身于克拉边境的狼族剑士，性情如名，出手却从不迟缓。<br>他惯以夺势、断招为先，常在敌人尚未站稳时便将局势撕开一道缺口。对他而言，剑不是单纯的杀器，而是逼迫对手在短瞬间做出选择的筹码。那些被他盯上的目标，往往还没来得及整理架势与兵刃，便已先被他拆去几分底气。",
        prefix: "",
        skills: ["vl_bofeng_aj", "vl_bofeng_ld", "vl_bofeng_ws"],
        addition: [],
        pack: "Valyana",
        vp: 0,
        sort: "kela",
        rank: "legend",
    },
    vl_ciyu: {
        enable: true,
        name: "迟雨",
        title: "素色一心",
        gender: "male",
        bloc: "vl_langzu",
        hp: 4,
        intro: "迟雨，和迟风一同行走于克拉边境的狼族青年，行事冷静，善于调度与周旋。<br>他更像一场绵密的雨：不急着正面压垮对手，而是先将“协”散入局中，再在关键时刻借势转移、接应与护持。对他而言，真正重要的不是一击定胜负，而是让每个人都站在自己该站的位置上。",
        prefix: "",
        skills: ["vl_ciyu_ss", "vl_ciyu_hq"],
        addition: [],
        pack: "Valyana",
        vp: 0,
        sort: "kela",
        rank: "legend",
    },
    vl_faers: {
        enable: true,
        name: "法斯",
        title: "永世恒常",
        gender: "female",
        bloc: "shen",
        hp: 4,
        intro: "法斯，或名法尔斯，兽人中最主要的神祇之一，代表了永恒与变换，是动与静的同一。法尔斯常以胡狼的形象示人，对任何物种都报以绝对的平衡。守护平衡是他的使命。但是在精灵族的预言集「瓦尔亚娜大百科」中其被预言是毁灭兽人王国的罪魁祸首。",
        prefix: "",
        skills: ["vl_faers_hc", "vl_faers_sb", "vl_faers_yl"],
        addition: ["zhu"],
        pack: "Valyana",
        vp: 0,
        sort: "shoushen",
        rank: "legend",
    },
    vl_yinhu: {
        enable: true,
        name: "寅虎",
        title: "祥瑞祝福",
        gender: "male",
        bloc: "shen",
        hp: 3,
        intro: "寅虎，色塔卡荒漠最受敬仰的神明，当地的人们认为他能够去除一切灾厄并带来降雨，因此每一年的「清雨节」当地的人们都会举行盛大的祭祀活动，来纪念这位神明。",
        prefix: "",
        skills: ["vl_yinhu_xr", "vl_yinhu_zd", "vl_yinhu_sp"],
        addition: [],
        pack: "Valyana",
        vp: 0,
        sort: "shoushen",
        rank: "legend",
    },
    vl_miya: {
        enable: true,
        name: "米亚",
        title: "连破剑圣",
        gender: "male",
        bloc: "vl_langzu",
        hp: 4,
        intro: "米亚，生于兽人王国「克拉」东部的小村落中。幼时便喜好剑术，随父亲学习。无意间得到「连破」与「两仪」两套剑法。成为远近闻名的剑术大师。「连破」剑法大成后，独自前往兽人王国「德恩」东部的兽人王国「奥格」历练。途中遇见科里科特，为其天赋所感。遂收其为徒，赠以「两仪」剑法。",
        prefix: "",
        skills: ["vl_miya_hz", "vl_miya_ks"],
        addition: [],
        pack: "Valyana",
        vp: 0,
        sort: "youdangzhe",
        rank: "legend",
    },
    vl_krikt: {
        enable: true,
        name: "科里克特",
        title: "两仪剑使",
        gender: "male",
        bloc: "vl_langzu",
        hp: 4,
        intro: "科里科特，「连破」剑法大师米亚之徒。修习其赠与的「两仪」剑法。其剑术诡谲多变，剑术有着极强的爆发性。其剑法之转换，时而如同狂风骤雨般快速无比，时而如同狂涛骇浪般凶猛无匹，时而如同清泉溪涧般缓慢温柔细腻，时而如同秋风扫落叶般冷酷无情。世人皆赞之，有诗云：“霍如羿射九日落，矫如群帝骖龙翔。来如雷霆收震怒，罢如江海凝清光。”",
        prefix: "",
        skills: ["vl_krikt_th", "vl_krikt_ly"],
        addition: [],
        pack: "Valyana",
        vp: 0,
        sort: "youdangzhe",
        rank: "legend",
    },
    vl_qima: {
        enable: true,
        name: "奇玛",
        title: "破月之心",
        gender: "male",
        bloc: "vl_langzu",
        hp: 3,
        intro: "奇玛，生活在沃尔夫东侧的索尔山脉附近。小时候，其父亲曾给予其一个由未知矿石制作的颜色吊坠，并言此物会在其遭遇危险时拯救其于水火。奇玛在一次前往深渊寻找拯救其父亲的草药：“忘忧草”时被深渊的魔物抓伤眼部，导致其视力丧失。",
        prefix: "",
        skills: ["vl_qima_jm", "vl_qima_dz"],
        addition: ["forbidai"],
        pack: "Valyana",
        vp: 0,
        sort: "youdangzhe",
        rank: "legend",
    },
    vl_akain: {
        enable: true,
        name: "阿卡因",
        title: "风云变幻",
        gender: "male",
        bloc: "vl_langzu",
        hp: 3,
        intro: "阿卡因，出生于克拉北境与旧军镇交界的狼族术士。当地常年被寒潮与地火夹击，部族为了生存频繁依附不同领主，阿卡因也因此自幼学会了在立场之间转换。他胸前佩戴的法轮原是北境祭司用来观测元素潮汐的仪器，后来被他改造成能够收束火焰与寒气的法球。<br>在一次边境冲突中，阿卡因所在的部族被两支军队同时征召。两边都要求他交出法轮作为军用术器，他却趁夜引动冰层与地火，让两支军队在裂开的冻土前同时停下。那以后，阿卡因离开北境，继续研究元素彼此转化的方式。他不轻易承诺忠诚，因为他见过太多旗帜在风雪中换了颜色。",
        prefix: "",
        skills: ["vl_akain_bx", "vl_akain_ys", "vl_akain_fy", "vl_akain_jh"],
        addition: ["doublegroup:wei:shu"],
        pack: "Valyana",
        vp: "1/3",
        sort: "vl_furry_migration",
        rank: "epic",
    },
    vl_alas: {
        enable: true,
        name: "奥拉斯",
        title: "破空断魂",
        gender: "male",
        bloc: "vl_quanzu",
        hp: 4,
        intro: "奥拉斯，出身于迦奈尔联邦南部的地下拳场，是犬族中少有的重拳手。少年时的奥拉斯原本只是拳场杂工，因替受伤的拳手上台，被迫与成名拳王交手。那一战中，他连续挨了七记重拳仍未倒下，最后用一记贴身直拳击碎了对方的护齿，也为自己赢下了第一副红色拳套。<br>离开拳场后，奥拉斯没有加入正规军，而是跟随商队和佣兵团穿行各地。他对规则的理解很简单：擂台上只要铃声没响，谁也不能说胜负已定；战场上只要敌人还握着武器，就必须把那份威胁彻底打掉。因此他总是逼近、压迫、连续出拳，直到对手连喘息的空隙都找不到。",
        prefix: "",
        skills: ["vl_olas_fh", "vl_olas_bx"],
        addition: [],
        pack: "Valyana",
        vp: 0,
        sort: "vl_furry_migration",
        rank: "common",
    },
    vl_berg: {
        enable: true,
        name: "伯格",
        title: "镜花水月",
        gender: "male",
        bloc: "vl_langzu",
        hp: 3,
        intro: "伯格，龙之谷外环月湖旁长大的狼族幻术师。月湖水面常年映着巨大的月影，湖底又埋有古龙遗留的魔晶，因此附近居民常能看见并不存在的人影与花火。伯格幼年时误入湖心禁地，醒来后便能把月光、水影和记忆碎片折成短暂的幻象。<br>成年后的伯格没有加入龙之谷的正规法师序列，而是独自记录月湖异象。他手中那枚紫色光球据说由湖底魔晶打磨而成，能够把即将发生的现实折射成另一种可能。伯格很少解释自己的术法，因为他知道，幻象一旦被说穿，就只剩下廉价的戏法。",
        prefix: "",
        skills: ["vl_berg_sy", "vl_berg_jh"],
        addition: [],
        pack: "Valyana",
        vp: 0,
        sort: "dragongu",
        rank: "epic",
    },
    vl_bladewolf: {
        enable: true,
        name: "刃狼",
        title: "机魂熔炉",
        gender: "male",
        bloc: "vl_jiqi",
        hp: 4,
        intro: "刃狼，是产于迦奈尔联邦的机器人，由于其驱动需要大量的电力，因此刃狼作为该型号唯一的机器人被装载了核动力反应堆。刃狼的生产目的是为了战争，因此其功能也被特化为战争相关，并卸除了情感模块。但是后来因一些机缘巧合，被西普感化并重新获得了情感，在其死后将其带回并改造为了机械生命。",
        prefix: "",
        skills: ["vl_bladewolf_qp", "vl_bladewolf_rh"],
        addition: ["forbidai"],
        pack: "Valyana",
        vp: 0,
        sort: "jixiezaowu",
        rank: "legend",
    },
    vl_sheep: {
        enable: true,
        name: "西普",
        title: "能机巧算",
        gender: "female",
        bloc: "vl_jiqi",
        hp: 3,
        intro: "西普，原生活于克拉，是出生于贫民窟的普通兽人；在哈拉尔国王上任前的那位国王——盖尔德鲁，是一位不折不扣的暴君，他欺压百姓并强迫贫民窟的人们前往战场。西普不幸被选中，后在战场上遇到了战争机器人——刃狼，经历一系列事件之后，西普成功使得刃狼获得了感情并相爱。后来再一次意外中，西普战死。刃狼将其带回并改造为机械生命。但是由于死去过久，其记忆没有被继承，现在将刃狼当作自己的哥哥。",
        prefix: "",
        skills: ["vl_sheep_jf", "vl_sheep_rh"],
        addition: [],
        pack: "Valyana",
        vp: 0,
        sort: "jixiezaowu",
        rank: "legend",
    },
    vl_horn: {
        enable: true,
        name: "霍恩",
        title: "恶灵推手",
        gender: "male",
        bloc: "vl_yangzu",
        hp: 3,
        intro: "霍恩，据传是来自深渊的恶魔，为了夺取米兰寺的珍贵宝物——豁免权杖，设计杀死了米兰寺的住持。霍恩不喜活物，他常常会放出致死的魔法，杀死周围的一切。",
        prefix: "",
        skills: ["vl_horn_ql", "vl_horn_ll"],
        addition: [],
        pack: "Valyana",
        vp: 0,
        sort: "milan",
        rank: "epic",
    },
    vl_jet: {
        enable: true,
        name: "杰特",
        title: "混乱之神",
        gender: "male",
        bloc: "shen",
        hp: 3,
        intro: "杰特，兽人诸神中少有的混乱神。有关他的记载极少，且互相矛盾：有的文书称他曾在王国初立时为诸部落传递火种，有的祭文却说他在同一日诱发了七场叛乱。神学者普遍认为，杰特并不掌管单纯的灾祸，而是掌管“秩序被打断后的可能性”。<br>他常以披着深色外衣、指间缠绕火光的狼族形象出现。每逢王权、军阵或仪式过于稳定时，杰特便会隐匿身份进入其中，轻轻拨动某个看似无关紧要的选择。有人因此得救，也有人因此毁灭。杰特从不解释自己的目的，只说若世界永远按一种方式运转，神明也会感到无聊。",
        prefix: "",
        skills: ["vl_jet_fy", "vl_jet_ww", "vl_jet_sl", "vl_jet_cl"],
        addition: ["hiddenSkill"],
        pack: "Valyana",
        vp: 0,
        sort: "shoushen",
        rank: "legend",
    },
    vl_kmjia: {
        enable: true,
        name: "卡米加",
        title: "教指人心",
        gender: "male",
        bloc: "vl_quanzu",
        hp: 3,
        intro: "卡米加，犬族出身的巡回教士，曾在克拉南境的教会学校任教。他年轻时并不以武力见长，却极擅长观察学生与信众的情绪变化，能够用几句话让争斗双方暂时放下武器。后来南境饥荒爆发，地方贵族强征粮食，卡米加带着学生护送难民离开，途中第一次将所有物资与行动计划交给一名年轻护卫执行。<br>那场逃亡让卡米加意识到，所谓领导并非永远站在最前面，而是在恰当时刻把路让给更适合行动的人。此后他不再固定任教，而是带着书箱在南境各村镇之间行走，替流亡者调解纠纷、安排去路。他记录不同人的选择与代价，也记录自己每一次因判断错误而付出的伤口。",
        prefix: "",
        skills: ["vl_kamijia_sx", "vl_kamijia_dr"],
        addition: ["zhu"],
        pack: "Valyana",
        vp: 0,
        sort: "vl_furry_migration",
        rank: "epic",
    },
    vl_knier: {
        enable: true,
        name: "科妮尔",
        title: "花非花，雾非雾",
        gender: "female",
        bloc: "vl_langzu",
        hp: 3,
        intro: "科妮尔，出生于万灵之森北侧的湖畔村落。村中每年春末都会出现覆盖湖面的白雾，雾中盛开的水花能够短暂吸收外来的魔力。科妮尔幼年时因体弱常被禁止外出，却在一次走失中独自穿过雾湖，带回了一枝不会枯萎的白花。自那以后，她便能把袭来的术式封进花雾之中。<br>成年后的科妮尔被龙之谷的学者邀请研究雾湖现象，但她并不适应学院生活，最终只留下几份笔记便离开。她更喜欢独自在湖边观察雾气涨落，把危险先藏进看不清的地方，再等它变成一朵安静的花。对科妮尔而言，花不是装饰，而是雾中最温柔也最危险的陷阱。",
        prefix: "",
        skills: ["vl_knier_yc", "vl_knier_wh", "vl_knier_hp"],
        addition: [],
        pack: "Valyana",
        vp: 0,
        sort: "vl_furry_migration",
        rank: "legend",
    },
    vl_lamost: {
        enable: true,
        name: "拉莫斯特",
        title: "犹记繁华",
        gender: "male",
        bloc: "vl_langzu",
        hp: 4,
        intro: "拉莫斯特，旧克拉贵族“拉莫斯特家”的末裔。盖尔德鲁统治后期，拉莫斯特家因拒绝为王室提供军费而被抄没，家族藏书与艺术品大多流入黑市。拉莫斯特本人侥幸逃离王城，只带走了一枚祖传的戒指和几页残缺账册。<br>流亡期间，他靠鉴定古物与整理失散文书谋生，也因此练就了从杂乱文卷中辨认可用线索的能力。后来他开始追查家族藏书的下落，逐渐走遍克拉各地旧书铺、黑市和废宅。拉莫斯特收集这些记录，不是为了复辟旧贵族，而是为了证明那些曾经繁华的名字并未完全消失。",
        prefix: "",
        skills: ["vl_lamost_zf"],
        addition: [],
        pack: "Valyana",
        vp: 0,
        sort: "vl_furry_migration",
        rank: "common",
    },
    vl_marxya: {
        enable: true,
        name: "马尔西亚",
        title: "谨小慎微",
        gender: "male",
        bloc: "vl_longzu",
        hp: 3,
        intro: "马尔西亚，龙之谷防卫队的斥候军官。龙族天生强大，许多年轻龙裔习惯以力量压制敌人，马尔西亚却恰好相反。他在第一次边境巡查中因冒进失去了整支小队，从此变得极端谨慎，凡事必先测距、留路、预藏退路。<br>他的作战方式源自龙之谷斥候使用的旧式战法：不与敌人正面交锋，而是让第一轮攻击落空，再趁对手露出破绽时回收战利品。马尔西亚身上总带着多枚护符和备用短刃，看似累赘，却都是他在某次死里逃生后留下的习惯。对他来说，谨慎不是怯懦，而是对死去队友最基本的尊重。",
        prefix: "",
        skills: ["vl_marcia_us", "vl_marcia_jz", "vl_marcia_ql"],
        addition: [],
        pack: "Valyana",
        vp: 0,
        sort: "dragongu",
        rank: "epic",
    },
    vl_ming: {
        enable: true,
        name: "鸣",
        title: "能言善辩",
        gender: "male",
        bloc: "vl_huzu",
        hp: 3,
        intro: "鸣，虎族书吏之子，幼年随父亲迁居克拉南部学城。与大多数虎族崇尚武力不同，鸣从小更喜欢背诵成语、诗句和古代判例。他曾因身形瘦小被同龄人嘲笑，却能在辩论课上连续接出数十个成语，让整间学堂哑口无言。<br>成年后，鸣成为巡回书记官，专门为不识字的村镇撰写诉状与契约。他相信语言并不比刀剑软弱，好的句子能够让人冷静，也能让敌人露出破绽。后来鸣在一次护送文书的途中遭遇盗匪，他一边吟诵诗句一边以短刃反击，第一次明白自己背下的文字也能成为护身的锋刃。",
        prefix: "",
        skills: ["vl_ming_yc", "vl_ming_yy"],
        addition: [],
        pack: "Valyana",
        vp: 0,
        sort: "vl_furry_migration",
        rank: "epic",
    },
    vl_mountainbear: {
        enable: true,
        name: "山熊",
        title: "力透千钧",
        gender: "male",
        bloc: "vl_xiongzu",
        hp: "3/3/4",
        intro: "&nbsp&nbsp&nbsp&nbsp山熊，原本是一只栖息在矮人之心洞穴周围的强大魔兽。它的存在一直是矮人部落的威胁，不断地对部落成员构成威胁。然而，山熊的命运在一次决定性的战斗中发生了巨变。在那场战斗中，山熊遭到了路西法的父亲的挑战。这场战斗激烈而残酷，但最终，路西法的父亲以出色的战斗技巧和坚韧不拔的意志，战胜了山熊。这场胜利被看作是路西法的父亲的一项英勇壮举，也标志着山熊的命运将发生改变。\n            <br>&nbsp&nbsp&nbsp&nbsp作为成年礼的礼物，路西法的父亲决定将山熊送给他的儿子。这个决定改变了山熊的生活轨迹，也让它与路西法的命运紧密交织在一起。在路西法的成年礼上，他通过强大的战斗技巧获得了山熊的认可。这次战斗是他们之间的一场考验，也是他们友谊的开始。山熊看到了路西法的坚决和勇气，开始信任他，并与他签订了一份特殊的契约。\n            <br>&nbsp&nbsp&nbsp&nbsp多年来，山熊和路西法成为了一对默契无间的伙伴。他们已经可以通过思想交流，将彼此的意愿传达得非常清晰，这是一种深厚的信任和默契的体现。他们的生命似乎已经通过契约而紧密连接，无论在战斗还是在日常生活中，他们总是互相扶持，守护着彼此。山熊生性暴戾，在没有兽语者控制的情况下。它可能会表现出随意伤人的行为，因此，只有路西法的存在和指导才能确保山熊不会陷入暴怒之中，保持友善和控制。\n            <br>&nbsp&nbsp&nbsp&nbsp山熊和路西法的故事是一段关于友情和信任的传奇。他们的契约将继续引领他们前行，不仅是伙伴，也是彼此的支持和保护者。这个不寻常的友情，已经成为了他们生命中最宝贵的财富。",
        prefix: "",
        skills: ["vl_mountainbear_xs", "vl_mountainbear_xj"],
        addition: ["unseen"],
        pack: "Valyana",
        vp: 0,
        sort: "vl_furry_migration",
        rank: "common",
    },
    vl_nore: {
        enable: true,
        name: "诺尔",
        title: "观微洞察",
        gender: "male",
        bloc: "vl_langzu",
        hp: 4,
        intro: "诺尔，出生于克拉西部矿镇的狼族调查员。矿镇地下遍布废弃坑道，当地人称其为“洞中”，认为那里会吞掉声音、火光和人的来路。诺尔少年时曾在矿难中被困三日，获救后便对黑暗、回声和无来源的震动异常敏感。<br>后来诺尔加入巡查署，专门调查那些无法确定凶手的案件。他常说，真正危险的伤害并不一定有清晰的来源，有时一条被忽略的坑道、一盏被移动过的灯，就足以说明整件事的走向。诺尔的调查方式冷静而缓慢，却总能从看似空洞的现场中挖出藏在渊薮里的真相。",
        prefix: "",
        skills: ["vl_nore_dz", "vl_nore_ys"],
        addition: [],
        pack: "Valyana",
        vp: 0,
        sort: "vl_furry_migration",
        rank: "rare",
    },
    vl_tiers: {
        enable: true,
        name: "缇尔斯",
        title: "战场玫瑰",
        gender: "female",
        bloc: "vl_tuzu",
        hp: 3,
        intro: "缇尔斯，生活在迦奈尔联邦，由于联邦周围大量禁魔矿石的影响，此处无法施展魔法，故此处的主要研究方向为科技。缇尔斯幼时丧父，与母亲相依为命，后进入联邦军队，在服役5年后因在与矮人的战争中负伤，回到家乡科马修养。",
        prefix: "",
        skills: ["vl_tiers_qp", "vl_tiers_kh"],
        addition: [],
        pack: "Valyana",
        vp: 0,
        sort: "jianaier",
        rank: "rare",
    },
    vl_verb: {
        enable: true,
        name: "韦贝尔",
        title: "绝处逢生",
        gender: "male",
        bloc: "vl_shuzu",
        hp: 3,
        intro: "韦贝尔，鼠族行商与情报贩子，常年往返于克拉、迦奈尔联邦与人鱼之海之间。他身形不高，胆子却很大，最擅长在强者谈判时挤进一句话，再把所有人的注意力引向自己想要的方向。<br>韦贝尔曾在一次黑市交易中被双方同时追杀，身上只剩一只货箱和几枚残币。为了活命，他当着所有追兵的面逐个点破他们私藏的秘密，逼迫众人先交出筹码再继续谈判。那次经历让他养成了先让每个人表态的习惯，再从别人暴露出的欲望里寻找生路。韦贝尔不认为自己幸运，他只是比大多数人更熟悉绝境的价格。",
        prefix: "",
        skills: ["vl_verb_zy", "vl_verb_fs"],
        addition: [],
        pack: "Valyana",
        vp: 0,
        sort: "youdangzhe",
        rank: "epic",
    },
    vl_wes: {
        enable: true,
        name: "维斯",
        title: "同生共死",
        gender: "male",
        bloc: "vl_longzu",
        hp: 3,
        intro: "维斯，生活在克拉北部的小镇米拉亚纳行省，毗邻吸血鬼禁区。由于附近丰富的魔力资源影响，维斯从小便表现出了强烈的魔法亲和性，其能力能够转移其他人受到的伤害。由于其能力的特殊性，自小其就被送往当地教会培养。",
        prefix: "",
        skills: ["vl_wes_ts", "vl_wes_gs", "vl_wes_lt"],
        addition: [],
        pack: "Valyana",
        vp: 0,
        sort: "kela",
        rank: "legend",
    },
    vl_west: {
        enable: true,
        name: "韦斯特",
        title: "仁心医者",
        gender: "male",
        bloc: "vl_quanzu",
        hp: 3,
        intro: "韦斯特，犬族药剂师，早年就读于迦奈尔联邦的民间医学院。因无法使用魔法，他转而研究草药、炼金溶剂和战场急救术；随身携带的粉色药剂，是他反复改良出的复苏药水，能够在短时间内稳定濒死者的生命体征。<br>矮人之心争夺战期间，韦斯特随医疗队进入前线，亲眼见到许多士兵因诅咒侵蚀、失血过多或护具崩毁而死。战争结束后，他离开联邦军医系统，开始独自旅行，为贫民窟和边境村落提供治疗。韦斯特相信医者的职责不仅是缝合伤口，更是把一个人从混乱与痛苦中重新扶回活人的道路。",
        prefix: "",
        skills: ["vl_west_pz", "vl_west_sx", "vl_west_jh"],
        addition: [],
        pack: "Valyana",
        vp: 0,
        sort: "vl_furry_migration",
        rank: "rare",
    },
    vl_wind: {
        enable: true,
        name: "温迪",
        title: "且听风吟",
        gender: "male",
        bloc: "vl_langzu",
        hp: 4,
        intro: "温迪，生活在人鱼之海沿岸的狼族旗手。少年时他常在港口帮船员收帆，能够通过旗帜、浪花和风声判断天气变化。后来一位流浪法师发现温迪对气流极为敏感，教他把风向、对象与结果拆成三枚独立的术式标记。<br>温迪并不擅长猛烈的攻击，他的能力更像调风：有时将顺风引向自己，有时把逆风推给旁人，有时在启程前改变局面，有时又等到一日将尽才让风落下。许多船员相信，只要温迪愿意在出航前听一听海上的风，船队就能避开最坏的风暴。",
        prefix: "",
        skills: ["vl_wind_fy"],
        addition: [],
        pack: "Valyana",
        vp: 0,
        sort: "vl_furry_migration",
        rank: "rare",
    },
    vl_yas_klin: {
        enable: true,
        name: "亚瑟",
        title: "祭天请神",
        gender: "male",
        bloc: "shen",
        hp: 4,
        intro: "亚瑟，旧祭司家族“克林”最后的继承人。克林家族原本侍奉诸神中的恐惧与契约之神，擅长通过献祭换取短暂庇护。新王朝建立后，这类血祭仪式被严厉禁止，亚瑟的族人陆续流亡，只留下他继续守着废弃祭坛。<br>亚瑟并不认为祭牲必然代表残酷。在他看来，真正的祭祀是把代价清楚地摆出来，让神明、施术者和受益者都无法逃避交换的结果。他在一场失控仪式中活了下来，手上残留的血契也从此与恐惧相连。若有人杀死亚瑟，契约会立刻反噬凶手，这也是许多猎神者至今不愿靠近他的原因。",
        prefix: "",
        skills: ["vl_yas_klin_bj", "vl_yas_klin_js"],
        addition: [],
        pack: "Valyana",
        vp: 0,
        sort: "vl_furry_migration",
        rank: "legend",
    },
    vl_youying: {
        enable: true,
        name: "游影",
        title: "挥剑如歌",
        gender: "male",
        bloc: "vl_langzu",
        hp: 4,
        intro: "游影，出生于万灵之森边陲的小镇“米埃”。自幼跟随父亲修行剑法，后出门远行前往米兰寺求学，经介绍后跟随米亚学习剑术，但最后因理念不同而分道扬镳。游影的剑法诡谲，翩若惊鸿，宛若游龙。剑法精妙，如诗般令人赏心悦目。",
        prefix: "",
        skills: ["vl_youying_jg", "vl_youying_qy"],
        addition: [],
        pack: "Valyana",
        vp: 0,
        sort: "youdangzhe",
        rank: "epic",
    },
    vl_zeron: {
        enable: true,
        name: "泽罗恩",
        title: "以牙还牙",
        gender: "male",
        bloc: "vl_haizu",
        hp: 4,
        intro: "泽罗恩，人鱼之海著名“胡子海盗团”的现任船长，他作为一位船长可谓是尽职尽责，或者对他来说每一位船员都是他的朋友。泽罗恩小时候便因父亲的家庭暴力失去了母亲，父亲整日酗酒对他不管不顾，甚至拳脚相加。这也导致泽罗恩没法上学而早早成为了一名海盗。泽罗恩成为海盗是因为他亲自手刃了自己的父亲被通缉，只能落草为寇。他信奉的信条便是“以牙还牙，以眼还眼”，如果你是他的朋友，他会对你百般纵容，如果你是他的敌人，他则会负责让你去见神明。",
        prefix: "",
        skills: ["vl_zeron_sx"],
        addition: [],
        pack: "Valyana",
        vp: 0,
        sort: "renyu",
        rank: "common",
    },
    vl_zeta: {
        enable: true,
        name: "泽塔",
        title: "固铸何归？",
        gender: "male",
        bloc: "vl_longzu",
        hp: 4,
        intro: "泽塔，龙之谷外城的锻造师，拥有少见的绿鳞龙族血统。他年轻时曾进入矮人之心学习金属锻造，因体格高大、力气惊人，被矮人师傅要求背负巨锤和铁砧完成整整三年的基础训练。泽塔肩上的小鸟名叫“归巢”，是他在矿洞坍塌后救下的信鸟，也成了他判断回程方向的伙伴。<br>泽塔相信任何材料都不该只被使用一次。废铁、断刃、破甲在他眼中都像散落的矿石，只要分类、回炉、重新分配，仍能铸成新的用途。后来他回到龙之谷开设工坊，专门回收战后遗留的兵刃与护具；许多被视为无法修复的残件，都会在他的炉火里获得第二次形状。",
        prefix: "",
        skills: ["vl_zeta_gz", "vl_zeta_fg"],
        addition: [],
        pack: "Valyana",
        vp: 0,
        sort: "dragongu",
        rank: "epic",
    },
    vl_zhan: {
        enable: true,
        name: "展",
        title: "束缚之厄",
        gender: "male",
        bloc: "vl_maozu",
        hp: 3,
        intro: "展，猫族少年，出身不详。关于他的最早记录来自克拉北部一处废弃实验室，搜救者在那里发现了断裂的铁链、刻满禁制的地面，以及一份被烧毁大半的实验日志。日志中将展称作“束缚样本”，认为他的体内能够在受伤后自动修复，并把伤害转化为更强的适应能力。<br>展被救出时已经无法正常使用多数后天训练出的技艺，只有束缚本身与解放冲动留在身体里。平日的展沉默、警惕，身上仍保留着锁链与拘束具留下的痕迹；一旦承受的痛苦超过极限，那些禁制便会崩断，并向周围释放名为「灾厄」的残留力量。此后他一直避开人群流浪，不是因为不懂得求助，而是害怕自己再次成为别人眼中的实验材料。",
        prefix: "",
        skills: ["vl_zhan_sf", "vl_zhan_jf"],
        addition: [],
        pack: "Valyana",
        vp: 0,
        sort: "vl_furry_migration",
        rank: "legend",
    },
    vl_kulun_light: {
        enable: true,
        name: "库伦·光明",
        title: "",
        gender: "male",
        bloc: "vl_langzu",
        hp: 1,
        intro: "",
        prefix: "",
        skills: ["vl_kulun_light_sg", "vl_kulun_light_yb"],
        addition: ['unseen'],
        pack: "Valyana",
        vp: 0,
        sort: "vl_furry_migration",
        rank: "epic",
    },
    vl_kulun_dark: {
        enable: true,
        name: "库伦·黑暗",
        title: "",
        gender: "male",
        bloc: "vl_langzu",
        hp: 1,
        intro: "",
        prefix: "",
        skills: ["vl_kulun_dark_as", "vl_kulun_dark_yb"],
        addition: ['unseen'],
        pack: "Valyana",
        vp: 0,
        sort: "vl_furry_migration",
        rank: "epic",
    },
    vl_kulun_wind: {
        enable: true,
        name: "库伦·飓风",
        title: "",
        gender: "male",
        bloc: "vl_langzu",
        hp: 1,
        intro: "",
        prefix: "",
        skills: ["vl_kulun_wind_wx", "vl_kulun_wind_cm"],
        addition: ['unseen'],
        pack: "Valyana",
        vp: 0,
        sort: "vl_furry_migration",
        rank: "epic",
    },
    vl_kulun_fire: {
        enable: true,
        name: "库伦·火焰",
        title: "",
        gender: "male",
        bloc: "vl_langzu",
        hp: 1,
        intro: "",
        prefix: "",
        skills: ["vl_kulun_fire_ly", "vl_kulun_fire_fz"],
        addition: ['unseen'],
        pack: "Valyana",
        vp: 0,
        sort: "vl_furry_migration",
        rank: "epic",
    },
    vl_kulun_water: {
        enable: true,
        name: "库伦·潮汐",
        title: "",
        gender: "male",
        bloc: "vl_langzu",
        hp: 1,
        intro: "",
        prefix: "",
        skills: ["vl_kulun_water_sy", "vl_kulun_water_jy"],
        addition: ['unseen'],
        pack: "Valyana",
        vp: 0,
        sort: "vl_furry_migration",
        rank: "epic",
    },
    vl_kulun_ice: {
        enable: true,
        name: "库伦·寒冰",
        title: "",
        gender: "male",
        bloc: "vl_langzu",
        hp: 1,
        intro: "",
        prefix: "",
        skills: ["vl_kulun_ice_hs", "vl_kulun_ice_dj"],
        addition: ['unseen'],
        pack: "Valyana",
        vp: 0,
        sort: "vl_furry_migration",
        rank: "epic",
    },
    vl_kulun_metal: {
        enable: true,
        name: "库伦·金属",
        title: "",
        gender: "male",
        bloc: "vl_langzu",
        hp: 1,
        intro: "",
        prefix: "",
        skills: ["vl_kulun_metal_zl", "vl_kulun_metal_rh"],
        addition: ['unseen'],
        pack: "Valyana",
        vp: 0,
        sort: "vl_furry_migration",
        rank: "epic",
    },
    vl_kulun_nature: {
        enable: true,
        name: "库伦·自然",
        title: "",
        gender: "male",
        bloc: "vl_langzu",
        hp: 1,
        intro: "",
        prefix: "",
        skills: ["vl_kulun_nature_hc", "vl_kulun_nature_tw"],
        addition: ['unseen'],
        pack: "Valyana",
        vp: 0,
        sort: "vl_furry_migration",
        rank: "epic",
    },
    vl_kulun_dirt: {
        enable: true,
        name: "库伦·大地",
        title: "",
        gender: "male",
        bloc: "vl_langzu",
        hp: 1,
        intro: "",
        prefix: "",
        skills: ["vl_kulun_dirt_zw", "vl_kulun_dirt_zj"],
        addition: ['unseen'],
        pack: "Valyana",
        vp: 0,
        sort: "vl_furry_migration",
        rank: "epic",
    },
    vl_kulun_thunder: {
        enable: true,
        name: "库伦·雷电",
        title: "",
        gender: "male",
        bloc: "vl_langzu",
        hp: 1,
        intro: "",
        prefix: "",
        skills: ["vl_kulun_thunder_yl", "vl_kulun_thunder_dl"],
        addition: ['unseen'],
        pack: "Valyana",
        vp: 0,
        sort: "vl_furry_migration",
        rank: "epic",
    },
    vl_kulun: {
        enable: true,
        name: "库伦",
        title: "元素引导者",
        gender: "male",
        bloc: "vl_langzu",
        hp: 1,
        intro: "&nbsp&nbsp&nbsp&nbsp库伦，出生于克拉王国，具有卓越的魔法天赋。在魔法学院的学习年月里，库伦积累了深厚的魔法知识，并发明了一根号称“扭称”的特殊法杖，能够将两种元素力量注入其中并维持其平衡。\n            <br>&nbsp&nbsp&nbsp&nbsp后来，他偶然发现了一个神秘的泉眼，这个泉眼融合了各种元素的能量，释放着无尽的魔法力量。库伦决定将泉眼视为自己的研究对象，但随着时间的推移，他渐渐被泉眼中的力量所吸引，着魔般地渴望着占有它。他利用“扭称”进行危险的实验，试图掌握泉眼的能量。\n            <br>&nbsp&nbsp&nbsp&nbsp库伦不知道的是，当所有元素被禁锢于同一容器时，它们会相互碰撞和交织，引发了强烈的爆炸。这场爆炸不仅波及了数千人，炸毁了整个魔法师塔，还导致了一场名为“魔力大崩溃”的魔法浩劫，世界的魔力等级骤降，所有人都无法再从世界的魔网中吸取超过十阶的能量。\n            <br>&nbsp&nbsp&nbsp&nbsp魔法，曾经是克拉文明的核心，从此陷入了低谷。而库伦的研究和冒险，无论是对于魔法学的贡献还是对于后世的警示，都将被永远地铭记在瓦尔亚那的历史中。",
        prefix: "",
        skills: ["vl_kulun_gz", "vl_kulun_fs", "vl_kulun_zn", "vl_kulun_skillfilter"],
        addition: [],
        pack: "Valyana",
        vp: 0,
        sort: "kela",
        rank: "epic",
    },
}
