export const character = {
    vl_templete: {
        enable: false,
        name: '🐺名字',
        title: '头衔',
        gender: 'male',
        bloc: '势力',
        hp: 3,
        intro: `简要介绍`,
        drawer: "钫酸酱",
        coder: "钫酸酱",
        designer: "钫酸酱",
        writer: "钫酸酱",
        prefix: "🐺",
        skills: [],
        addition: [],
        pack: '武将包',
        vp: 0,
        sort: '分类',
        rank: '评级'
    },
    vl_fangsuan: {
        enable: true,
        name: 'SP钫酸',
        title: '无畏暴君',
        gender: 'male',
        bloc: 'vl_hulizu',
        hp: 3,
        vp: 3,
        intro: `
钫酸出生于瓦尔亚纳大陆北部的一个小公国。他的父亲是那片领地的公爵，母亲来自一个没落的精灵家族。他幼年时便显露出异于常人的天赋——左眼能看穿谎言的纹理，右眼能捕捉魔法的流动。十岁那年，他当着宫廷法师的面，用目光让一头狂暴的狮鹫安静下来，随后命令它撞死在城墙上。这件事被记录为他的第一次“催眠”。公爵没有感到欣慰，而是恐惧。他试图将儿子送往边境的修道院，但车队在途中遭遇山匪，随行的护卫全部死亡，钫酸独自返回城堡，身后跟着那伙山匪的头颅。公爵当晚暴毙，死因不明。十三岁的钫酸继承了爵位，随后用三年时间吞并了周边六个领地。
<br>他的扩张从未停止。他没有盟友，只有暂时未被征服的敌人。他使用军队、魔法、暗杀，也使用他自己的眼睛。只要与他对视，对方就无法拒绝他的命令。这种能力让他绕过所有谈判桌，直接抵达结果。二十岁时，他已经控制了大陆北部三分之一的土地。他继续向南推进，遭遇了精灵联军、矮人王国和人类帝国的联合抵抗。这场战争持续了七年。钫酸在战争末期独自进入精灵的圣殿，与当时掌管大陆神力的十二位神祇对峙。他用了三天时间，逐一撕碎了那些神的化身。神祇陨落时，整个大陆的地脉都发生了震颤。第四天，他走出圣殿，宣布自己为唯一的王。
<br>统一后的第八年，钫酸颁布了“犬令”。所有臣民，不论贵族或平民，都被要求佩戴项圈，行为规范由皇家法典统一规定。他废除了原有的法律体系，将所有权力收归王座。反抗者被投入地牢，或直接由他的骑士处决。他的四位骑士——望朔、小c、阿然、阿早——各自掌管审判、传讯、死亡与治愈，形成一套完整的统治架构。第五位骑士莱恩曾是他最信任的将领，但在一场由钫酸亲自设计的构陷中，莱恩被迫杀死自己的挚友，精神崩溃，被囚禁于王宫地底深处。钫酸保留了莱恩的骑士头衔，但不再允许他踏出牢笼。
<br>钫酸的性格中有一种冷静的残酷。他从不因愤怒而杀人，也不因快感而折磨。他的行动基于效率和必要性。当他认为某件事没有价值时，他会直接终结它。他很少提高音量，眼神的变化足以传递指令。他的臣民学会在他注视时低头，因为直视他的双眼意味着失去自我。他很少使用催眠能力，因为他觉得让一个人清醒地服从更有趣。
<br>统治稳定后，钫酸开始感到一种持续的乏味。战争、征服、立法，这些事都结束了。他拥有一切，但一切都在预期之内。这种状态持续了数月，直到一位自称泡芙的术士从王宫的穹顶降落。泡芙带来了一套名为“挑担的游戏”的规则，用机关与谜题制造困境和抉择。钫酸接受了这个游戏，因为游戏本身不可预测，而不可预测是他唯一尚未体验的事物。他将游戏的执行权交给旁人，自己作为观察者坐在王座上。游戏开始后，他的时间才重新流动起来。他不会亲自裁定每一道规则，但他会介入游戏变得乏味的时刻——以他自己的方式。
<br>他被称为“阴鸷神王”。这个称号源于他对神祇的屠杀，也源于他那种深藏不露的、近乎残酷的冷静。他的额头那枚红色印记，是他在撕碎最后一位神祇时，对方临死前烙下的诅咒烙印。神祇说，这印记会让他永远记着“被注视”的滋味。钫酸没有去除它，因为他觉得这印记让他看起来更威严。他是瓦尔亚纳唯一的王，也是这片大陆最后的神。`,
        drawer: "钫酸酱",
        coder: "钫酸酱",
        designer: "钫酸酱",
        writer: "钫酸酱",
        prefix: "SP",
        skills: ['vl_fangsuan_ximing', 'vl_fangsun_mishe', 'vl_fangsuan_kuangluan'],
        addition: ['zhu'],
        pack: 'Valyana',
        sort: 'vl_tiaodan',
        rank: 'legend'
    },
    vl_wangshuo: {
        enable: true,
        name: 'SP望朔',
        title: '守护之骑',
        gender: 'male',
        bloc: 'vl_shizu',
        hp: '3/4',
        intro: `
望朔是钫酸座下的第一位骑士，掌管审判。他是狮子兽人，头顶一对白色龙角，身上常年带着竹子的清淡气息。他的铠甲为白色，披挂为绿色，手持一柄被称为“圣剑”的长剑。这柄剑并不以锋利著称，而是能感应谎言与罪责，在审判时显现光芒。望朔的形象通常被描述为正义与光明的化身，他在公开场合的行为也符合这一描述——他主持法庭，裁决争端，从不徇私。
<br>他与钫酸签订了永世不得背叛的契约。这份契约并非出于恐惧或利益，而是基于他对秩序的认同。望朔认为，钫酸虽然手段残酷，但建立了大陆千年以来唯一统一的法度。他忠于钫酸，忠于王座，也忠于自己内心对“审判”的定义。他会在公开场合严格执行钫酸的命令，但在私下场合，他有时会延长审问的时间，或允许犯人申诉。这种行为并未违反契约，钫酸也从未过问。
<br>望朔的性格中有一种近乎固执的正直。他相信规则本身的意义，而非规则制定者的意志。如果钫酸的命令明显违背他认定的法理，他会先执行，然后请求复议。钫酸偶尔会驳回他的请求，但多数时候会调整指令。两人之间形成了一种微妙的制衡——望朔是唯一一个能在王座前提出异议而不被惩罚的骑士。其他骑士对此心知肚明，但从未有人点破。
<br>他的龙角是幼年时被一头白龙抚养留下的痕迹。那头龙在他成年时死去，将角留给了他。望朔从不谈论这件事，也不允许其他人提及。他将那段过往锁在记忆深处，像对待一道陈年旧伤一样，不触碰，不展示。`,
        drawer: "钫酸酱",
        coder: "钫酸酱",
        designer: "钫酸酱",
        writer: "钫酸酱",
        prefix: "SP",
        skills: ['vl_wangshuo_shouwang', 'vl_wangshuo_maofang'],
        addition: [],
        pack: 'Valyana',
        sort: 'vl_tiaodan',
        rank: 'epic'
    },
    vl_chen: {
        enable: true,
        name: "辰",
        title: "裂羽穿云",
        gender: "male",
        bloc: "vl_langzu",
        hp: 3,
        intro: "辰，常年游走于边地与战场之间的狼族弓手。他沉默寡言，却总能在最合适的距离射出最致命的一箭。<br>据说辰对武器与阵势有着异于常人的敏锐直觉，凡是被他盯上的目标，往往还没看清来路，便已先失了先机。对他而言，战斗不是喧嚣的拼杀，而是一次次精准的落点与时机的压制。",
        drawer: "钫酸酱",
        coder: "钫酸酱",
        designer: "钫酸酱",
        writer: "钫酸酱",
        prefix: "",
        skills: ["vl_chen_ly", "vl_chen_jx", "vl_chen_lz"],
        addition: [],
        pack: "Valyana",
        vp: 0,
        sort: "vl_tiaodan",
        rank: "epic",
    },
    vl_buline: {
        enable: true,
        name: "布莱恩",
        title: "邪恶法师",
        gender: "male",
        bloc: "vl_maozu",
        hp: 4,
        intro: "布莱恩是来自地狱的无上法术的咏唱者（自称），他做过的坏事数不胜数，包括但不限于：赶走偷吃鸡的黄鼠狼，杀死袭击村民的强盗，强迫受保护费的官兵学狗叫之类，因此其深受百姓憎恶（自称）。他致力于成为整个兽人王国最邪恶的黑魔法师，并为此努力着。《瓦尔亚那百科》中曾预言布莱恩有着黑暗生物的血统与两幅面孔，但似乎其本身并不知情。",
        drawer: "钫酸酱",
        coder: "钫酸酱",
        designer: "钫酸酱",
        writer: "钫酸酱",
        prefix: "",
        skills: ["vl_buline_qm", "vl_buline_yt"],
        addition: [],
        pack: "Valyana",
        vp: 0,
        sort: "wanling",
        rank: "junk",
    },
    vl_sisk: {
        enable: true,
        name: "西斯科",
        title: "嗜血狂徒",
        gender: "male",
        bloc: "vl_huzu",
        hp: "4/5",
        intro: "西斯科，罕见的狮兽人与吸血鬼的后代。拥有极其强力的身体素质与高超的种族天赋。后来被科亚所救，加入了「流亡者」雇佣兵团。其对血液极为敏感，些许的血腥味也会导致其进入狂暴。",
        drawer: "钫酸酱",
        coder: "钫酸酱",
        designer: "fox⑧",
        writer: "钫酸酱",
        prefix: "",
        skills: ["vl_sisk_yx", "vl_sisk_wg", "vl_sisk_jx"],
        addition: [],
        pack: "Valyana",
        vp: "2/5",
        sort: "yongbing",
        rank: "epic",
    },
    vl_aerte: {
        enable: true,
        name: "阿尔特",
        title: "缴械武解",
        gender: "male",
        bloc: "vl_langzu",
        hp: 4,
        intro: "阿尔特，出身于克拉北境的狼族骑士团。他身披白甲，常以巨剑立于阵前，却并不以杀戮为荣。北境旧俗中，决斗的胜负往往在第一击前便已决定——谁能先夺下对方的武器，谁便取得审判的权力。阿尔特正是在这种严苛训练中成长起来的骑士。<br>他曾在边境战争中独自拦下一支掠夺队，没有斩下任何一人的头颅，只是逐一卸去他们手中的刀剑，再将缴获的武器分给身后的民兵。自那以后，人们开始称他为“缴械武解”。阿尔特相信武器本身没有善恶，真正需要被制止的是握住武器的人。因此，他常常夺下敌人的杀意，再把新的力量交到更值得信任的人手中。",
        drawer: "钫酸酱",
        coder: "钫酸酱",
        designer: "钫酸酱",
        writer: "钫酸酱",
        prefix: "",
        skills: ["vl_aerte_jw"],
        addition: [],
        pack: "Valyana",
        vp: 0,
        sort: "kela",
        rank: "epic",
    },
    vl_hars: {
        enable: true,
        name: "哈尔斯",
        title: "全知之神",
        gender: "male",
        bloc: "shen",
        hp: 4,
        intro: "哈尔斯，兽人的智慧之神。其拥有惑人心魄的能力。根据矮人族与部分兽人族内部记录。哈尔斯能够直接降临到任何一人身上，据此观察世界。而被降临的人则被称为「神降者」。由于任何人都有可能成为「神降者」。因此，哈尔斯的眼线遍布整个大陆，而其本人也被称为「全知之神」。",
        drawer: "钫酸酱",
        coder: "钫酸酱",
        designer: "钫酸酱",
        writer: "钫酸酱",
        prefix: "",
        skills: ["vl_hars_sj", "vl_hars_hr"],
        addition: [],
        pack: "Valyana",
        vp: 0,
        sort: "shoushen",
        rank: "rare",
    },
    vl_yada: {
        enable: true,
        name: "亚达",
        title: "百变千面",
        gender: "male",
        bloc: "vl_huzu",
        hp: 4,
        intro: "亚达，暗影刺杀队的化妆师，在刺杀行动中，为了避免被其他人发现，如何伪装自己就是小队最大的难题。而亚达他凭着一手出人意料的易容技巧得到了队长斯克瑞的青睐，并在斯克瑞刺杀国王的那次行动中提供了伪装。",
        drawer: "钫酸酱",
        coder: "钫酸酱",
        designer: "钫酸酱",
        writer: "钫酸酱",
        prefix: "",
        skills: ["vl_yada_yl", "vl_yada_yy"],
        addition: [],
        pack: "Valyana",
        vp: 0,
        sort: "franying",
        rank: "rare",
    },
    vl_hundun: {
        enable: true,
        name: "混沌",
        title: "死亡使者",
        gender: "male",
        bloc: "shen",
        hp: 4,
        intro: "混沌，虽然他的知名度不如尧和洛一般，但是他确实是瓦尔亚那大陆上极为重要的神明之一。在尧和洛将灵魂拘回冥界后，混沌则会根据他们生前的事迹裁决是否对他们执行惩罚或奖励。混沌手中的双镰名为死魂幽镰，可以无视物理法则直接对灵体产生伤害。",
        drawer: "钫酸酱",
        coder: "钫酸酱",
        designer: "钫酸酱",
        writer: "钫酸酱",
        prefix: "",
        skills: ["vl_hundun_sy", "vl_hundun_sl", "vl_hundun_sp"],
        addition: [],
        pack: "Valyana",
        vp: 0,
        sort: "shoushen",
        rank: "legend",
    },
    vl_xiaomo: {
        enable: true,
        name: "泡芙",
        title: "破击无声",
        gender: "male",
        bloc: "vl_maozu",
        hp: 3,
        intro: "泡芙，是一名行踪不定的猫族旅者，也是将“挑担的游戏”带到钫酸王座前的人。与他轻巧的外表不同，泡芙对危险有着近乎本能的判断。他很少正面承受攻击，总能在刀锋落下前错开半步，让伤害像掠过水面的风一样消散。<br>据说泡芙曾在某个异界战场中学习过把护甲化作冲击力的技巧。他平日看似懒散，真正出手时却极快，能够将积蓄的防护一次性压进短促的突袭之中，因此得名“闪击”。他不喜欢解释自己的来历，只说自己是在寻找一场足够有趣、足够危险，也足够不讲道理的游戏。",
        drawer: "钫酸酱",
        coder: "钫酸酱",
        designer: "钫酸酱",
        writer: "钫酸酱",
        skills: ["vl_xiaomo_sj", "vl_xiaomo_ld"],
        addition: [],
        pack: "Valyana",
        vp: 0,
        sort: "kela",
        rank: "legend",
    },
    vl_froh: {
        enable: true,
        name: "钫",
        title: "命运书写者",
        gender: "male",
        bloc: "shen",
        hp: 3,
        intro: "钫，传说中执掌一切生物命运的神祇，在《瓦尔亚那百科》中记载，他是现存的唯一的「自然神」。有传言称，《瓦尔亚那百科》便是在他的授意下委托精灵族长者写成。作为神族的他，常常以蒙眼的姿态出现并为众人降下祝福。目前还没有人看见过他睁眼的样子，据说当他睁眼，便是昭告毁灭的来临。",
        drawer: "钫酸酱",
        coder: "钫酸酱",
        designer: "钫酸酱",
        writer: "钫酸酱",
        prefix: "",
        skills: ["vl_froh_sz", "vl_froh_qn", "vl_froh_sn"],
        addition: ["zhu"],
        pack: "Valyana",
        vp: 0,
        sort: "shoushen",
        rank: "legend",
    },
    vl_ala: {
        enable: true,
        name: "阿拉安",
        title: "睚眦必报",
        gender: "male",
        bloc: "vl_niuzu",
        hp: 4,
        intro: "阿拉安，米兰寺的大弟子，在其二十四岁时出师，后四处游历。目前正在矮人之心洞穴附近修行。奥拉类似于林和炎的哥哥的存在，从小对他们多有照顾。",
        drawer: "钫酸酱",
        coder: "钫酸酱",
        designer: "钫酸酱",
        writer: "钫酸酱",
        prefix: "",
        skills: ["vl_ala_dy", "vl_ala_gm"],
        addition: [],
        pack: "Valyana",
        vp: 0,
        sort: "milan",
        rank: "epic",
    },
    vl_delagu: {
        enable: true,
        name: "德古拉",
        title: "鲜血祭祀",
        gender: "male",
        bloc: "vl_guaiwu",
        hp: "2/4",
        intro: "德古拉，出生于克拉王国东南侧的禁忌之地——被人们称为“深渊”的无人区。他是深渊的产物，属于血族，身负着长生不老的神秘特性，也有着对血液的病态执着。<br>如同深渊中潜伏的巨鲨，德古拉散发着一股无法忽视的阴森氛围。他对血液的执念像是无尽的深海，吞噬着他的理智。即便微不足道的血腥气息，也足以将他引入狂热的疯狂状态。<br>德古拉的存在就如同深渊的黑暗，克拉的人们对他心生畏惧。他的身影如鲨鱼般游走在深渊的边缘，时刻准备着向那些无知者展开致命的袭击。血液是他的媒介，也是他无法自拔的诱因，将他引向一条充满危险和疯狂的不归之路。正如那深渊入口所镌刻的石碑所言：<br>克拉之地，深渊之间，<br>伺藏恶鬼，诱人缠绵。<br>身躯长生，鲜血沐浴，<br>教诲谨记，勿贪而妄言。<br><br>魔鬼常潜，深渊长眠，<br>恶鬼既出，血光乍现，<br>若为欲求，半步黄泉。<br>教诲谨记，勿痴而妄言。<br><br>克拉众民，心当警戒，<br>守此规劝，莫贪邪谶。<br>刻骨铭心，避入此间，<br>教诲谨记，勿嗔而妄言。",
        drawer: "钫酸酱",
        coder: "钫酸酱",
        designer: "钫酸酱",
        writer: "钫酸酱",
        prefix: "",
        skills: ["vl_delagu_xj", "vl_delagu_xy", "vl_delagu_bm"],
        addition: [],
        pack: "Valyana",
        vp: 0,
        sort: "kela",
        rank: "legend",
    },
    vl_fate: {
        enable: true,
        name: "法特",
        title: "命运之手",
        gender: "male",
        bloc: "vl_quanzu",
        hp: 3,
        intro: "法特，生于兽人王国“克拉”南部的贫民窟中，幼年时其父母因卷入债务纠纷而死，其一人独自生活。法特十二岁时，曾尝试寻找杀死父母的仇人，未果，后在游历各处的剑术大师米亚的帮助下终于成功。法特有着天生的赌博天赋，纵横各大赌场且百战百胜，被各大赌场称为“命运之手”。",
        drawer: "钫酸酱",
        coder: "钫酸酱",
        designer: "钫酸酱",
        writer: "钫酸酱",
        prefix: "",
        skills: ["vl_fate_tm", "vl_fate_ss"],
        addition: [],
        pack: "Valyana",
        vp: 0,
        sort: "kela",
        rank: "epic",
    },
    vl_mika: {
        enable: true,
        name: "米卡",
        title: "但求浪息",
        gender: "male",
        bloc: "vl_maozu",
        hp: 4,
        intro: "米卡(6151A.W.-6342A.W.)，人鱼之海著名的“胡子”海盗团的第一任船长，作为一位海盗，她一年大部分时间都生活在海上，而营养的需求则是通过与人鱼族进行贸易获得。米卡能够成为船长，除了特殊的个人魅力以外，能够控制天气的能力也是其中之一。她能够让大海变得平静无波，保证航行的顺利进行。在她死后，许多生活在人鱼之海的船员们都以他为信仰，并自发为其建立雕塑。生活在人鱼之海的靠航行生存的人们，在航行之前或者每年的“「海行日」”，都会举行盛大的祭祀，以求得航行的顺利。",
        drawer: "钫酸酱",
        coder: "钫酸酱",
        designer: "钫酸酱",
        writer: "钫酸酱",
        prefix: "",
        skills: ["vl_mika_lx", "vl_mika_pl"],
        addition: [],
        pack: "Valyana",
        vp: 0,
        sort: "renyu",
        rank: "epic",
    },
    vl_mile: {
        enable: true,
        name: "米勒",
        title: "自然之灵",
        gender: "male",
        bloc: "vl_maozu",
        hp: 3,
        intro: "米勒，生于贵族家庭，但因为意外在十岁时，就和兄长分离。作为米尔克的弟弟，不像自己兄长一样出口成章，他认为修辞学只是无用指鹿为马。相反，他甚至说话有些结巴，这给他带来了许多困扰，他曾经因为这个毛病被其他人嘲笑。因此，他一怒之下逃到了万灵之森。<br>后来，他发现自己能够和其他人看不见的自然之灵交流，自然之灵们也很欢迎这个小家伙，他们因此结下了深厚的友谊。",
        drawer: "钫酸酱",
        coder: "钫酸酱",
        designer: "钫酸酱",
        writer: "钫酸酱",
        prefix: "",
        skills: ["vl_mile_tl", "vl_mile_ly"],
        addition: ["zhu"],
        pack: "Valyana",
        vp: 0,
        sort: "wanling",
        rank: "epic",
    },
    vl_milism: {
        enable: true,
        name: "米里森",
        title: "黔水之灵",
        gender: "male",
        bloc: "vl_langzu",
        hp: 4,
        intro: "米里森，虎兽人与狮兽人的后代，就读于「魔法学院」。尤善水性，拥有水元素魔法天赋。而且能够转移他人的疼痛到自己，被誉为「治愈魔法师」。",
        drawer: "钫酸酱",
        coder: "钫酸酱",
        designer: "钫酸酱",
        writer: "钫酸酱",
        prefix: "",
        skills: ["vl_milism_ql", "vl_milism_th", "vl_milism_gn"],
        addition: [],
        pack: "Valyana",
        vp: 0,
        sort: "xueyuan",
        rank: "legend",
    },
    vl_muen: {
        enable: true,
        name: "牧恩",
        title: "窃贼巧手",
        gender: "male",
        bloc: "vl_langzu",
        hp: 3,
        intro: "牧恩，色塔卡荒原上的盗贼，或者说是向导。这取决于你怎么看他。熟悉沙地的人都知道，色塔卡的路从不只属于地图：风会改写沙丘，烈日会抹去足迹，夜里的寒冷则会让最坚强的旅人失去判断。牧恩就在这样的地方长大，学会了用笑容问路，也学会了在别人低头看水囊时取走腰间的钱袋。<br>他并不喜欢把自己的手艺称作偷窃。在牧恩看来，能被他悄无声息拿走的东西，本就没有被主人好好看管。他总能在最拮据的时候从缝隙中找到机会，也总能从敌人的袖口、刀鞘或马鞍旁摸出能救命的东西。有人雇他带路，有人悬赏抓他，而牧恩通常会在两边都收钱之后，选一条只有自己知道的路离开。",
        drawer: "钫酸酱",
        coder: "钫酸酱",
        designer: "钫酸酱",
        writer: "钫酸酱",
        prefix: "",
        skills: ["vl_muen_tx", "vl_muen_jb"],
        addition: [],
        pack: "Valyana",
        vp: 0,
        sort: "setaka",
        rank: "common",
    },
    vl_sangdi: {
        enable: true,
        name: "桑迪",
        title: "深巷探风者",
        gender: "male",
        bloc: "vl_quanzu",
        hp: 3,
        intro: "桑迪，出生于迦奈尔联邦，他曾因他敏锐的嗅觉和出色的直觉，在数不清的罪犯抓捕行动中积累了杰出的战绩，但终究选择了离开。原因很简单——他感觉不自由。<br>于是，桑迪决定创办自己的侦探事务所，追求他所钟爱的独立生活。然而，在平日里，客户并不是那么多，这留给了他大量的空闲时间和自主权。这种自由是宝贵的，但三三两两的案件远不能满足他的经济需求，甚至无法支付房租。桑迪常常陷入深思，如何平衡自由与生计之间的权衡。<br><br>客串原型：染柒",
        drawer: "钫酸酱",
        coder: "染柒、钫酸酱",
        designer: "染柒",
        writer: "钫酸酱",
        prefix: "",
        skills: ["vl_sangdi_at", "vl_sangdi_bf", "vl_sangdi_zy"],
        addition: [],
        pack: "Valyana",
        vp: 0,
        sort: "jianaier",
        rank: "epic",
    },
    vl_yinlong: {
        enable: true,
        name: "印龙",
        title: "游龙影绰",
        gender: "female",
        bloc: "vl_longzu",
        hp: 3,
        intro: "印龙，随着一阵强烈的白光突然出现在龙之谷中的神秘龙族，受到了智慧之神哈尔斯的亲自接见。据说印龙是来自于另一平行时空的旅者，她天生热爱自然，不像其他龙族一样蔑视其他种族，而且具有媲美商业精英的经商知识，因此其在龙之谷中担任了与其他种族贸易和沟通的职务。<br><br>联动拓展：星穹防线-印龙",
        drawer: "钫酸酱",
        coder: "钫酸酱",
        designer: "钫酸酱、染柒",
        writer: "钫酸酱",
        prefix: "",
        skills: ["vl_yinlong_cb", "vl_yinlong_jh"],
        addition: [],
        pack: "Valyana",
        vp: 0,
        sort: "dragongu",
        rank: "epic",
    },
    vl_sainit: {
        enable: true,
        name: "塞涅特",
        title: "月华指引者",
        gender: "female",
        bloc: "shen",
        hp: 3,
        intro: "塞涅特，被远古神月神黛安娅的祝福的少女，体内流淌着神祇的血脉，她能够调动月光的力量。即使是清冷的月，在她的引导下，也能爆发灿烂的光芒。",
        drawer: "钫酸酱",
        coder: "钫酸酱",
        designer: "钫酸酱",
        writer: "钫酸酱",
        prefix: "",
        skills: ["vl_sainit_yj", "vl_sainit_jh"],
        addition: [],
        pack: "Valyana",
        vp: 0,
        sort: "kela",
        rank: "epic",
    },
    vl_skry: {
        enable: true,
        name: "斯克瑞",
        title: "毒计百出",
        gender: "male",
        bloc: "vl_quanzu",
        hp: 3,
        intro: "斯克瑞，「暗影」刺杀队的队长，擅长于通过下毒的方式来完成任务，他最著名的一次刺杀任务，就是接受哈拉尔的雇佣刺杀国王盖尔德鲁。在斯克瑞几近成功时被盖尔德鲁发现，被抓住并关押进地牢。后来哈拉尔即位后释放了斯克瑞，而这次刺杀也让他名声大噪。",
        drawer: "钫酸酱",
        coder: "钫酸酱",
        designer: "钫酸酱",
        writer: "钫酸酱",
        prefix: "",
        skills: ["vl_skery_ds", "vl_skery_yj"],
        addition: [],
        pack: "Valyana",
        vp: 0,
        sort: "franying",
        rank: "epic",
    },
    vl_fox: {
        enable: true,
        name: "狐克斯",
        title: "幻梦一场",
        gender: "male",
        bloc: "vl_hulizu",
        hp: 4,
        intro: "狐克斯，来自狐人一族的年轻旅人。与大多数狐人擅长化形和迷惑不同，他的能力更接近“梦的回声”：凡是经由他亲手施展过的动作，都会在短暂的时间里留下虚幻的影子。等到夕阳沉下，影子便会沿着原本的轨迹再度显现，像一场已经醒来的梦重新发生。<br>狐克斯常戴着护目镜，背着轻便的行装在大陆各处旅行。他说自己只是喜欢看不同地方的天空，但不少赏金公会的记录都提到过同一个红狐青年：他会在战斗中先以轻松的笑容试探对手，再让先前的步法、刀光与术式于黄昏时分接连重现。和他交手的人往往分不清哪一次是真实，哪一次只是幻梦遗留的余温。",
        drawer: "钫酸酱",
        coder: "钫酸酱",
        designer: "钫酸酱",
        writer: "钫酸酱",
        prefix: "",
        skills: ["vl_fox_hm"],
        addition: [],
        pack: "Valyana",
        vp: 0,
        sort: "kela",
        rank: "epic",
    },
    vl_molis: {
        enable: true,
        name: "莫莉斯",
        title: "时空跳跃者",
        gender: "female",
        bloc: "vl_hulizu",
        hp: 3,
        intro: "莫莉斯，神秘的占星术士“希顿”的女儿，受到智慧之神哈尔斯的青睐，获得了能够在时空中跳跃的能力，作为交换，莫莉斯要为哈尔斯记录各个时空发生的事情并汇报。",
        drawer: "钫酸酱",
        coder: "钫酸酱",
        designer: "钫酸酱",
        writer: "钫酸酱",
        prefix: "",
        skills: ["vl_molis_hs", "vl_molis_sy"],
        addition: [],
        pack: "Valyana",
        vp: 0,
        sort: "kela",
        rank: "legend",
    },
    vl_whitewolf: {
        enable: true,
        name: "华特",
        title: "固若金汤",
        gender: "male",
        bloc: "vl_langzu",
        hp: 4,
        intro: "华特，生于兽人王国“克拉”南部的贫民窟沐恩城中，是华兹的哥哥。在兽人王国最重要的巡游——“火灵日大典”被前任国王盖尔德鲁相中，与华兹一同进入王宫成为侍卫。华特的能力：“不动如山，动如雷震”，更加擅长防御与保护。在某次刺杀中因保护国王有功，被提拔为贴身侍卫，但是遭华兹嫉妒，二人反目。盖尔德鲁垮台后二人不知所踪。",
        drawer: "钫酸酱",
        coder: "钫酸酱",
        designer: "钫酸酱",
        writer: "钫酸酱",
        prefix: "",
        skills: ["vl_whitewolf_wl", "vl_whitewolf_fz"],
        addition: [],
        pack: "Valyana",
        vp: 0,
        sort: "kela",
        rank: "epic",
    },
    vl_blackwolf: {
        enable: true,
        name: "华兹",
        title: "浪潮汹涌",
        gender: "male",
        bloc: "vl_langzu",
        hp: 4,
        intro: "华兹，生于兽人王国“克拉”南部的贫民窟沐恩城中，从小与华特相依为命。在“火灵日大典”被国王盖尔德鲁相中，与华特一同进入王宫成为侍卫，后因嫉妒华特的能力，与其反目。华兹与华特不同，更擅长狂暴而快速的攻击，世人谓之：“一剑斩不摧,双刃去如来”，又赞曰：“势如涛浪汹涌，形如雨打秋风”。盖尔德鲁垮台后二人不知所踪。",
        drawer: "钫酸酱",
        coder: "钫酸酱",
        designer: "钫酸酱",
        writer: "钫酸酱",
        prefix: "",
        skills: ["vl_blackwolf_cy", "vl_blackwolf_nb"],
        addition: [],
        pack: "Valyana",
        vp: 0,
        sort: "kela",
        rank: "epic",
    },
    vl_dmoa: {
        enable: true,
        name: "多默尔",
        title: "日夜笙歌",
        gender: "female",
        bloc: "vl_hulizu",
        hp: 3,
        intro: "多默尔(7154A.W.-7366A.W.)，诞生于传统的一个兽人贵族家庭，她的父亲是宫廷的乐师，因此多默尔幼年时就展现出了惊人的乐器天赋，她能够将多种乐器组装起来进行演奏，一个人就能够达到一个乐团的演出效果。但是多默尔并不满足于接替父亲的工作。在20岁时，恰巧遇上库伦引发的魔网崩溃，当时法师人心涣散，多默尔自发的作为吟游诗人游历各国，用音乐的力量抚慰人心。",
        drawer: "钫酸酱",
        coder: "钫酸酱",
        designer: "钫酸酱",
        writer: "钫酸酱",
        prefix: "",
        skills: ["vl_dmoa_sg", "vl_dmoa_yh"],
        addition: [],
        pack: "Valyana",
        vp: 0,
        sort: "kela",
        rank: "epic",
    },
    vl_luwu: {
        enable: true,
        name: "陆伍",
        title: "兵圣",
        gender: "male",
        bloc: "vl_langzu",
        hp: 3,
        intro: "陆伍，出身军伍的狼族统帅，曾以极少兵力在混战中稳住全线，因此被人称作“兵圣”。他不以蛮勇取胜，更擅长利用敌人的破绽与阵形变化，将战场一步步引入自己设下的局中。<br>在许多老兵眼里，陆伍最可怕的不是锋刃，而是他始终冷静的判断。只要他还站在阵前，敌人的退路就往往已经被悄然封死。",
        drawer: "钫酸酱",
        coder: "狂神",
        designer: "白曦",
        writer: "钫酸酱",
        prefix: "",
        skills: ["vl_luwu_kd", "vl_luwu_yj"],
        addition: [],
        pack: "Valyana",
        vp: 0,
        sort: "dalu_lingmian",
        rank: "epic",
    },
    vl_liping: {
        enable: true,
        name: "李冯",
        title: "救世神医",
        gender: "male",
        bloc: "vl_langzu",
        hp: 3,
        intro: "李冯，字安民，战国前期名医。辰国兽。中元前3549年，生于辰立李家。在少时经历瘟疫，与家人别离后，寄宿在城外一户人家。期间，李冯学习从家中带出的医书，苦学医术，为附近的百姓治病，立志成为一名医者。随后，李冯游历四方，习尝百药，沿途为百姓治病，逐渐有了神医的称号。李冯总结出望闻问切的诊法，并编成《辰医书》，将千年来的医术总结，彻底形成了一套完整且科学的医学体系，开创了中医学的先河。中元前3348年，李冯在给季惠王治病上山采药中，被季国贵族派来的刺客刺杀身亡。",
        drawer: "钫酸酱",
        coder: "钫酸酱",
        designer: "白曦",
        writer: "钫酸酱",
        prefix: "",
        skills: ["vl_liping_ys", "vl_liping_sz", "vl_liping_yl"],
        addition: [],
        pack: "Valyana",
        vp: 0,
        sort: "dalu_lingmian",
        rank: "legend",
    },
    vl_zhanggu: {
        enable: true,
        name: "张蛊",
        title: "蛊鸩毒医",
        gender: "male",
        bloc: "vl_langzu",
        hp: 3,
        intro: "张蛊，字季阴，战国前期毒医，辰国兽，中原前3531年于辰立生。少时随辰宣王南迁。15岁时，母亲大病，张蛊不远千里去请李冯医治，后拜李冯为师。入门后，学习李冯的医术，大有所成。但行医理念与李冯不同，认为重病与生活对人来说是一种长久的痛苦，于是在一次毒死一位李冯的重病人后，被逐出师门。后半生一直追求毒术，帮一些重病或生活无望的人解脱。晚年，思念师傅，得知其在季国，于是前往并给季惠王下了轻毒，之后不久便死于季国。中元前3348年，寿终正寝。",
        drawer: "钫酸酱",
        coder: "钫酸酱",
        designer: "白曦",
        writer: "钫酸酱",
        prefix: "",
        skills: ["vl_zhanggu_dy", "vl_zhanggu_gs", "vl_zhanggu_yl"],
        addition: [],
        pack: "Valyana",
        vp: 0,
        sort: "dalu_lingmian",
        rank: "legend",
    },
    vl_xit: {
        enable: true,
        name: "希特",
        title: "夜梦龙魂",
        gender: "male",
        bloc: "vl_longzu",
        hp: 4,
        intro: "希特，龙之谷少见的拥有精神系能力龙裔，它可以强迫他人进入深眠，然后对其精神体直接发动攻击。一旦目标的精神体被击溃，那么他的肉体也会随之消亡。希特不善社交，不喜喧闹，因此隐居于龙之谷东侧的山谷之中，对于希特来说，每天最愉快的时刻就是去找印龙一同前往百花山谷，当然，对印龙来说也许是最头疼的时候，因为希特总做出一些令人无语的事情。",
        drawer: "钫酸酱",
        coder: "钫酸酱",
        designer: "钫酸酱",
        writer: "钫酸酱",
        prefix: "",
        skills: ["vl_xit_xm"],
        addition: [],
        pack: "Valyana",
        vp: 0,
        sort: "dragongu",
        rank: "common",
    },
    vl_azao: {
        enable: true,
        name: "阿早",
        title: "先声护誓",
        gender: "male",
        bloc: "vl_longzu",
        hp: 4,
        intro: "阿早，来自龙族边缘地带的年轻旅者，行事轻快，像总比旁人早一步醒来。别看他平日说话懒散，真到关键时刻，他的反应快得近乎本能，总能在风声未落时先护住自己想护的人。<br>他习惯把承诺看得比性命更重，也因此常被卷进一些并不轻松的麻烦里。对阿早来说，活着不只是呼吸，更是把该守的东西守到最后。",
        drawer: "钫酸酱",
        coder: "钫酸酱",
        designer: "钫酸酱",
        writer: "钫酸酱",
        prefix: "",
        skills: ["vl_azao_huxi", "vl_azao_guishi"],
        addition: [],
        pack: "Valyana",
        vp: 0,
        sort: "dragongu",
        rank: "epic",
    },
    vl_yifa: {
        enable: true,
        name: "弈法",
        title: "言灵圣者",
        gender: "female",
        bloc: "vl_hulizu",
        hp: 3,
        intro: "弈法，《瓦尔亚那百科》中曾参加了万灵之森保卫战的大英雄弈霜的后代，是弈风的妹妹。弈法天性好动活泼，其在幼时就被检测出有稀有的魔法天赋，能够通过语言来获得其他人的能力，《百科》中不曾预言过这种能力，实属世间罕见。由于此能力，其幼时便饱受困扰，许多贪婪狡诈之徒对此能力趋之若鹜。直至其十岁，父母因此而死，后与弈风共同远离兽人王国，前往精灵之森定居。",
        drawer: "钫酸酱",
        coder: "钫酸酱",
        designer: "钫酸酱",
        writer: "钫酸酱",
        prefix: "",
        skills: ["vl_yifa_xs"],
        addition: [],
        pack: "Valyana",
        vp: 0,
        sort: "wanling",
        rank: "epic",
    },
    vl_yifeng: {
        enable: true,
        name: "弈风",
        title: "执月之手",
        gender: "male",
        bloc: "vl_langzu",
        hp: 3,
        intro: "弈风，《瓦尔亚那百科》中曾参加了万灵之森保卫战的大英雄弈霜的后代，是弈法的哥哥，与弈法共同居住在万灵之森外围的不知名小村落中。弈风生性沉稳，不喜言辞，与弈法截然相反。据传，其拥有一把能够逆转因果的弓，名曰霜月，通体泛着银月丝绸般的光芒。被弓箭射中者，若其行径正义，心无不端，则平安无事，而若其为邪恶之辈，将会遭受最为严峻的痛苦，直至其为罪行忏悔。",
        drawer: "钫酸酱",
        coder: "钫酸酱",
        designer: "钫酸酱",
        writer: "钫酸酱",
        prefix: "",
        skills: ["vl_kref_yz", "vl_yifeng_ml"],
        addition: [],
        pack: "Valyana",
        vp: 0,
        sort: "wanling",
        rank: "rare",
    },
    vl_yue: {
        enable: true,
        name: "岳",
        title: "负山决刃",
        gender: "male",
        bloc: "vl_huzu",
        hp: "1/5/3",
        intro: "岳，沉默而自持的虎族战士，常以近乎苛刻的方式约束自己。他不喜欢多余的言辞，也不屑于把胜负寄托给运气，更愿意用最直接的方式迎接每一次对决。<br>在旁人看来，岳像一块难以撼动的山石；可真正交手后才会发现，他愿意把代价一并背在身上，只为换来一次足够彻底的反击。",
        drawer: "钫酸酱",
        coder: "钫酸酱",
        designer: "钫酸酱",
        writer: "钫酸酱",
        prefix: "",
        skills: ["vl_yue_jd", "vl_yue_hq"],
        addition: [],
        pack: "Valyana",
        vp: 0,
        sort: "vl_tiaodan",
        rank: "legend",
    },
    vl_ranxing: {
        enable: true,
        name: "燃星",
        title: "噬业罪羊",
        gender: "male",
        bloc: "vl_yangzu",
        hp: 3,
        intro: "燃星，生来便带着异样火息的羊族青年，像一团不肯熄灭的余烬。旁人眼中的罪与业，在他身上反倒会化作更旺的火，让他在混乱中越战越烈。<br>他既像受难者，也像宣判者，总能在别人的破绽里燃起自己的锋芒。凡是被他盯上的目标，很少还能保持原本的步调。",
        drawer: "钫酸酱",
        coder: "钫酸酱",
        designer: "钫酸酱",
        writer: "钫酸酱",
        prefix: "",
        skills: ["vl_ranxing_tx", "vl_ranxing_sy", "vl_ranxing_pq"],
        addition: [],
        pack: "Valyana",
        vp: 0,
        sort: "vl_tiaodan",
        rank: "legend",
    },
    vl_bofeng: {
        enable: true,
        name: "迟风",
        title: "玄色一剑",
        gender: "male",
        bloc: "vl_langzu",
        hp: 4,
        intro: "迟风，出身于克拉边境的狼族剑士，性情如名，出手却从不迟缓。<br>他惯以夺势、断招为先，常在敌人尚未站稳时便将局势撕开一道缺口。对他而言，剑不是单纯的杀器，而是逼迫对手在短瞬间做出选择的筹码。那些被他盯上的目标，往往还没来得及整理架势与兵刃，便已先被他拆去几分底气。",
        drawer: "钫酸酱",
        coder: "钫酸酱",
        designer: "钫酸酱",
        writer: "钫酸酱",
        prefix: "",
        skills: ["vl_bofeng_aj", "vl_bofeng_ld", "vl_bofeng_ws"],
        addition: [],
        pack: "Valyana",
        vp: 0,
        sort: "kela",
        rank: "legend",
    },
    vl_ciyu: {
        enable: true,
        name: "迟雨",
        title: "素色一心",
        gender: "male",
        bloc: "vl_langzu",
        hp: 4,
        intro: "迟雨，和迟风一同行走于克拉边境的狼族青年，行事冷静，善于调度与周旋。<br>他更像一场绵密的雨：不急着正面压垮对手，而是先将“协”散入局中，再在关键时刻借势转移、接应与护持。对他而言，真正重要的不是一击定胜负，而是让每个人都站在自己该站的位置上。",
        drawer: "钫酸酱",
        coder: "钫酸酱",
        designer: "钫酸酱",
        writer: "钫酸酱",
        prefix: "",
        skills: ["vl_ciyu_ss", "vl_ciyu_hq"],
        addition: [],
        pack: "Valyana",
        vp: 0,
        sort: "kela",
        rank: "legend",
    },
    vl_faers: {
        enable: true,
        name: "法斯",
        title: "永世恒常",
        gender: "female",
        bloc: "shen",
        hp: 4,
        intro: "法斯，或名法尔斯，兽人中最主要的神祇之一，代表了永恒与变换，是动与静的同一。法尔斯常以胡狼的形象示人，对任何物种都报以绝对的平衡。守护平衡是他的使命。但是在精灵族的预言集「瓦尔亚娜大百科」中其被预言是毁灭兽人王国的罪魁祸首。",
        drawer: "钫酸酱",
        coder: "钫酸酱",
        designer: "钫酸酱",
        writer: "钫酸酱",
        prefix: "",
        skills: ["vl_faers_hc", "vl_faers_sb", "vl_faers_yl"],
        addition: ["zhu"],
        pack: "Valyana",
        vp: 0,
        sort: "shoushen",
        rank: "legend",
    },
    vl_yinhu: {
        enable: true,
        name: "寅虎",
        title: "祥瑞祝福",
        gender: "male",
        bloc: "shen",
        hp: 3,
        intro: "寅虎，色塔卡荒漠最受敬仰的神明，当地的人们认为他能够去除一切灾厄并带来降雨，因此每一年的「清雨节」当地的人们都会举行盛大的祭祀活动，来纪念这位神明。",
        drawer: "钫酸酱",
        coder: "钫酸酱",
        designer: "钫酸酱",
        writer: "钫酸酱",
        prefix: "",
        skills: ["vl_yinhu_xr", "vl_yinhu_zd", "vl_yinhu_sp"],
        addition: [],
        pack: "Valyana",
        vp: 0,
        sort: "shoushen",
        rank: "legend",
    },
    vl_miya: {
        enable: true,
        name: "米亚",
        title: "连破剑圣",
        gender: "male",
        bloc: "vl_langzu",
        hp: 4,
        intro: "米亚，生于兽人王国「克拉」东部的小村落中。幼时便喜好剑术，随父亲学习。无意间得到「连破」与「两仪」两套剑法。成为远近闻名的剑术大师。「连破」剑法大成后，独自前往兽人王国「德恩」东部的兽人王国「奥格」历练。途中遇见科里科特，为其天赋所感。遂收其为徒，赠以「两仪」剑法。",
        drawer: "钫酸酱",
        coder: "fox⑧",
        designer: "fox⑧",
        writer: "钫酸酱",
        prefix: "",
        skills: ["vl_miya_hz", "vl_miya_ks"],
        addition: [],
        pack: "Valyana",
        vp: 0,
        sort: "youdangzhe",
        rank: "legend",
    },
    vl_krikt: {
        enable: true,
        name: "科里克特",
        title: "两仪剑使",
        gender: "male",
        bloc: "vl_langzu",
        hp: 4,
        intro: "科里科特，「连破」剑法大师米亚之徒。修习其赠与的「两仪」剑法。其剑术诡谲多变，剑术有着极强的爆发性。其剑法之转换，时而如同狂风骤雨般快速无比，时而如同狂涛骇浪般凶猛无匹，时而如同清泉溪涧般缓慢温柔细腻，时而如同秋风扫落叶般冷酷无情。世人皆赞之，有诗云：“霍如羿射九日落，矫如群帝骖龙翔。来如雷霆收震怒，罢如江海凝清光。”",
        drawer: "钫酸酱",
        coder: "钫酸酱",
        designer: "钫酸酱",
        writer: "钫酸酱",
        prefix: "",
        skills: ["vl_krikt_th", "vl_krikt_ly"],
        addition: [],
        pack: "Valyana",
        vp: 0,
        sort: "youdangzhe",
        rank: "legend",
    },
    vl_qima: {
        enable: true,
        name: "奇玛",
        title: "破月之心",
        gender: "male",
        bloc: "vl_langzu",
        hp: 3,
        intro: "奇玛，生活在沃尔夫东侧的索尔山脉附近。小时候，其父亲曾给予其一个由未知矿石制作的颜色吊坠，并言此物会在其遭遇危险时拯救其于水火。奇玛在一次前往深渊寻找拯救其父亲的草药：“忘忧草”时被深渊的魔物抓伤眼部，导致其视力丧失。",
        drawer: "钫酸酱",
        coder: "钫酸酱",
        designer: "钫酸酱",
        writer: "钫酸酱",
        prefix: "",
        skills: ["vl_qima_jm", "vl_qima_dz"],
        addition: ["forbidai"],
        pack: "Valyana",
        vp: 0,
        sort: "youdangzhe",
        rank: "legend",
    },
    vl_akain: {
        enable: true,
        name: "阿卡因",
        title: "风云变幻",
        gender: "male",
        bloc: "vl_langzu",
        hp: 3,
        intro: "阿卡因，出生于克拉北境与旧军镇交界的狼族术士。当地常年被寒潮与地火夹击，部族为了生存频繁依附不同领主，阿卡因也因此自幼学会了在立场之间转换。他胸前佩戴的法轮原是北境祭司用来观测元素潮汐的仪器，后来被他改造成能够收束火焰与寒气的法球。<br>在一次边境冲突中，阿卡因所在的部族被两支军队同时征召。两边都要求他交出法轮作为军用术器，他却趁夜引动冰层与地火，让两支军队在裂开的冻土前同时停下。那以后，阿卡因离开北境，继续研究元素彼此转化的方式。他不轻易承诺忠诚，因为他见过太多旗帜在风雪中换了颜色。",
        drawer: "钫酸酱",
        coder: "钫酸酱",
        designer: "fox⑧",
        writer: "钫酸酱",
        prefix: "",
        skills: ["vl_akain_bx", "vl_akain_ys", "vl_akain_fy", "vl_akain_jh"],
        addition: ["doublegroup:wei:shu"],
        pack: "Valyana",
        vp: "1/3",
        sort: "kela",
        rank: "epic",
    },
    vl_alas: {
        enable: true,
        name: "奥拉斯",
        title: "破空断魂",
        gender: "male",
        bloc: "vl_quanzu",
        hp: 4,
        intro: "奥拉斯，出身于迦奈尔联邦南部的地下拳场，是犬族中少有的重拳手。少年时的奥拉斯原本只是拳场杂工，因替受伤的拳手上台，被迫与成名拳王交手。那一战中，他连续挨了七记重拳仍未倒下，最后用一记贴身直拳击碎了对方的护齿，也为自己赢下了第一副红色拳套。<br>离开拳场后，奥拉斯没有加入正规军，而是跟随商队和佣兵团穿行各地。他对规则的理解很简单：擂台上只要铃声没响，谁也不能说胜负已定；战场上只要敌人还握着武器，就必须把那份威胁彻底打掉。因此他总是逼近、压迫、连续出拳，直到对手连喘息的空隙都找不到。",
        drawer: "钫酸酱",
        coder: "钫酸酱",
        designer: "钫酸酱",
        writer: "钫酸酱",
        prefix: "",
        skills: ["vl_olas_fh", "vl_olas_bx"],
        addition: [],
        pack: "Valyana",
        vp: 0,
        sort: "jianaier",
        rank: "common",
    },
    vl_berg: {
        enable: true,
        name: "伯格",
        title: "镜花水月",
        gender: "male",
        bloc: "vl_langzu",
        hp: 3,
        intro: "伯格，龙之谷外环月湖旁长大的狼族幻术师。月湖水面常年映着巨大的月影，湖底又埋有古龙遗留的魔晶，因此附近居民常能看见并不存在的人影与花火。伯格幼年时误入湖心禁地，醒来后便能把月光、水影和记忆碎片折成短暂的幻象。<br>成年后的伯格没有加入龙之谷的正规法师序列，而是独自记录月湖异象。他手中那枚紫色光球据说由湖底魔晶打磨而成，能够把即将发生的现实折射成另一种可能。伯格很少解释自己的术法，因为他知道，幻象一旦被说穿，就只剩下廉价的戏法。",
        drawer: "钫酸酱",
        coder: "钫酸酱",
        designer: "钫酸酱",
        writer: "钫酸酱",
        prefix: "",
        skills: ["vl_berg_sy", "vl_berg_jh"],
        addition: [],
        pack: "Valyana",
        vp: 0,
        sort: "dragongu",
        rank: "epic",
    },
    vl_bladewolf: {
        enable: true,
        name: "刃狼",
        title: "机魂熔炉",
        gender: "male",
        bloc: "vl_jiqi",
        hp: 4,
        intro: "刃狼，是产于迦奈尔联邦的机器人，由于其驱动需要大量的电力，因此刃狼作为该型号唯一的机器人被装载了核动力反应堆。刃狼的生产目的是为了战争，因此其功能也被特化为战争相关，并卸除了情感模块。但是后来因一些机缘巧合，被西普感化并重新获得了情感，在其死后将其带回并改造为了机械生命。",
        drawer: "钫酸酱",
        coder: "钫酸酱",
        designer: "钫酸酱",
        writer: "钫酸酱",
        prefix: "",
        skills: ["vl_bladewolf_qp", "vl_bladewolf_rh"],
        addition: ["forbidai"],
        pack: "Valyana",
        vp: 0,
        sort: "jixiezaowu",
        rank: "legend",
    },
    vl_sheep: {
        enable: true,
        name: "西普",
        title: "能机巧算",
        gender: "female",
        bloc: "vl_jiqi",
        hp: 3,
        intro: "西普，原生活于克拉，是出生于贫民窟的普通兽人；在哈拉尔国王上任前的那位国王——盖尔德鲁，是一位不折不扣的暴君，他欺压百姓并强迫贫民窟的人们前往战场。西普不幸被选中，后在战场上遇到了战争机器人——刃狼，经历一系列事件之后，西普成功使得刃狼获得了感情并相爱。后来再一次意外中，西普战死。刃狼将其带回并改造为机械生命。但是由于死去过久，其记忆没有被继承，现在将刃狼当作自己的哥哥。",
        drawer: "钫酸酱",
        coder: "钫酸酱",
        designer: "钫酸酱",
        writer: "钫酸酱",
        prefix: "",
        skills: ["vl_sheep_jf", "vl_sheep_rh"],
        addition: [],
        pack: "Valyana",
        vp: 0,
        sort: "jixiezaowu",
        rank: "legend",
    },
    vl_horn: {
        enable: true,
        name: "霍恩",
        title: "恶灵推手",
        gender: "male",
        bloc: "vl_yangzu",
        hp: 3,
        intro: "霍恩，据传是来自深渊的恶魔，为了夺取米兰寺的珍贵宝物——豁免权杖，设计杀死了米兰寺的住持。霍恩不喜活物，他常常会放出致死的魔法，杀死周围的一切。",
        drawer: "钫酸酱",
        coder: "钫酸酱",
        designer: "钫酸酱",
        writer: "钫酸酱",
        prefix: "",
        skills: ["vl_horn_ql", "vl_horn_ll"],
        addition: [],
        pack: "Valyana",
        vp: 0,
        sort: "milan",
        rank: "epic",
    },
    vl_jet: {
        enable: true,
        name: "杰特",
        title: "混乱之神",
        gender: "male",
        bloc: "shen",
        hp: 3,
        intro: "杰特，兽人诸神中少有的混乱神。有关他的记载极少，且互相矛盾：有的文书称他曾在王国初立时为诸部落传递火种，有的祭文却说他在同一日诱发了七场叛乱。神学者普遍认为，杰特并不掌管单纯的灾祸，而是掌管“秩序被打断后的可能性”。<br>他常以披着深色外衣、指间缠绕火光的狼族形象出现。每逢王权、军阵或仪式过于稳定时，杰特便会隐匿身份进入其中，轻轻拨动某个看似无关紧要的选择。有人因此得救，也有人因此毁灭。杰特从不解释自己的目的，只说若世界永远按一种方式运转，神明也会感到无聊。",
        drawer: "钫酸酱",
        coder: "钫酸酱",
        designer: "钫酸酱",
        writer: "钫酸酱",
        prefix: "",
        skills: ["vl_jet_fy", "vl_jet_ww", "vl_jet_sl", "vl_jet_cl"],
        addition: ["hiddenSkill"],
        pack: "Valyana",
        vp: 0,
        sort: "shoushen",
        rank: "legend",
    },
    vl_kmjia: {
        enable: true,
        name: "卡米加",
        title: "教指人心",
        gender: "male",
        bloc: "vl_quanzu",
        hp: 3,
        intro: "卡米加，犬族出身的巡回教士，曾在克拉南境的教会学校任教。他年轻时并不以武力见长，却极擅长观察学生与信众的情绪变化，能够用几句话让争斗双方暂时放下武器。后来南境饥荒爆发，地方贵族强征粮食，卡米加带着学生护送难民离开，途中第一次将所有物资与行动计划交给一名年轻护卫执行。<br>那场逃亡让卡米加意识到，所谓领导并非永远站在最前面，而是在恰当时刻把路让给更适合行动的人。此后他不再固定任教，而是带着书箱在南境各村镇之间行走，替流亡者调解纠纷、安排去路。他记录不同人的选择与代价，也记录自己每一次因判断错误而付出的伤口。",
        drawer: "钫酸酱",
        coder: "钫酸酱",
        designer: "钫酸酱",
        writer: "钫酸酱",
        prefix: "",
        skills: ["vl_kamijia_sx", "vl_kamijia_dr"],
        addition: ["zhu"],
        pack: "Valyana",
        vp: 0,
        sort: "kela",
        rank: "epic",
    },
    vl_knier: {
        enable: true,
        name: "科妮尔",
        title: "花非花，雾非雾",
        gender: "female",
        bloc: "vl_langzu",
        hp: 3,
        intro: "科妮尔，出生于万灵之森北侧的湖畔村落。村中每年春末都会出现覆盖湖面的白雾，雾中盛开的水花能够短暂吸收外来的魔力。科妮尔幼年时因体弱常被禁止外出，却在一次走失中独自穿过雾湖，带回了一枝不会枯萎的白花。自那以后，她便能把袭来的术式封进花雾之中。<br>成年后的科妮尔被龙之谷的学者邀请研究雾湖现象，但她并不适应学院生活，最终只留下几份笔记便离开。她更喜欢独自在湖边观察雾气涨落，把危险先藏进看不清的地方，再等它变成一朵安静的花。对科妮尔而言，花不是装饰，而是雾中最温柔也最危险的陷阱。",
        drawer: "钫酸酱",
        coder: "钫酸酱",
        designer: "钫酸酱",
        writer: "钫酸酱",
        prefix: "",
        skills: ["vl_knier_yc", "vl_knier_wh", "vl_knier_hp"],
        addition: [],
        pack: "Valyana",
        vp: 0,
        sort: "wanling",
        rank: "legend",
    },
    vl_lamost: {
        enable: true,
        name: "拉莫斯特",
        title: "犹记繁华",
        gender: "male",
        bloc: "vl_langzu",
        hp: 4,
        intro: "拉莫斯特，旧克拉贵族“拉莫斯特家”的末裔。盖尔德鲁统治后期，拉莫斯特家因拒绝为王室提供军费而被抄没，家族藏书与艺术品大多流入黑市。拉莫斯特本人侥幸逃离王城，只带走了一枚祖传的戒指和几页残缺账册。<br>流亡期间，他靠鉴定古物与整理失散文书谋生，也因此练就了从杂乱文卷中辨认可用线索的能力。后来他开始追查家族藏书的下落，逐渐走遍克拉各地旧书铺、黑市和废宅。拉莫斯特收集这些记录，不是为了复辟旧贵族，而是为了证明那些曾经繁华的名字并未完全消失。",
        drawer: "钫酸酱",
        coder: "钫酸酱",
        designer: "钫酸酱",
        writer: "钫酸酱",
        prefix: "",
        skills: ["vl_lamost_zf"],
        addition: [],
        pack: "Valyana",
        vp: 0,
        sort: "kela",
        rank: "common",
    },
    vl_marxya: {
        enable: true,
        name: "马尔西亚",
        title: "谨小慎微",
        gender: "male",
        bloc: "vl_longzu",
        hp: 3,
        intro: "马尔西亚，龙之谷防卫队的斥候军官。龙族天生强大，许多年轻龙裔习惯以力量压制敌人，马尔西亚却恰好相反。他在第一次边境巡查中因冒进失去了整支小队，从此变得极端谨慎，凡事必先测距、留路、预藏退路。<br>他的作战方式源自龙之谷斥候使用的旧式战法：不与敌人正面交锋，而是让第一轮攻击落空，再趁对手露出破绽时回收战利品。马尔西亚身上总带着多枚护符和备用短刃，看似累赘，却都是他在某次死里逃生后留下的习惯。对他来说，谨慎不是怯懦，而是对死去队友最基本的尊重。",
        drawer: "钫酸酱",
        coder: "钫酸酱",
        designer: "钫酸酱",
        writer: "钫酸酱",
        prefix: "",
        skills: ["vl_marcia_us", "vl_marcia_jz", "vl_marcia_ql"],
        addition: [],
        pack: "Valyana",
        vp: 0,
        sort: "dragongu",
        rank: "epic",
    },
    vl_ming: {
        enable: true,
        name: "鸣",
        title: "能言善辩",
        gender: "male",
        bloc: "vl_huzu",
        hp: 3,
        intro: "鸣，虎族书吏之子，幼年随父亲迁居克拉南部学城。与大多数虎族崇尚武力不同，鸣从小更喜欢背诵成语、诗句和古代判例。他曾因身形瘦小被同龄人嘲笑，却能在辩论课上连续接出数十个成语，让整间学堂哑口无言。<br>成年后，鸣成为巡回书记官，专门为不识字的村镇撰写诉状与契约。他相信语言并不比刀剑软弱，好的句子能够让人冷静，也能让敌人露出破绽。后来鸣在一次护送文书的途中遭遇盗匪，他一边吟诵诗句一边以短刃反击，第一次明白自己背下的文字也能成为护身的锋刃。",
        drawer: "钫酸酱",
        coder: "钫酸酱",
        designer: "钫酸酱",
        writer: "钫酸酱",
        prefix: "",
        skills: ["vl_ming_yc", "vl_ming_yy"],
        addition: [],
        pack: "Valyana",
        vp: 0,
        sort: "kela",
        rank: "epic",
    },
    vl_mountainbear: {
        enable: true,
        name: "山熊",
        title: "力透千钧",
        gender: "male",
        bloc: "vl_xiongzu",
        hp: "3/3/4",
        intro: "&nbsp&nbsp&nbsp&nbsp山熊，原本是一只栖息在矮人之心洞穴周围的强大魔兽。它的存在一直是矮人部落的威胁，不断地对部落成员构成威胁。然而，山熊的命运在一次决定性的战斗中发生了巨变。在那场战斗中，山熊遭到了路西法的父亲的挑战。这场战斗激烈而残酷，但最终，路西法的父亲以出色的战斗技巧和坚韧不拔的意志，战胜了山熊。这场胜利被看作是路西法的父亲的一项英勇壮举，也标志着山熊的命运将发生改变。\n            <br>&nbsp&nbsp&nbsp&nbsp作为成年礼的礼物，路西法的父亲决定将山熊送给他的儿子。这个决定改变了山熊的生活轨迹，也让它与路西法的命运紧密交织在一起。在路西法的成年礼上，他通过强大的战斗技巧获得了山熊的认可。这次战斗是他们之间的一场考验，也是他们友谊的开始。山熊看到了路西法的坚决和勇气，开始信任他，并与他签订了一份特殊的契约。\n            <br>&nbsp&nbsp&nbsp&nbsp多年来，山熊和路西法成为了一对默契无间的伙伴。他们已经可以通过思想交流，将彼此的意愿传达得非常清晰，这是一种深厚的信任和默契的体现。他们的生命似乎已经通过契约而紧密连接，无论在战斗还是在日常生活中，他们总是互相扶持，守护着彼此。山熊生性暴戾，在没有兽语者控制的情况下。它可能会表现出随意伤人的行为，因此，只有路西法的存在和指导才能确保山熊不会陷入暴怒之中，保持友善和控制。\n            <br>&nbsp&nbsp&nbsp&nbsp山熊和路西法的故事是一段关于友情和信任的传奇。他们的契约将继续引领他们前行，不仅是伙伴，也是彼此的支持和保护者。这个不寻常的友情，已经成为了他们生命中最宝贵的财富。",
        drawer: "钫酸酱",
        coder: "钫酸酱",
        designer: "钫酸酱",
        writer: "钫酸酱",
        prefix: "",
        skills: ["vl_mountainbear_xs", "vl_mountainbear_xj"],
        addition: ["unseen"],
        pack: "Valyana",
        vp: 0,
        sort: "airenzhixin",
        rank: "common",
    },
    vl_nore: {
        enable: true,
        name: "诺尔",
        title: "观微洞察",
        gender: "male",
        bloc: "vl_langzu",
        hp: 4,
        intro: "诺尔，出生于克拉西部矿镇的狼族调查员。矿镇地下遍布废弃坑道，当地人称其为“洞中”，认为那里会吞掉声音、火光和人的来路。诺尔少年时曾在矿难中被困三日，获救后便对黑暗、回声和无来源的震动异常敏感。<br>后来诺尔加入巡查署，专门调查那些无法确定凶手的案件。他常说，真正危险的伤害并不一定有清晰的来源，有时一条被忽略的坑道、一盏被移动过的灯，就足以说明整件事的走向。诺尔的调查方式冷静而缓慢，却总能从看似空洞的现场中挖出藏在渊薮里的真相。",
        drawer: "钫酸酱",
        coder: "钫酸酱",
        designer: "钫酸酱",
        writer: "钫酸酱",
        prefix: "",
        skills: ["vl_nore_dz", "vl_nore_ys"],
        addition: [],
        pack: "Valyana",
        vp: 0,
        sort: "kela",
        rank: "rare",
    },
    vl_tiers: {
        enable: true,
        name: "缇尔斯",
        title: "战场玫瑰",
        gender: "female",
        bloc: "vl_tuzu",
        hp: 3,
        intro: "缇尔斯，生活在迦奈尔联邦，由于联邦周围大量禁魔矿石的影响，此处无法施展魔法，故此处的主要研究方向为科技。缇尔斯幼时丧父，与母亲相依为命，后进入联邦军队，在服役5年后因在与矮人的战争中负伤，回到家乡科马修养。",
        drawer: "钫酸酱",
        coder: "钫酸酱",
        designer: "钫酸酱",
        writer: "钫酸酱",
        prefix: "",
        skills: ["vl_tiers_qp", "vl_tiers_kh"],
        addition: [],
        pack: "Valyana",
        vp: 0,
        sort: "jianaier",
        rank: "rare",
    },
    vl_verb: {
        enable: true,
        name: "韦贝尔",
        title: "绝处逢生",
        gender: "male",
        bloc: "vl_shuzu",
        hp: 3,
        intro: "韦贝尔，鼠族行商与情报贩子，常年往返于克拉、迦奈尔联邦与人鱼之海之间。他身形不高，胆子却很大，最擅长在强者谈判时挤进一句话，再把所有人的注意力引向自己想要的方向。<br>韦贝尔曾在一次黑市交易中被双方同时追杀，身上只剩一只货箱和几枚残币。为了活命，他当着所有追兵的面逐个点破他们私藏的秘密，逼迫众人先交出筹码再继续谈判。那次经历让他养成了先让每个人表态的习惯，再从别人暴露出的欲望里寻找生路。韦贝尔不认为自己幸运，他只是比大多数人更熟悉绝境的价格。",
        drawer: "钫酸酱",
        coder: "钫酸酱",
        designer: "钫酸酱",
        writer: "钫酸酱",
        prefix: "",
        skills: ["vl_verb_zy", "vl_verb_fs"],
        addition: [],
        pack: "Valyana",
        vp: 0,
        sort: "youdangzhe",
        rank: "epic",
    },
    vl_wes: {
        enable: true,
        name: "维斯",
        title: "同生共死",
        gender: "male",
        bloc: "vl_longzu",
        hp: 3,
        intro: "维斯，生活在克拉北部的小镇米拉亚纳行省，毗邻吸血鬼禁区。由于附近丰富的魔力资源影响，维斯从小便表现出了强烈的魔法亲和性，其能力能够转移其他人受到的伤害。由于其能力的特殊性，自小其就被送往当地教会培养。",
        drawer: "钫酸酱",
        coder: "钫酸酱",
        designer: "钫酸酱",
        writer: "钫酸酱",
        prefix: "",
        skills: ["vl_wes_ts", "vl_wes_gs", "vl_wes_lt"],
        addition: [],
        pack: "Valyana",
        vp: 0,
        sort: "kela",
        rank: "legend",
    },
    vl_west: {
        enable: true,
        name: "韦斯特",
        title: "仁心医者",
        gender: "male",
        bloc: "vl_quanzu",
        hp: 3,
        intro: "韦斯特，犬族药剂师，早年就读于迦奈尔联邦的民间医学院。因无法使用魔法，他转而研究草药、炼金溶剂和战场急救术；随身携带的粉色药剂，是他反复改良出的复苏药水，能够在短时间内稳定濒死者的生命体征。<br>矮人之心争夺战期间，韦斯特随医疗队进入前线，亲眼见到许多士兵因诅咒侵蚀、失血过多或护具崩毁而死。战争结束后，他离开联邦军医系统，开始独自旅行，为贫民窟和边境村落提供治疗。韦斯特相信医者的职责不仅是缝合伤口，更是把一个人从混乱与痛苦中重新扶回活人的道路。",
        drawer: "钫酸酱",
        coder: "钫酸酱",
        designer: "钫酸酱",
        writer: "钫酸酱",
        prefix: "",
        skills: ["vl_west_pz", "vl_west_sx", "vl_west_jh"],
        addition: [],
        pack: "Valyana",
        vp: 0,
        sort: "jianaier",
        rank: "rare",
    },
    vl_wind: {
        enable: true,
        name: "温迪",
        title: "且听风吟",
        gender: "male",
        bloc: "vl_langzu",
        hp: 4,
        intro: "温迪，生活在人鱼之海沿岸的狼族旗手。少年时他常在港口帮船员收帆，能够通过旗帜、浪花和风声判断天气变化。后来一位流浪法师发现温迪对气流极为敏感，教他把风向、对象与结果拆成三枚独立的术式标记。<br>温迪并不擅长猛烈的攻击，他的能力更像调风：有时将顺风引向自己，有时把逆风推给旁人，有时在启程前改变局面，有时又等到一日将尽才让风落下。许多船员相信，只要温迪愿意在出航前听一听海上的风，船队就能避开最坏的风暴。",
        drawer: "钫酸酱",
        coder: "钫酸酱",
        designer: "钫酸酱",
        writer: "钫酸酱",
        prefix: "",
        skills: ["vl_wind_fy"],
        addition: [],
        pack: "Valyana",
        vp: 0,
        sort: "renyu",
        rank: "rare",
    },
    vl_yas_klin: {
        enable: true,
        name: "亚瑟",
        title: "祭天请神",
        gender: "male",
        bloc: "shen",
        hp: 4,
        intro: "亚瑟，旧祭司家族“克林”最后的继承人。克林家族原本侍奉诸神中的恐惧与契约之神，擅长通过献祭换取短暂庇护。新王朝建立后，这类血祭仪式被严厉禁止，亚瑟的族人陆续流亡，只留下他继续守着废弃祭坛。<br>亚瑟并不认为祭牲必然代表残酷。在他看来，真正的祭祀是把代价清楚地摆出来，让神明、施术者和受益者都无法逃避交换的结果。他在一场失控仪式中活了下来，手上残留的血契也从此与恐惧相连。若有人杀死亚瑟，契约会立刻反噬凶手，这也是许多猎神者至今不愿靠近他的原因。",
        drawer: "钫酸酱",
        coder: "钫酸酱",
        designer: "钫酸酱",
        writer: "钫酸酱",
        prefix: "",
        skills: ["vl_yas_klin_bj", "vl_yas_klin_js"],
        addition: [],
        pack: "Valyana",
        vp: 0,
        sort: "shoushen",
        rank: "legend",
    },
    vl_youying: {
        enable: true,
        name: "游影",
        title: "挥剑如歌",
        gender: "male",
        bloc: "vl_langzu",
        hp: 4,
        intro: "游影，出生于万灵之森边陲的小镇“米埃”。自幼跟随父亲修行剑法，后出门远行前往米兰寺求学，经介绍后跟随米亚学习剑术，但最后因理念不同而分道扬镳。游影的剑法诡谲，翩若惊鸿，宛若游龙。剑法精妙，如诗般令人赏心悦目。",
        drawer: "钫酸酱",
        coder: "钫酸酱",
        designer: "钫酸酱",
        writer: "钫酸酱",
        prefix: "",
        skills: ["vl_youying_jg", "vl_youying_qy"],
        addition: [],
        pack: "Valyana",
        vp: 0,
        sort: "youdangzhe",
        rank: "epic",
    },
    vl_zeron: {
        enable: true,
        name: "泽罗恩",
        title: "以牙还牙",
        gender: "male",
        bloc: "vl_haizu",
        hp: 4,
        intro: "泽罗恩，人鱼之海著名“胡子海盗团”的现任船长，他作为一位船长可谓是尽职尽责，或者对他来说每一位船员都是他的朋友。泽罗恩小时候便因父亲的家庭暴力失去了母亲，父亲整日酗酒对他不管不顾，甚至拳脚相加。这也导致泽罗恩没法上学而早早成为了一名海盗。泽罗恩成为海盗是因为他亲自手刃了自己的父亲被通缉，只能落草为寇。他信奉的信条便是“以牙还牙，以眼还眼”，如果你是他的朋友，他会对你百般纵容，如果你是他的敌人，他则会负责让你去见神明。",
        drawer: "钫酸酱",
        coder: "钫酸酱",
        designer: "钫酸酱",
        writer: "钫酸酱",
        prefix: "",
        skills: ["vl_zeron_sx"],
        addition: [],
        pack: "Valyana",
        vp: 0,
        sort: "renyu",
        rank: "common",
    },
    vl_zeta: {
        enable: true,
        name: "泽塔",
        title: "固铸何归？",
        gender: "male",
        bloc: "vl_longzu",
        hp: 4,
        intro: "泽塔，龙之谷外城的锻造师，拥有少见的绿鳞龙族血统。他年轻时曾进入矮人之心学习金属锻造，因体格高大、力气惊人，被矮人师傅要求背负巨锤和铁砧完成整整三年的基础训练。泽塔肩上的小鸟名叫“归巢”，是他在矿洞坍塌后救下的信鸟，也成了他判断回程方向的伙伴。<br>泽塔相信任何材料都不该只被使用一次。废铁、断刃、破甲在他眼中都像散落的矿石，只要分类、回炉、重新分配，仍能铸成新的用途。后来他回到龙之谷开设工坊，专门回收战后遗留的兵刃与护具；许多被视为无法修复的残件，都会在他的炉火里获得第二次形状。",
        drawer: "钫酸酱",
        coder: "钫酸酱",
        designer: "钫酸酱",
        writer: "钫酸酱",
        prefix: "",
        skills: ["vl_zeta_gz", "vl_zeta_fg"],
        addition: [],
        pack: "Valyana",
        vp: 0,
        sort: "dragongu",
        rank: "epic",
    },
    vl_zhan: {
        enable: true,
        name: "展",
        title: "束缚之厄",
        gender: "male",
        bloc: "vl_maozu",
        hp: 3,
        intro: "展，猫族少年，出身不详。关于他的最早记录来自克拉北部一处废弃实验室，搜救者在那里发现了断裂的铁链、刻满禁制的地面，以及一份被烧毁大半的实验日志。日志中将展称作“束缚样本”，认为他的体内能够在受伤后自动修复，并把伤害转化为更强的适应能力。<br>展被救出时已经无法正常使用多数后天训练出的技艺，只有束缚本身与解放冲动留在身体里。平日的展沉默、警惕，身上仍保留着锁链与拘束具留下的痕迹；一旦承受的痛苦超过极限，那些禁制便会崩断，并向周围释放名为「灾厄」的残留力量。此后他一直避开人群流浪，不是因为不懂得求助，而是害怕自己再次成为别人眼中的实验材料。",
        drawer: "钫酸酱",
        coder: "钫酸酱",
        designer: "钫酸酱",
        writer: "钫酸酱",
        prefix: "",
        skills: ["vl_zhan_sf", "vl_zhan_jf"],
        addition: [],
        pack: "Valyana",
        vp: 0,
        sort: "kela",
        rank: "legend",
    },
    vl_kulun_light: {
        enable: true,
        name: "库伦·光明",
        title: "",
        gender: "male",
        bloc: "vl_langzu",
        hp: 1,
        intro: "",
        drawer: "钫酸酱",
        coder: "钫酸酱",
        designer: "钫酸酱",
        writer: "钫酸酱",
        prefix: "",
        skills: ["vl_kulun_light_sg", "vl_kulun_light_yb"],
        addition: ['unseen'],
        pack: "Valyana",
        vp: 0,
        sort: "jianaier",
        rank: "epic",
    },
    vl_kulun_dark: {
        enable: true,
        name: "库伦·黑暗",
        title: "",
        gender: "male",
        bloc: "vl_langzu",
        hp: 1,
        intro: "",
        drawer: "钫酸酱",
        coder: "钫酸酱",
        designer: "钫酸酱",
        writer: "钫酸酱",
        prefix: "",
        skills: ["vl_kulun_dark_as", "vl_kulun_dark_yb"],
        addition: ['unseen'],
        pack: "Valyana",
        vp: 0,
        sort: "kela",
        rank: "epic",
    },
    vl_kulun_wind: {
        enable: true,
        name: "库伦·飓风",
        title: "",
        gender: "male",
        bloc: "vl_langzu",
        hp: 1,
        intro: "",
        drawer: "钫酸酱",
        coder: "钫酸酱",
        designer: "钫酸酱",
        writer: "钫酸酱",
        prefix: "",
        skills: ["vl_kulun_wind_wx", "vl_kulun_wind_cm"],
        addition: ['unseen'],
        pack: "Valyana",
        vp: 0,
        sort: "wanling",
        rank: "epic",
    },
    vl_kulun_fire: {
        enable: true,
        name: "库伦·火焰",
        title: "",
        gender: "male",
        bloc: "vl_langzu",
        hp: 1,
        intro: "",
        drawer: "钫酸酱",
        coder: "钫酸酱",
        designer: "钫酸酱",
        writer: "钫酸酱",
        prefix: "",
        skills: ["vl_kulun_fire_ly", "vl_kulun_fire_fz"],
        addition: ['unseen'],
        pack: "Valyana",
        vp: 0,
        sort: "jianaier",
        rank: "epic",
    },
    vl_kulun_water: {
        enable: true,
        name: "库伦·潮汐",
        title: "",
        gender: "male",
        bloc: "vl_langzu",
        hp: 1,
        intro: "",
        drawer: "钫酸酱",
        coder: "钫酸酱",
        designer: "钫酸酱",
        writer: "钫酸酱",
        prefix: "",
        skills: ["vl_kulun_water_sy", "vl_kulun_water_jy"],
        addition: ['unseen'],
        pack: "Valyana",
        vp: 0,
        sort: "jianaier",
        rank: "epic",
    },
    vl_kulun_ice: {
        enable: true,
        name: "库伦·寒冰",
        title: "",
        gender: "male",
        bloc: "vl_langzu",
        hp: 1,
        intro: "",
        drawer: "钫酸酱",
        coder: "钫酸酱",
        designer: "钫酸酱",
        writer: "钫酸酱",
        prefix: "",
        skills: ["vl_kulun_ice_hs", "vl_kulun_ice_dj"],
        addition: ['unseen'],
        pack: "Valyana",
        vp: 0,
        sort: "renyu",
        rank: "epic",
    },
    vl_kulun_metal: {
        enable: true,
        name: "库伦·金属",
        title: "",
        gender: "male",
        bloc: "vl_langzu",
        hp: 1,
        intro: "",
        drawer: "钫酸酱",
        coder: "钫酸酱",
        designer: "钫酸酱",
        writer: "钫酸酱",
        prefix: "",
        skills: ["vl_kulun_metal_zl", "vl_kulun_metal_rh"],
        addition: ['unseen'],
        pack: "Valyana",
        vp: 0,
        sort: "kela",
        rank: "epic",
    },
    vl_kulun_nature: {
        enable: true,
        name: "库伦·自然",
        title: "",
        gender: "male",
        bloc: "vl_langzu",
        hp: 1,
        intro: "",
        drawer: "钫酸酱",
        coder: "钫酸酱",
        designer: "钫酸酱",
        writer: "钫酸酱",
        prefix: "",
        skills: ["vl_kulun_nature_hc", "vl_kulun_nature_tw"],
        addition: ['unseen'],
        pack: "Valyana",
        vp: 0,
        sort: "kela",
        rank: "epic",
    },
    vl_kulun_dirt: {
        enable: true,
        name: "库伦·大地",
        title: "",
        gender: "male",
        bloc: "vl_langzu",
        hp: 1,
        intro: "",
        drawer: "钫酸酱",
        coder: "钫酸酱",
        designer: "钫酸酱",
        writer: "钫酸酱",
        prefix: "",
        skills: ["vl_kulun_dirt_zw", "vl_kulun_dirt_zj"],
        addition: ['unseen'],
        pack: "Valyana",
        vp: 0,
        sort: "kela",
        rank: "epic",
    },
    vl_kulun_thunder: {
        enable: true,
        name: "库伦·雷电",
        title: "",
        gender: "male",
        bloc: "vl_langzu",
        hp: 1,
        intro: "",
        drawer: "钫酸酱",
        coder: "钫酸酱",
        designer: "钫酸酱",
        writer: "钫酸酱",
        prefix: "",
        skills: ["vl_kulun_thunder_yl", "vl_kulun_thunder_dl"],
        addition: ['unseen'],
        pack: "Valyana",
        vp: 0,
        sort: "jianaier",
        rank: "epic",
    },
    vl_kulun: {
        enable: true,
        name: "库伦",
        title: "元素引导者",
        gender: "male",
        bloc: "vl_langzu",
        hp: 1,
        intro: "&nbsp&nbsp&nbsp&nbsp库伦，出生于克拉王国，具有卓越的魔法天赋。在魔法学院的学习年月里，库伦积累了深厚的魔法知识，并发明了一根号称“扭称”的特殊法杖，能够将两种元素力量注入其中并维持其平衡。\n            <br>&nbsp&nbsp&nbsp&nbsp后来，他偶然发现了一个神秘的泉眼，这个泉眼融合了各种元素的能量，释放着无尽的魔法力量。库伦决定将泉眼视为自己的研究对象，但随着时间的推移，他渐渐被泉眼中的力量所吸引，着魔般地渴望着占有它。他利用“扭称”进行危险的实验，试图掌握泉眼的能量。\n            <br>&nbsp&nbsp&nbsp&nbsp库伦不知道的是，当所有元素被禁锢于同一容器时，它们会相互碰撞和交织，引发了强烈的爆炸。这场爆炸不仅波及了数千人，炸毁了整个魔法师塔，还导致了一场名为“魔力大崩溃”的魔法浩劫，世界的魔力等级骤降，所有人都无法再从世界的魔网中吸取超过十阶的能量。\n            <br>&nbsp&nbsp&nbsp&nbsp魔法，曾经是克拉文明的核心，从此陷入了低谷。而库伦的研究和冒险，无论是对于魔法学的贡献还是对于后世的警示，都将被永远地铭记在瓦尔亚那的历史中。",
        drawer: "钫酸酱",
        coder: "钫酸酱",
        designer: "钫酸酱、fox⑧",
        writer: "钫酸酱",
        prefix: "",
        skills: ["vl_kulun_gz", "vl_kulun_fs", "vl_kulun_zn", "vl_kulun_skillfilter"],
        addition: [],
        pack: "Valyana",
        vp: 0,
        sort: "kela",
        rank: "epic",
    },
    vl_shark: {
        enable: true,
        name: "鲨克",
        title: "其人之道",
        gender: "male",
        bloc: "vl_haizu",
        hp: 4,
        intro: "沙克，来自人鱼之海的深部，其拥有一颗宝贵的珍珠，约一桅长，此珍珠能够映射出任意人的样貌，并使得拥有者获得相同的能力，据传其和凌月之球的制作者属于同一人。",
        prefix: "",
        skills: ["vl_shark_yz"],
        addition: [],
        pack: "Valyana",
        vp: 0,
        sort: "renyu",
        rank: "rare",
    },
    vl_blam: {
        enable: true,
        name: "布兰",
        title: "如入幻境之刃",
        gender: "male",
        bloc: "vl_langzu",
        hp: 4,
        intro: "布兰，希尔特黑帮的二把手，也是旧剑术名家希诺一脉的后裔。希诺曾以“血剑共鸣”的秘法闻名，能够让自身血液与剑刃产生回响，使出剑者在短时间内进入近乎人剑合一的状态。布兰幼年时被黑帮首领收养，在街巷斗争中长大，却始终以贵族般的仪态要求自己；他身上的军礼外套和金饰并非虚张声势，而是希诺家族旧日荣光的残片。<br>据传，布兰曾于科里科特一带与数名剑士交锋，只用一柄被血浸透的短剑便压制全场。此后他成为希尔特黑帮的二把手，负责处理那些无法靠谈判解决的争端。布兰发动剑祭时，会主动舍弃护身之物，将一切防备都换成进攻的锋芒；被他选中的敌人往往会在幻境般的剑影中失去还手余地，只能听见血液与剑刃同时震鸣。",
        prefix: "",
        skills: ["vl_blame_jj"],
        addition: [],
        pack: "Valyana",
        vp: 0,
        sort: "kela",
        rank: "legend",
    },
    vl_bwol: {
        enable: true,
        name: "鲍尔",
        title: "爆炸艺术家",
        gender: "male",
        bloc: "vl_baozu",
        hp: 3,
        intro: "鲍尔，出身于迦奈尔联邦科马工业区的爆破学研究员。幼年时，他曾在一次矿用炸药事故中失去嗅觉，也因此终年戴着改装过的防毒面具。旁人只看见他白袍、试管和冷淡的眼神，却很少知道他最早研究爆炸并非为了破坏，而是为了让矿井、隧道和战场障碍在可控范围内被精准拆除。<br>进入联邦军械院后，鲍尔提出过一套“等量失衡”理论：只要让目标携带的资源与压力达到相同刻度，再投入微小火星，就能引发最节省材料的连锁崩解。这套理论曾被军方用于攻城火药，也让鲍尔意识到自己的成果正在离救援越来越远。后来他离开军械院，带着几箱未公开的爆剂配方独自行动。鲍尔称爆炸为艺术，并不是因为他迷恋火光，而是因为真正优秀的爆破从不浪费一寸裂纹。",
        prefix: "",
        skills: ["vl_bwol_mb", "vl_bwol_zj"],
        addition: [],
        pack: "Valyana",
        vp: 0,
        sort: "jianaier",
        rank: "epic",
    },
    vl_charlin: {
        enable: true,
        name: "查尔林",
        title: "指鹿为马",
        gender: "male",
        bloc: "vl_luzu",
        hp: 3,
        intro: "查尔林，从小就是众人眼中的天之骄子，诞生于克拉贵族家庭的他从小就受到了极其严苛和专业的教导，而他也对哲学和修辞学尤为喜爱，并跟从多戈进行学习。觉醒了精神系能力的他，能够让任何人在短时间内相信他所说的一切，他也因此能力被克拉的老国王选为了祭祀。在老国王死后，他则负责太子盖尔德鲁的伴读和老师，而盖尔德鲁也对他极其信赖。但是不要被他的外表所迷惑，看似亲和的外表下隐藏的却是残忍而嗜血的内心，他为了达成自己的目的不择手段。有传言称国王盖尔德鲁后期的昏聩和位极人臣的查尔林的诱导脱不开关系，另有传言称其害死了他的老师。",
        prefix: "",
        skills: ["vl_charlin_fs", "vl_charlin_qs"],
        addition: [],
        pack: "Valyana",
        vp: 0,
        sort: "kela",
        rank: "legend",
    },
    vl_crow: {
        enable: true,
        name: "克劳",
        title: "智谋慧者",
        gender: "male",
        bloc: "vl_yizu",
        hp: 3,
        intro: "克劳，万灵之森北缘鸦族贤者，也是少数能解读月相与鸟群轨迹的占候师。鸦族长久以来被许多城邦视作不祥之兆，克劳少年时便因紫色异瞳和沉默寡言遭到驱逐，只能在夜间随乌鸦迁徙，学习从风向、星位和尸骸旁留下的细节里判断灾祸来处。<br>成年后的克劳回到森林边境，建立了一座只在满月时开放的观星塔。他不喜欢直接介入争斗，更擅长提前记录那些足以改变局面的术式、谎言与计策。许多谋士以为自己藏得足够深，却不知道克劳早已在月下看见了他们的影子。对他而言，智慧不是把所有人推向胜利，而是在灾厄抵达前，先知道哪一枚羽毛会落下。",
        prefix: "",
        skills: ["vl_crow_my", "vl_crow_mc", "vl_crow_td"],
        addition: [],
        pack: "Valyana",
        vp: 0,
        sort: "wanling",
        rank: "epic",
    },
    vl_delta: {
        enable: true,
        name: "德尔塔",
        title: "破瞬之斩",
        gender: "male",
        bloc: "vl_quanzu",
        hp: 4,
        intro: "德尔塔，迦奈尔联邦旧城区出身的犬族佣兵，曾是地下格斗场中最年轻的刀手。少年时期的他没有接受过完整军校训练，只在码头、赌馆和废弃工厂之间学会了如何用最短的动作结束冲突。后来一位退役工程师收留了他，教他用算尺、齿轮和弹道图推算距离；德尔塔这才发现，自己赖以生存的本能也能被拆解成精确的角度与时机。<br>他的短刃术因此变得异常危险。交手前，德尔塔会先在脑中完成一连串近乎疯狂的推演，一旦找到那条最窄的路径，便以身体作为代价强行穿过。许多敌人只看见红影一闪，护具、阵形与退路就已被同时撕开。德尔塔并不崇拜莽勇，他只是相信瞬间的胜负从来不是运气，而是计算到极致后的斩击。",
        prefix: "",
        skills: ["vl_delta_sy", "vl_delta_sz"],
        addition: [],
        pack: "Valyana",
        vp: 0,
        sort: "jianaier",
        rank: "legend",
    },
    vl_derk: {
        enable: true,
        name: "德克",
        title: "黯影随行",
        gender: "male",
        bloc: "vl_maozu",
        hp: 4,
        intro: "德克，迦奈尔联邦杰出的数学家，以其群论理论为迦奈尔的工程和社会建设提供了理论指导，并在国防领域推动了禁魔子弹的空气动力学设计，为联邦的安全和国防事业作出了卓越贡献。他是A.W.纪元之后最伟大的数学家之一。",
        prefix: "",
        skills: ["vl_derk_ly", "vl_derk_liuyan"],
        addition: [],
        pack: "Valyana",
        vp: 0,
        sort: "jianaier",
        rank: "junk",
    },
    vl_dier: {
        enable: true,
        name: "戴尔",
        title: "守龙之护",
        gender: "male",
        bloc: "vl_longzu",
        hp: 4,
        intro: "戴尔，龙之谷赤翼氏族的守宝人。赤翼氏族世代看守古龙遗留的宝库，族中幼龙在成年前必须学会分辨真正的财富与诱饵。戴尔年少时性情骄纵，曾在一次巡守中放走伪装成商人的盗宝者，导致一枚夕炎龙晶流落谷外。为追回龙晶，他独自离开巢穴，连续追踪三年，最终在黑市拍卖场前夺回失物，却也因此失去了一截翼骨。<br>那次经历让戴尔不再把守护视作单纯的力量展示。他习惯展开双翼挡在宝库与同伴之前，以龙族的高傲承受第一轮冲击，再从来犯者手中夺回本不属于他们的东西。戴尔并不吝惜宝物，龙之谷也并非拒绝外人；但在他看来，未经允许伸出的手，必须先学会被夕炎灼痛。",
        prefix: "",
        skills: ["vl_dier_sb", "vl_dier_ly", "vl_dier_xy"],
        addition: [],
        pack: "Valyana",
        vp: 0,
        sort: "dragongu",
        rank: "epic",
    },
    vl_dolina: {
        enable: true,
        name: "多林",
        title: "分海噬浪",
        gender: "male",
        bloc: "vl_langzu",
        hp: 3,
        intro: "多林，出生在人鱼之海北岸的狼族巡潮官。沿海村镇常年受潮汐、海盗与海兽威胁，巡潮官既要观测海况，也要在灾难来临时组织撤离。多林少年时曾随父亲出海，却在一场异常退潮后亲眼看见整片海湾被巨浪吞没；幸存后，他开始研究浪势、风压与水下魔力的关系，逐渐掌握了将海潮引入自身意志的术法。<br>多林并不喜欢炫耀力量。他总穿着印有狼纹的旧外套，在港口、灯塔和海堤之间巡行，记录每一种可能伤人的浪。真正战斗时，他会先以威仪压住来犯者的锋芒，再把记忆中的风暴逐一释放。传言多林曾独自站在海堤尽头，将一场足以毁掉三座港镇的浪潮分开；从那以后，沿岸的人们便称他为“噬浪者”。",
        prefix: "",
        skills: ["vl_dolina_wy", "vl_dolina_sl", "vl_dolina_qj"],
        addition: [],
        pack: "Valyana",
        vp: 0,
        sort: "renyu",
        rank: "common",
    },
    vl_dragon: {
        enable: true,
        name: "德拉贡",
        title: "黑焰之龙",
        gender: "male",
        bloc: "vl_longzu",
        hp: 4,
        intro: "德拉贡，龙之谷白鳞龙裔，生于黑焰火山脚下的禁守氏族。黑焰并非普通火焰，而是古龙魂魄燃尽后残留的怨火，能够灼伤生命本源。德拉贡幼年时在火山裂隙中救出一名误入禁地的旅人，却被黑焰侵入血脉；自那以后，他的鳞片转为冷白，掌心也会浮现幽蓝色的火痕。<br>氏族长老曾试图封印他的力量，但德拉贡选择反向吞噬黑焰，将怨火炼成自己的魂怒。他外表张扬，言辞锋利，却极少主动伤及无辜，因为他比任何人都清楚那种火焰会带走什么。每当德拉贡出现在战场，敌人看见的往往不是烈焰，而是一枚枚被黑火烙下的罪证。若有人仍要靠近龙之谷的禁地，他便会让对方明白，古龙的怒意从未真正熄灭。",
        prefix: "",
        skills: ["vl_dragon_hy", "vl_dragon_ly", "vl_dragon_hn"],
        addition: [],
        pack: "Valyana",
        vp: 0,
        sort: "dragongu",
        rank: "epic",
    },
    vl_edmon: {
        enable: true,
        name: "埃德蒙",
        title: "以死护全",
        gender: "male",
        bloc: "vl_langzu",
        hp: 4,
        intro: "埃德蒙，克拉北境旧军团的狼族盾卫。盖尔德鲁统治后期，北境频繁征兵，埃德蒙原本只是随军铁匠之子，却在一次撤退中捡起阵亡骑士的圆盾，独自挡住了追兵射向难民队伍的箭雨。那面盾后来被修补了十七次，盾心的金色星纹也成了北境民兵口中“归阵”的标志。<br>埃德蒙从不认为自己擅长进攻。他真正可怕的地方，是能把敌人的杀意一层层接到自己身前，再在最恰当的时刻将其全部偿还。战争结束后，他拒绝进入王城任职，继续在边境村镇之间巡防，尤其照看那些因战乱失去亲人的孩子。有人说他过于固执，埃德蒙却只回答：盾牌若不先站在弱者前面，便只是一块昂贵的铁。",
        prefix: "",
        skills: ["vl_edmond_jz", "vl_edmond_jj"],
        addition: [],
        pack: "Valyana",
        vp: 0,
        sort: "kela",
        rank: "common",
    },
    vl_francium: {
        enable: true,
        name: "弗兰西亚",
        title: "双舞翩翩",
        gender: "male",
        bloc: "vl_guaiwu",
        hp: 3,
        intro: "弗兰西亚，关于他的身份，神学者至今没有统一结论。有人称他是晨昏交界处诞生的双翼怪物，也有人认为他曾是侍奉光明与黑暗两位神祇的祭司，在一次失败的仪式中被两种神性同时撕裂。现存壁画里，他总以白狼、黑翼和覆面的姿态出现，一半像宣告黎明的使者，一半像吞没余晖的阴影。<br>弗兰西亚很少在同一个地方停留太久。清晨见过他的人，说他会以圣咏安抚伤者，让濒死者重新听见呼吸；黄昏见过他的人，则记得他将手中一切化作暗涌般的杀意，毫不犹豫地斩断敌人的退路。弗兰西亚并不解释自己究竟属于哪一侧，因为晨与昏本就是同一日的两端。凡人称其为怪物，信徒称其为神迹，而他只在明灭之间继续前行。",
        prefix: "",
        skills: ["vl_francium_ch", "vl_francium_sx", "vl_francium_yl", "vl_francium_mm"],
        addition: [],
        pack: "Valyana",
        vp: 0,
        sort: "shoushen",
        rank: "legend",
    },
    vl_gairtelu: {
        enable: true,
        name: "盖尔德鲁",
        title: "暴戾君王",
        gender: "male",
        bloc: "vl_huzu",
        hp: 4,
        intro: "盖尔德鲁，克拉的王室成员，作为皇室血脉的他在10岁时就成为了克拉的国王。但是作为国王的他却耽于享乐，27岁时下令建造“圣灵塔”妄图与永恒之神法斯建立连接以获得无尽的寿命。在他的任期内，国民的赋税甚至达到了恐怖1/3。后来北境爆发被称为“正裁战争”的起义将其王朝推翻，哈拉尔接替他成为国王。而盖尔德鲁从此下落不明，民间有传言称其逃到了矮人边境，也有说法称其被哈拉尔秘密处决。",
        prefix: "",
        skills: ["vl_gairtelu_sf", "vl_gairtelu_zs", "vl_gairtelu_aq"],
        addition: ["zhu"],
        pack: "Valyana",
        vp: 0,
        sort: "kela",
        rank: "epic",
    },
    vl_harald: {
        enable: true,
        name: "哈拉尔",
        title: "兽族王者",
        gender: "male",
        bloc: "vl_shizu",
        hp: 4,
        intro: "哈拉尔，生于克拉北境的贫苦农民家庭，由于国王盖尔德鲁的残暴统治和严苛税赋，哈拉尔所在的伊斯曼省份发动起义，而哈拉尔因为其的卓越军事天赋被选为领袖并成功推翻了原国王的残暴统治，哈拉尔上任后立刻开始着手修复前任国王造成的经济破坏，成功使得克拉从动荡中稳定下来。由于他的卓越功勋，受到他恩惠的人们赞颂他为“圣明王”。",
        prefix: "",
        skills: ["vl_harald_fy", "vl_harald_zb"],
        addition: ['zhu'],
        pack: "Valyana",
        vp: 0,
        sort: "kela",
        rank: "legend",
    },
    vl_hynea: {
        enable: true,
        name: "哈尼亚",
        title: "登峰造极",
        gender: "male",
        bloc: "vl_quanzu",
        hp: 4,
        intro: "哈尼亚，迦奈尔联邦地下搏击场出身的鬣犬族斗士。与讲究章法的拳手不同，他最早学会的是在酒馆、巷口和铁笼里活下来：被击倒就喝一口烈酒止痛，失去平衡就用牙齿和膝盖重新抢回距离。少年时期的哈尼亚因屡次挑战强者而声名狼藉，却也在一次次濒死中磨出了近乎野兽般的韧性。<br>后来，一名流浪修士看中他的执着，教他把醉意、疼痛和冲动压进固定的呼吸节奏。哈尼亚由此踏上所谓“登峰”的修行：每越过一道险境，他对酒意与身体的掌控就更进一步；等到极限被彻底踩碎，他的狂辩与笑声便会成为新的武器。哈尼亚不在乎别人说他粗野，他只相信真正的高手必须先敢把自己推到悬崖边，再从那里走回来。",
        prefix: "",
        skills: ["vl_hynea_cg", "vl_hynea_ds", "vl_hynea_rx"],
        addition: [],
        pack: "Valyana",
        vp: 0,
        sort: "jianaier",
        rank: "rare",
    },
    vl_jgby: {
        enable: true,
        name: "吉岡邦彦",
        title: "狂炎灼冰",
        gender: "male",
        bloc: "vl_langzu",
        hp: 4,
        intro: "吉岡邦彦，来自远东群岛的狼族剑士，曾在雪山道场中修习冰息剑术，又在火山边境的战事中领悟炎流。两种截然相反的力量在他身上并未互相抵消，反而像两柄并行的刀，一柄封住退路，一柄逼出破绽。<br>他不常谈论自己的故乡，只随身携带一枚被火烧裂的冰玉。有人见过他在暴雪中点燃刀锋，也有人见过他以烈焰冻结敌人的血气。吉岡邦彦相信真正的武技不该拘泥于属性之分，冰与火都只是意志抵达目标的路径。",
        prefix: "",
        skills: ["vl_jbgy_qx", "vl_jbgy_ze"],
        addition: [],
        pack: "Valyana",
        vp: 0,
        sort: "youdangzhe",
        rank: "epic",
    },
    vl_jiejie: {
        enable: true,
        name: "檞界",
        title: "饮血剑法",
        gender: "male",
        bloc: "vl_langzu",
        hp: 3,
        intro: "檞界，生活在克拉王城外郊，学习木系魔法与剑术，曾与米亚切磋剑术但是惜败。檞界的剑据说时来自深渊的矿石制成，因此天然带有魔法亲和力。据说此矿石若与禁魔石混合点燃，便会发生剧烈的爆炸，但是否有此事尚未可知。",
        prefix: "",
        skills: ["vl_jiejie_zr", "vl_jiejie_zf", "vl_jiejie_my"],
        addition: [],
        pack: "Valyana",
        vp: 0,
        sort: "kela",
        rank: "common",
    },
    vl_kasaers: {
        enable: true,
        name: "卡萨尔斯",
        title: "狂狼怒吼",
        gender: "male",
        bloc: "vl_langzu",
        hp: 4,
        intro: "卡萨尔斯，北境荒原上长大的狼族战士，少年时期便以惊人的肺力与战吼闻名。荒原部族相信吼声能够唤醒血脉中的古狼意志，而卡萨尔斯正是少数能让整支队伍随其咆哮一同冲锋的人。<br>他并非单纯鲁莽的斗士。卡萨尔斯习惯用近乎疯狂的攻势撕开阵线，再以震耳欲聋的怒吼压垮敌人的胆气。与他并肩作战的人会觉得脚下大地都在回应他的声音；而站在他面前的人，往往在第一声狼嚎响起时便已失去退路。",
        prefix: "",
        skills: ["vl_kasers_yz", "vl_kasers_kb"],
        addition: [],
        pack: "Valyana",
        vp: 0,
        sort: "kela",
        rank: "legend",
    },
    vl_ken: {
        enable: true,
        name: "科恩",
        title: "机器之心",
        gender: "male",
        bloc: "vl_jiqi",
        hp: 4,
        intro: "科恩，迦奈尔联邦早期机械生命实验的幸存者。与普通战争机器不同，他的核心中保留了完整的情绪回路，因此既能像士兵一样执行指令，也会像真正的生命一样迟疑、愤怒与怀念。创造者称这枚核心为“机器之心”，但科恩更愿意把它称作自己的灵魂。<br>他曾被编入前线重装部队，负责在禁魔矿脉附近执行高危任务。多次战斗后，科恩开始质疑机械被制造出来是否只能服从命令。如今他游走在工坊、战场与废弃机库之间，寻找同类，也寻找能够证明自己并非兵器的答案。",
        prefix: "",
        skills: ["vl_ken_jj", "vl_ken_yn", "vl_ken_pb"],
        addition: [],
        pack: "Valyana",
        vp: 0,
        sort: "jixiezaowu",
        rank: "epic",
    },
    vl_kersm: {
        enable: true,
        name: "科尔森",
        title: "盟国之约",
        gender: "male",
        bloc: "vl_baozu",
        hp: 4,
        intro: "科尔森，「流亡者」佣兵团的经理，与「赏金公会」进行任务对接。虽然科尔森看起来十分和善，但所有佣兵团的人都知道，科尔森是最不能惹的人。其特殊能力未知，但据说十分强力，能够与十级法师平手。",
        prefix: "",
        skills: ["vl_kersm_my", "vl_kersm_jq"],
        addition: [],
        pack: "Valyana",
        vp: 0,
        sort: "yongbing",
        rank: "epic",
    },
    vl_kert: {
        enable: true,
        name: "柯尔特",
        title: "掠魂动魄",
        gender: "male",
        bloc: "vl_quanzu",
        hp: 4,
        intro: "柯尔特，「流亡者」佣兵团的最年轻的成员，由于其对枪械十分精通，因此其在火力掩护的方面有极其重要的作用。他也被团长所赏识，现在小队里都默认他将是下一任团长。柯尔特的身体曾被迦奈尔联邦改造，因此其能够适应各种极端的环境。其最出名的一次任务就是受到神秘的精灵族委托，去寻找能够复活生命之树的元素之泉。",
        prefix: "",
        skills: ["vl_kert_lp", "vl_kert_jl"],
        addition: [],
        pack: "Valyana",
        vp: 0,
        sort: "yongbing",
        rank: "rare",
    },
    vl_kesaya: {
        enable: true,
        name: "克萨亚",
        title: "无影无踪",
        gender: "male",
        bloc: "vl_huzu",
        hp: 2,
        intro: "克萨亚，暗影佣兵团个人能力最强的成员，但是行事莽撞，需要其他人的指挥。克萨亚十分仰慕团长斯克瑞，其卧室内都是斯克瑞的照片和通缉令（据雷恩斯所说）。克萨亚能够通过自己的血液将自己融入暗影，但是对自己的消耗过大，因此斯克瑞总是安排他做一些无关紧要的任务。",
        prefix: "",
        skills: ["vl_kesaya_zw", "vl_kesaya_wy", "vl_kesaya_ax"],
        addition: [],
        pack: "Valyana",
        vp: 0,
        sort: "franying",
        rank: "legend",
    },
    vl_keste: {
        enable: true,
        name: "科斯特",
        title: "常胜将军",
        gender: "male",
        bloc: "vl_langzu",
        hp: 4,
        intro: "科斯特，迦奈尔联邦最年轻也是最年少有为的将军，曾经在与矮人族的战争——“矮人之心争夺战”中大获全胜，歼敌数万。其主导与矮人族签下的《斯兰条约》为迦奈尔联邦的贸易事业奠定了发展基础。因此，这位将军也被成为“尼拉特”将军——即矮人语中的“恶魔”。",
        prefix: "",
        skills: ["vl_keste_yg", "vl_keste_wp"],
        addition: [],
        pack: "Valyana",
        vp: 0,
        sort: "jianaier",
        rank: "epic",
    },
    vl_keya: {
        enable: true,
        name: "科亚",
        title: "佣兵团长",
        gender: "male",
        bloc: "vl_langzu",
        hp: 4,
        intro: "科亚，「流亡者」佣兵团的现任团长，擅长于掩护队友和压制对手。科亚曾经是迦奈尔联邦的逃犯，后来进入赏金工会，受到会长的赏识，通过政治庇护免除了他的罪行。因此其现在正在为赏金工会工作。",
        prefix: "",
        skills: ["vl_kaye_jy", "vl_kaye_yj"],
        addition: ["zhu"],
        pack: "Valyana",
        vp: 0,
        sort: "yongbing",
        rank: "rare",
    },
    vl_klier: {
        enable: true,
        name: "克莱尔",
        title: "坚实后盾",
        gender: "male",
        bloc: "vl_huzu",
        hp: 3,
        intro: "克莱尔，「流亡者」的成员之一，也许对于其他成员来说，克莱尔的能力并不是最为突出的，但是他确实是行事最为稳重的那个。克莱尔虽然看起来大大咧咧，但是在所有任务中，他均表现出了极其可靠的能力和细心，属于是粗中有细。据柯尔特所言，克莱尔目前似乎已经找到了自己的伴侣，而且似乎有打算退出佣兵团。",
        prefix: "",
        skills: ["vl_kelaier_dh", "vl_kelaier_ty"],
        addition: [],
        pack: "Valyana",
        vp: 0,
        sort: "yongbing",
        rank: "rare",
    },
    vl_klif: {
        enable: true,
        name: "克里夫",
        title: "追猎者",
        gender: "male",
        bloc: "vl_jiqi",
        hp: 3,
        intro: "克里夫，迦奈尔联邦制造的侦猎型机械生命，原本被设计用于追踪逃犯、潜入敌后与清除失控造物。他的感知系统能从脚印、热量、金属碎屑甚至残留魔力中拼出目标的行踪，因此很少有人能真正摆脱他的追猎。<br>在一次边境任务中，克里夫没有按命令处决已经投降的目标，而是将其交给当地法庭审判。那之后，他从军用编号中脱离，开始以自己的判断选择猎物。他依旧沉默、精准、冷静，只是如今每一次锁定目标前，都会先确认自己追逐的究竟是命令，还是罪责。",
        prefix: "",
        skills: ["vl_krif_zl", "vl_krif_lj"],
        addition: [],
        pack: "Valyana",
        vp: 0,
        sort: "jixiezaowu",
        rank: "rare",
    },
    vl_laays: {
        enable: true,
        name: "拉亚斯",
        title: "镣铐游荡者",
        gender: "male",
        bloc: "vl_langzu",
        hp: 4,
        intro: "“像这样四处游荡，又过了多久呢？”拉亚斯的话语回荡在旷野上。自从那场人类与精灵的大战以人类的完全胜利为结局，拉亚斯也不知道自己游荡多久了。他是当年参加过此次战争的兽人族战士，后牺牲于战火之中。也许是生命树被毁的缘故，拉亚斯重新得到肉体复活。",
        prefix: "",
        skills: ["vl_laays_cs"],
        addition: [],
        pack: "Valyana",
        vp: 0,
        sort: "youdangzhe",
        rank: "junk",
    },
    vl_lamas: {
        enable: true,
        name: "拉马斯",
        title: "战技如神",
        gender: "male",
        bloc: "vl_shizu",
        hp: 4,
        intro: "拉马斯，克拉旧军学院出身的狮族武师，精通长兵、短刃、盾击与徒手格斗。年轻时的他曾连续挑战七座军营的教官，未尝一败，因此被士兵们半是敬畏半是调侃地称作“战技如神”。<br>拉马斯并不相信所谓天生强者。他认为所有战斗都能被拆解为距离、节奏、角度与代价，只要看清这些，任何华丽招式都不过是可以被破解的结构。后来他离开军学院，四处寻找足够危险的战场，以继续验证自己对武艺的理解。",
        prefix: "",
        skills: ["vl_lamas_zj"],
        addition: [],
        pack: "Valyana",
        vp: 0,
        sort: "kela",
        rank: "rare",
    },
    vl_lens: {
        enable: true,
        name: "雷恩斯",
        title: "元素法师",
        gender: "male",
        bloc: "vl_longzu",
        hp: 3,
        intro: "雷恩斯，「暗影」刺杀队的队员之一，作为罕见的龙族，天生能够亲和各种魔法元素。其中，雷恩斯对雷和火元素的亲和最为突出。虽然其作为法师却加入了刺客佣兵团的原因或未可知，但是其出色的能力还是为整个小队带来了极大的方便。",
        prefix: "",
        skills: ["vl_lens_yl", "vl_lens_rj"],
        addition: [],
        pack: "Valyana",
        vp: 0,
        sort: "franying",
        rank: "rare",
    },
    vl_lint: {
        enable: true,
        name: "林特",
        title: "制衡掣肘",
        gender: "male",
        bloc: "vl_niuzu",
        hp: 4,
        intro: "林特，出身于商路要冲的牛族调停人。那片地区常年夹在佣兵团、商会与地方贵族之间，任何一次冲突都可能牵连整条贸易线。林特少年时便跟随长辈处理赔款、护送与地界争端，逐渐学会用最小的动作牵制最大的局势。<br>他不喜欢亲自站到冲突中心，却总能让双方在最关键的时刻发现自己受制于人。林特相信力量并不只存在于刀剑上，契约、债务、人情与恐惧同样可以成为锁链。只要锁链足够精准，再强硬的人也会被迫停下脚步。",
        prefix: "",
        skills: ["vl_lint_nd"],
        addition: [],
        pack: "Valyana",
        vp: 0,
        sort: "kela",
        rank: "rare",
    },
    vl_linyan: {
        enable: true,
        name: "林&炎",
        title: "双人共舞",
        gender: "male",
        bloc: "vl_langzu",
        hp: 3,
        intro: "林和炎是一对双胞胎，自幼时被父母遗弃，后被米兰寺收养。他们从小就生活于龙之谷外围的米兰寺中，与寺庙的主持相依为命。后来霍恩为了夺取寺庙中的宝物，设计毒杀了住持，而林与炎因外出而逃过一劫。",
        prefix: "",
        skills: ["vl_linyan_kr", "vl_linyan_ys"],
        addition: [],
        pack: "Valyana",
        vp: 0,
        sort: "milan",
        rank: "rare",
    },
    vl_liona: {
        enable: true,
        name: "里欧纳",
        title: "整军待战",
        gender: "male",
        bloc: "vl_shizu",
        hp: "4/5",
        intro: "里欧那，生活于兽人王国克拉的贵族家庭，从小就被作为一位战士培养。二十一岁时，在一次前往坷拉进行战斗的过程中，意外拯救了坷拉的公主，后二人暗生情愫。后来在一次战斗中下落不明。",
        prefix: "",
        skills: ["vl_liona_hz", "vl_liona_zz"],
        addition: ["zhu"],
        pack: "Valyana",
        vp: 0,
        sort: "kela",
        rank: "epic",
    },
    vl_liuqing: {
        enable: true,
        name: "流青",
        title: "兵无常饰",
        gender: "male",
        bloc: "vl_huzu",
        hp: 3,
        intro: "流青，迦奈尔联邦边军中的虎族奇兵，擅长伪装、换装与临阵变阵。他曾在一次补给线被截断的战役中带领残部混入敌营，靠改换旗帜与口令连续误导三支追兵，最终把整支队伍完整带回。<br>流青不把军服、阵旗或身份看得过重。在他看来，战场上的一切标识都只是暂时借用的工具，真正可靠的只有判断与行动。他常说兵无常形，人也不该被一种样子困住；当敌人终于认出他时，局势通常已经被他悄悄改写。",
        prefix: "",
        skills: ["vl_liuqing_yf", "vl_liuqing_lz"],
        addition: [],
        pack: "Valyana",
        vp: 0,
        sort: "jianaier",
        rank: "legend",
    },
    vl_liya: {
        enable: true,
        name: "莉亚",
        title: "动运千机",
        gender: "female",
        bloc: "vl_hulizu",
        hp: 3,
        intro: "莉亚生于兽人王国中部的商业中心——恩特城，是兽人王国国王哈拉尔的独女。作为贵族女子的她，自小时候便被灌输各种各样的贵族礼仪，但她的生性不羁，时时让自己的父亲紧张。她在16岁时，曾收到过哈拉尔赠送的重装机车，是她最喜欢的生日礼物。",
        prefix: "",
        skills: ["vl_liya_sz", "vl_liya_sj", "vl_liya_yy"],
        addition: [],
        pack: "Valyana",
        vp: 0,
        sort: "kela",
        rank: "junk",
    },
    vl_lucifer: {
        enable: true,
        name: "路西法",
        title: "兽语部首",
        gender: "male",
        bloc: "vl_langzu",
        hp: 3,
        intro: "路西法，目前为居住在矮人之心洞穴附近的兽人部落首领。其部落信仰生命之神——“特拉克斯”，并获得了其传承的特殊能力。该能力使得其部落的勇士能够与动物沟通，甚至训练动物成为伙伴。拥有这种特殊能力的人在《瓦尔亚那》百科中称为“兽语者”。",
        prefix: "",
        skills: ["vl_lucifer_cc", "vl_lucifer_xz"],
        addition: [],
        pack: "Valyana",
        vp: 0,
        sort: "airenzhixin",
        rank: "rare",
    },
    vl_lusiya: {
        enable: true,
        name: "卢西亚",
        title: "天慧之才",
        gender: "male",
        bloc: "vl_longzu",
        hp: 3,
        intro: "卢西亚，曾就读于人类王国「魔法学院」，与沃里克为好友。其智力超群，并且在学习魔法方面有着很高的造诣。在魔法学院的时期他曾经创立过自己的魔法研究所「时空之门」，并在某双系法师的帮助下，还原了时空魔法的原理。由此卢西亚还未毕业的时候便已经获得了学院授予的最高荣誉。",
        prefix: "",
        skills: ["vl_luciya_yc", "vl_luciya_xl", "vl_luciya_hl"],
        addition: [],
        pack: "Valyana",
        vp: 0,
        sort: "xueyuan",
        rank: "epic",
    },
    vl_mala: {
        enable: true,
        name: "马拉尔",
        title: "龙裔之王",
        gender: "male",
        bloc: "vl_longzu",
        hp: 4,
        intro: "马拉尔，龙之谷古老王族的后裔，被部分龙族氏族尊称为“龙裔之王”。他的血脉中继承着古龙残留的威压，也背负着调停各氏族纷争的责任。龙族向来高傲而分散，能让他们暂时低头听令，本身便意味着非同寻常的力量。<br>马拉尔并不急于登上任何王座。他更常出现在边境、祭坛与古龙遗迹之间，追查那些足以动摇龙之谷根基的隐患。对他而言，王不是坐在高处接受臣服的人，而是在灾厄真正降临前，先一步站到所有龙裔之前的人。",
        prefix: "",
        skills: ["vl_mala_ly", "vl_mala_ht"],
        addition: [],
        pack: "Valyana",
        vp: 0,
        sort: "shoushen",
        rank: "junk",
    },
    vl_markn: {
        enable: true,
        name: "马克恩",
        title: "洞中窾会",
        gender: "male",
        bloc: "vl_langzu",
        hp: 3,
        intro: "马克恩，狼族学者兼游历术士，长期研究地下遗迹与古代机关。他最擅长的并不是强行破门，而是在石壁缝隙、风声回响和机关磨损中寻找真正的入口。同行者常说，只要马克恩停下来侧耳倾听，附近多半藏着一段被遗忘的历史。<br>他曾在矮人旧矿道深处发现一处无名会厅，墙上刻满早已失传的会议记录。自那以后，马克恩开始相信遗迹本身也会保留记忆，而探索者要做的不是夺走宝物，而是读懂沉默。若有人企图粗暴破坏古址，他往往会先一步让对方迷失在自己布下的岔路中。",
        prefix: "",
        skills: ["vl_markn_yz", "vl_markn_yc"],
        addition: [],
        pack: "Valyana",
        vp: 0,
        sort: "airenzhixin",
        rank: "epic",
    },
    vl_mierk: {
        enable: true,
        name: "米尔克",
        title: "力争神辩",
        gender: "male",
        bloc: "vl_langzu",
        hp: 3,
        intro: "米尔克，米勒的哥哥，生于克拉贵族家庭的他从小就跟随师傅查尔林学习修辞学。后来因为与其师傅的理念不同而分道扬镳，离开了王城。也正因此躲过了后来的政治风波。",
        prefix: "",
        skills: ["vl_mierk_jc", "vl_mierk_fm", "vl_mierk_jingcai"],
        addition: [],
        pack: "Valyana",
        vp: 0,
        sort: "kela",
        rank: "epic",
    },
    vl_milis: {
        enable: true,
        name: "弥斯利",
        title: "铸刃千口",
        gender: "male",
        bloc: "vl_xiongzu",
        hp: 3,
        intro: "弥斯利，熊族铸兵匠，曾在矮人之心外围的熔炉城学习锻造。他不满足于只打造一柄名器，而是执着于让每一种材料、每一种持握方式都找到最适合的锋刃。传闻他工坊中悬挂着上千把半成品，每一把都记录着一次失败或一次突破。<br>弥斯利上战场并非为了证明武力，而是为了亲眼确认自己的作品在真正厮杀中的表现。他会记下刀刃崩口的角度、枪尖弯折的原因，也会在战后把敌我双方遗落的兵器全部带回重铸。对他而言，铸刃不是制造杀戮，而是让使用者在生死之间多一分选择。",
        prefix: "",
        skills: ["vl_mislee_jx", "vl_mislee_tj", "vl_mislee_zr"],
        addition: [],
        pack: "Valyana",
        vp: 0,
        sort: "airenzhixin",
        rank: "junk",
    },
        vl_mokalin: {
        enable: true,
        name: "莫卡林",
        title: "坚如磐石",
        gender: "male",
        bloc: "vl_xiongzu",
        hp: 4,
        intro: "莫卡林，随着一阵强光从天而降的神秘熊人。路过万林之森的米亚和科里科特师徒发现了衣不蔽体的他。醒来后，莫卡林虽然尝试与他们沟通，但操着一口异世界的语言的他在尝试融入新世界的路上渐行渐远...<br>即使如此，米亚还是欣然接受了莫卡林进入自己的队伍，并踏上了新的旅程。据莫卡林所言，其是来自另一个世界的某部落首领（科里科特表示怀疑），无意间踏进空间裂隙来到此地，目前还在寻找回去的方法，在了解到这个世界的兽人处境后，他表示很乐意先做些什么再走。",
        prefix: "",
        skills: ["vl_mokalin_sy", "vl_mokalin_dh"],
        addition: [],
        pack: "Valyana",
        vp: 0,
        sort: "tuozhanliandong",
        rank: "epic",
    },
    


    vl_milite: {
        enable: true,
        name: "巴兹",
        title: "疑计丛生",
        gender: "male",
        bloc: "vl_longzu",
        hp: 7,
        intro: "巴兹出身于龙之谷北侧的雷崖氏族，幼年时便被族人视为异类。他的鳞角颜色浅淡，体格却远比同龄龙族高大，常年穿着厚重铠甲在风暴崖壁间巡行。雷崖氏族曾因一场内乱几乎分裂，巴兹没有选择用蛮力镇压，而是以假情报、诱敌路线和层层伏兵拆开了叛军的盟约，自此得到“疑计丛生”的称号。<br>巴兹习惯在战前观察很久。他手中的长刃不只是武器，也是指挥信号；当雷声落下，他布置的每一处误导都会同时收束。外人常以为他沉默迟钝，真正与他交手后才会明白，那些看似笨重的停顿往往是陷阱开始合拢的前兆。",
        prefix: "",
        skills: ["vl_milite_sz", "vl_milite_yj"],
        addition: [],
        pack: "Valyana",
        vp: 0,
        sort: "dragongu",
        rank: "rare",
    },
    vl_morly: {
        enable: true,
        name: "莫雷",
        title: "枪林弹雨",
        gender: "male",
        bloc: "vl_zhuzu",
        hp: 4,
        intro: "莫雷出生在迦奈尔联邦西部的旧工业城，那里烟囱林立，矿车与军工厂的噪声几乎盖过了钟声。他少年时在枪械工坊做学徒，最初只负责给试验武器记录膛压与弹道。一次边境冲突中，整座工坊被临时征用，莫雷用一支尚未定型的连发火枪守住了撤离通道，也因此被联邦军械署注意。<br>莫雷的战斗方式带着工匠式的精确。他喜欢把不同属性的晶石弹匣插在腰间，根据风向、湿度和敌人的护甲材质临时调整弹种。那身深色护甲和手中的长枪让他看上去像普通士兵，但熟悉他的人都知道，莫雷真正可怕之处在于他总能把一场混乱交火拆成冷静的弹道计算。",
        prefix: "",
        skills: ["vl_morly_ld", "vl_morly_xd", "vl_morly_qy"],
        addition: [],
        pack: "Valyana",
        vp: 0,
        sort: "jianaier",
        rank: "common",
    },
    vl_mouse: {
        enable: true,
        name: "缪斯",
        title: "奇门八卦",
        gender: "female",
        bloc: "vl_shuzu",
        hp: 4,
        intro: "缪斯来自米兰寺外的河港鼠族世家。她幼年体弱，被送入寺中调养，反而对经阁里残缺的机关阵图产生了兴趣。米兰寺僧侣讲求静心观象，缪斯却喜欢把香灰、铜钱和红线摆成阵盘，从细小的偏差里推算人心与地势。多年后，她带着一卷八门阵谱离寺游历，成为少见的鼠族阵术师。<br>缪斯总披着宽大的斗篷，背后挂着符绳和小型罗盘，看似散漫，实则会在谈话时记住每个人踏出的方向。她相信世界处处有门，生路、伤路、惊路皆藏在选择之间。若她愿意替人开门，那人便可能从绝境中脱身；若她将门关上，再坚固的堡垒也会变成迷宫。",
        prefix: "",
        skills: ["vl_mouse_bm"],
        addition: [],
        pack: "Valyana",
        vp: 0,
        sort: "milan",
        rank: "epic",
    },
    vl_muliy: {
        enable: true,
        name: "穆里耶",
        title: "峰回路转",
        gender: "female",
        bloc: "vl_hulizu",
        hp: 3,
        intro: "穆里耶生于万灵之森边缘的狐族礼乐家族，自幼被训练为祭典司仪。她总穿着整洁的青绿色礼服，腰间系着红绳与铃饰，在灯笼与木廊之间行走时，几乎不会发出脚步声。一次森林神龛迁移中，她发现古老仪轨并非固定的咒文，而是一套引导地脉回旋的节奏，由此掌握了改变流向的灵术。<br>穆里耶并不追求正面对抗。她擅长在局势将要坠落时轻轻拨动一处节点，让原本的败势转回可控的路径。万灵之森的长者称她为“峰回路转”，因为她总能在山穷水尽处找到新的转弯，也总能让急躁的同行者明白，真正的道路未必在眼前。",
        prefix: "",
        skills: ["vl_mliy_lf", "vl_mliy_hx"],
        addition: [],
        pack: "Valyana",
        vp: 0,
        sort: "wanling",
        rank: "rare",
    },
    vl_nashu: {
        enable: true,
        name: "尧",
        title: "恶魂使者",
        gender: "male",
        bloc: "shen",
        hp: 4,
        intro: "尧，是瓦尔亚那大陆信仰中的神明，他是冥界的统治者，负责管理和收割那些邪恶的灵魂。在瓦尔亚那大陆的历史中，尧一直是一个神秘而的存在。<br>传说中，当一个人死后，他的灵魂会被送到尧的冥界，经过他的审判和选择，才能得到永恒的归宿。因此，尧在人们的心目中拥有着无上的权威和力量，被视为神圣不可侵犯的存在。<br>尧的力量和能力是源于他所收割的灵魂。每当他收割一个灵魂，他就可以从中吸取力量，增强自己的能力。随着收割的灵魂数量的增加，尧的力量也会逐渐增强，变得越来越不可战胜。",
        prefix: "",
        skills: ["vl_nashu_th", "vl_nashu_sg"],
        addition: [],
        pack: "Valyana",
        vp: 0,
        sort: "shoushen",
        rank: "legend",
    },
    vl_neises: {
        enable: true,
        name: "内瑟斯",
        title: "黑塔算师",
        gender: "male",
        bloc: "vl_quanzu",
        hp: 3,
        intro: "内瑟斯出生于迦奈尔联邦北境的犬族矿镇，那里终年阴雨，机械钟塔与黑色工厂相互遮蔽。他少年时不擅长体力劳作，却能在废弃账册和旧式计算机之间找到异常规律。联邦学院破格收下他后，他将矩阵算法、占测术和机关逻辑混合成一套独特的演算体系，被同僚称为“黑塔算师”。<br>内瑟斯常穿深色长衣，站在昏暗窗前记录每一次实验结果。他不喜欢用预言形容自己的能力，认为未来只是大量变量交错后的暂时解。战场、交易、政治谈判在他眼中都可以被拆成数列；只要给他足够信息，他便能指出最脆弱的那个点。",
        prefix: "",
        skills: ["vl_neises_hb"],
        addition: [],
        pack: "Valyana",
        vp: 0,
        sort: "jianaier",
        rank: "junk",
    },
    vl_nier: {
        enable: true,
        name: "尼尔",
        title: "智解万象",
        gender: "male",
        bloc: "vl_hulizu",
        hp: 3,
        intro: "尼尔，生活在万灵之森中的神秘狐人，他曾言自己见过《瓦尔亚那百科》的原本，因此获得了强大的智慧，能够看穿事物的本质。他崇尚自然和和平，对一切破坏自然的人都会不假辞色。他在弈法和弈风前往万灵之森后看中他们的天赋，并将它们收为弟子。与其说是师傅，尼尔更不如说是他们的父亲一般的角色。",
        prefix: "",
        skills: ["vl_nier_zj"],
        addition: [],
        pack: "Valyana",
        vp: 0,
        sort: "wanling",
        rank: "junk",
    },
    vl_nulia: {
        enable: true,
        name: "怒力亚",
        title: "渡化万物",
        gender: "male",
        bloc: "vl_niuzu",
        hp: 4,
        intro: "怒力亚来自人鱼之海北岸的牛族港镇。海风、盐渍和船坞木桩构成了他的童年，他原本只是码头搬运工，因一次风暴中救下沉船幸存者而被海岸修会收留。修会教他用潮汐草药、净水仪式和朴素的祈祷安抚伤者，他也逐渐从粗粝的水手成长为能在灾后维持秩序的渡海医者。<br>怒力亚总穿着明亮的外衣，像一面在海雾中容易辨认的旗帜。他相信痛苦若无人接住，便会继续传给下一个人。因此他四处奔走，替渔村、商队和流亡者处理伤病与怨恨。人们说他的手能渡化万物，并不是因为他从不愤怒，而是因为他总能把愤怒带到该停下的地方。",
        prefix: "",
        skills: ["vl_nulia_dh", "vl_nulia_hj"],
        addition: [],
        pack: "Valyana",
        vp: 0,
        sort: "renyu",
        rank: "rare",
    },
    vl_oert: {
        enable: true,
        name: "欧尔特",
        title: "轮回使者",
        gender: "male",
        bloc: "shen",
        hp: 4,
        intro: "轮回之神欧尔特，不像其他的神那样高高在上。据传，欧尔特曾在瓦尔亚娜大陆最重要的节日“「火灵日」”，亲自来到瓦尔亚娜大陆的一座山峰上为瓦尔亚娜的百姓祈福，并参加兽人族的祭典活动。而受他惠顾的小贩说到：“神灵大人最喜欢我们家的丸子。”虽然真假未可知。",
        prefix: "",
        skills: ["vl_oert_lh", "vl_oert_wy"],
        addition: [],
        pack: "Valyana",
        vp: 0,
        sort: "shoushen",
        rank: "epic",
    },
    vl_paers: {
        enable: true,
        name: "帕尔斯",
        title: "斗转星移",
        gender: "male",
        bloc: "vl_hulizu",
        hp: 4,
        intro: "帕尔斯出生于迦奈尔联邦的高层金融区，是狐族中少见的空间工程顾问。他年轻时曾参与城市轨道与传送站的校准工作，负责处理那些看不见却足以让整列列车偏离数寸的空间误差。一次传送事故后，他失去了原本的职位，却也因此摸清了联邦禁用的折跃公式。<br>帕尔斯总以西装示人，手中端着酒杯或怀表，仿佛任何危机都只是宴会上的一段插曲。他擅长让距离、方位与代价互相交换，使攻击落空，使退路出现在不合常理的位置。熟悉他的人从不轻易与他对赌，因为帕尔斯最擅长的事，就是在所有人下注后悄悄移动赌桌。",
        prefix: "",
        skills: ["vl_paers_fy", "vl_pares_xh"],
        addition: [],
        pack: "Valyana",
        vp: 0,
        sort: "jianaier",
        rank: "epic",
    },
    vl_peter_likes: {
        enable: true,
        name: "皮特莱克",
        title: "操魂控魄",
        gender: "male",
        bloc: "vl_langzu",
        hp: 3,
        intro: "皮特莱克，出生于一个传统的兽人家庭，父亲以制作玩偶为生。在一次意外之后，皮特获得了特殊的能力，能够操纵别人的意识。如此强大的能力却没有被其滥用，而是用来帮助更多人。",
        prefix: "",
        skills: ["vl_peterlk_kh", "vl_peterlk_jn"],
        addition: [],
        pack: "Valyana",
        vp: 0,
        sort: "kela",
        rank: "legend",
    },
    vl_pluvia: {
        enable: true,
        name: "普鲁维亚",
        title: "治疗之刃",
        gender: "male",
        bloc: "vl_langzu",
        hp: 4,
        intro: "普鲁维亚是龙之谷边境的狼族医剑士，早年随商队穿越龙族领地时被卷入氏族冲突。他在战火中失去同行者，却被一名龙族祭司救下，并学会了以血液、刃纹和誓言引导生命力的古老术式。自那以后，普鲁维亚留在龙之谷，成为调停战后创伤的游医。<br>他身披带有紫色辉光的护甲，手中的剑既能切开敌人的防线，也能引出伤口中的污秽魔力。普鲁维亚不认为治疗意味着温和，很多时候，救人必须先斩断腐坏的根源。他因此被称为“治疗之刃”，行走在战场边缘，替幸存者收拾仍在燃烧的余烬。",
        prefix: "",
        skills: ["vl_pluvia_fs", "vl_pluvia_sx", "vl_pluvia_xs"],
        addition: [],
        pack: "Valyana",
        vp: 0,
        sort: "dragongu",
        rank: "common",
    },
    vl_rabby: {
        enable: true,
        name: "瑞比",
        title: "刑事拘留",
        gender: "female",
        bloc: "vl_tuzu",
        hp: 3,
        intro: "对瑞比来说，每天最为惊心动魄的时刻大概就是追捕犯人。出生于迦奈尔联邦的她，从小便幻想自己是超级英雄，能够消灭一切邪恶。后来她不出所料成为了迦奈尔联邦警局的一员。",
        prefix: "",
        skills: ["vl_rabby_qj", "vl_rabby_xj"],
        addition: [],
        pack: "Valyana",
        vp: 0,
        sort: "jianaier",
        rank: "epic",
    },
    vl_rasali: {
        enable: true,
        name: "洛",
        title: "善灵指引",
        gender: "male",
        bloc: "shen",
        hp: 3,
        intro: "洛，和尧一样，是瓦尔亚那大陆信仰中的神明之一，执掌着冥界的善灵收集和引导工作。<br>他的责任是寻找那些有着良善灵魂的人们，以便在他们离开世界之前引领他们前往冥界，让他们的灵魂在冥界得到永恒的安息。洛是一位仁慈而有担当的神明，他深知自己肩负的责任，努力工作以确保每个良善的灵魂都能得到引领。他深知冥界对于那些有着良善灵魂的人意味着什么，因此他不惜一切代价来保护他们。",
        prefix: "",
        skills: ["vl_rasali_ly", "vl_rasali_hq"],
        addition: [],
        pack: "Valyana",
        vp: 0,
        sort: "shoushen",
        rank: "legend",
    },
    vl_rest: {
        enable: true,
        name: "瑞斯特",
        title: "兴风作浪",
        gender: "male",
        bloc: "vl_haizu",
        hp: 3,
        intro: "瑞斯特，生于人鱼之海附近，虽说当地兽人族与鱼人族的关系并不融洽，但瑞斯特算是少有的与两族同时交好的人，其目前在二者之间经商。",
        prefix: "",
        skills: ["vl_rest_qf", "vl_rest_nb"],
        addition: [],
        pack: "Valyana",
        vp: 0,
        sort: "renyu",
        rank: "rare",
    },
    vl_sayisu: {
        enable: true,
        name: "萨伊苏",
        title: "兵不血刃",
        gender: "male",
        bloc: "vl_longzu",
        hp: 4,
        intro: "萨伊苏出身于龙之谷南部的赤岩氏族，那里崇尚近身角力与血脉威压。他年轻时身形魁梧、性情急躁，曾以为胜利只属于最先拔刀的人。后来在一场氏族争端中，他亲眼见到无意义的复仇吞掉整座聚落，便离开故乡，追随一位老龙裔学习如何在冲突爆发前结束冲突。<br>如今的萨伊苏仍保留着强悍的外表和锋利的爪牙，却很少急着动手。他会站在双方之间，用沉默、威慑和精准的判断压住局面；若必须出击，也往往只击中让战意崩塌的一处。龙之谷的人称他“兵不血刃”，因为他不是不懂杀戮，而是更清楚何时不该让血流下去。",
        prefix: "",
        skills: ["vl_sayisu_fj"],
        addition: [],
        pack: "Valyana",
        vp: 0,
        sort: "dragongu",
        rank: "common",
    },
    vl_shisan: {
        enable: true,
        name: "拾弎",
        title: "察微知宏",
        gender: "male",
        bloc: "vl_longzu",
        hp: 3,
        intro: "拾弎是龙之谷古城守望者的后裔，幼年便被训练在集市、祭坛和城墙之间观察细节。他的鳞色偏绿，常穿厚重甲胄混入人群，记录商队路线、氏族纹章和陌生人的呼吸节奏。一次外来势力试图挑拨龙族内斗时，正是拾弎从几枚错置的货币与一封假信中看破了阴谋。<br>拾弎相信宏大的灾难总会先在微小处露出裂痕。他不急于发表判断，宁愿在街角多站半日，也要确认每个线索的位置。人们称他“察微知宏”，既是赞誉，也是提醒：在拾弎面前，许多自以为隐秘的计划，早已在不经意间露出了完整轮廓。",
        prefix: "",
        skills: ["vl_shisan_dg", "vl_shisan_tx"],
        addition: [],
        pack: "Valyana",
        vp: 0,
        sort: "dragongu",
        rank: "legend",
    },
    vl_sier: {
        enable: true,
        name: "希尔",
        title: "降龙伏虎",
        gender: "male",
        bloc: "vl_longzu",
        hp: 3,
        intro: "希尔出生于龙之谷火山口附近的混血氏族，背生暗色龙翼，却没有得到纯血龙族的完整认可。少年时，他常被派去执行最危险的巡山任务，独自面对失控的亚龙、盗猎者和熔岩裂隙。一次深谷坍塌中，他以近乎蛮横的方式拖回了整支巡逻队，也让质疑者第一次承认他的力量。<br>希尔的战斗像从高处坠落的岩块，直接、沉重、难以阻挡。但他并非只靠血脉与体魄，长期在险地求生让他懂得何时收翼、何时俯冲、何时让敌人的力量反撞回去。“降龙伏虎”并不是他征服他人的宣言，而是他在龙之谷学会的生存方式：先降服心中的恐惧，再面对更巨大的怪物。",
        prefix: "",
        skills: ["vl_sier_xl", "vl_sier_fh", "vl_sier_ql"],
        addition: [],
        pack: "Valyana",
        vp: 0,
        sort: "dragongu",
        rank: "rare",
    },
    vl_siji: {
        enable: true,
        name: "司稷",
        title: "司农之祖",
        gender: "male",
        bloc: "vl_langzu",
        hp: 3,
        intro: "司稷，生于长河中流，瑞江边的一个部落。刚出生时，因其父未知而被认为是不详，母亲屡次将他抛弃在了山野，却也屡次被动物救助，经此三次后，母亲终于妥协将他带回家中。司稷少时对农业极具兴趣，长大后，改良谷种，并使粮食收获大幅提高，使族民彻底摆脱粮食问题。此后其一生致力于农业，被受命掌管农事与祭祀事物。最后的生命在家中安然睡去。死后被后世封为稷神、司农之祖、农圣。",
        prefix: "",
        skills: ["vl_siji_sx", "vl_siji_jg", "vl_siji_ys"],
        addition: [],
        pack: "Valyana",
        vp: 0,
        sort: "kela",
        rank: "epic",
    },
    vl_slen: {
        enable: true,
        name: "萨冷",
        title: "八面玲珑",
        gender: "male",
        bloc: "vl_langzu",
        hp: 3,
        intro: "萨冷是米兰寺旧钟楼的守夜人。幼年时，他随流民队伍来到寺外，在雪夜中被僧侣收留；成年后，他没有选择成为正式僧侣，而是负责接待旅人、修补经窗、记录来往信件。长年与各地香客、商人和避难者打交道，使他练就了周旋于复杂人际之间的本领。<br>萨冷总穿着宽大的白衣，提着一盏旧灯站在高处眺望山路。他懂礼仪，也懂谎言；懂慈悲，也懂拒绝。许多人以为“八面玲珑”只是圆滑，米兰寺的人却知道，萨冷能让互相敌视的人在同一张桌前坐下，并在天亮前找到各自还能接受的退路。",
        prefix: "",
        skills: ["vl_slen_xj", "vl_slen_gc"],
        addition: [],
        pack: "Valyana",
        vp: 0,
        sort: "milan",
        rank: "epic",
    },
    vl_souls: {
        enable: true,
        name: "莎尔丝",
        title: "魔法少女",
        gender: "female",
        bloc: "vl_hulizu",
        hp: 3,
        intro: "莎尔丝出生于万灵之森与人类城镇交界处的狐族家庭。她小时候常在教堂尖塔和森林祭坛之间奔跑，一边听修女讲述星辰，一边偷看精灵法师修补结界。某次夜间灾厄降临时，她在残破彩窗前听见来自星辉的呼唤，从一枚旧胸针中唤出了守护魔法，也因此踏上了自称“魔法少女”的道路。<br>莎尔丝的装束轻快明亮，常被误认为只是在模仿童话里的英雄。但她所面对的并不只是孩童幻想中的邪恶，而是深夜巷口的失踪、森林边缘的诅咒和无人愿意处理的小型灾难。她相信希望必须有具体的形状，于是把缎带、咒语和笑容都当成武器，努力让旁人相信黑夜确实会过去。",
        prefix: "",
        skills: ["vl_souls_ch", "vl_souls_mj", "vl_souls_md"],
        addition: [],
        pack: "Valyana",
        vp: "1/3",
        sort: "wanling",
        rank: "epic",
    },
    vl_taber: {
        enable: true,
        name: "塔贝尔",
        title: "掘地三尺",
        gender: "male",
        bloc: "vl_langzu",
        hp: 4,
        intro: "塔贝尔是游荡旅行者中有名的遗物猎人，常背着鼓鼓囊囊的行囊出现在旧矿道、废村和古战场边缘。他出生在克拉乡间，年轻时为了寻找失踪的兄长离家，途中学会了辨认土层、修补地图和从废墟传闻中筛出真实线索。兄长最终没有找到，他却再也无法停下脚步。<br>塔贝尔手中的铲子和笔记本比刀剑更常用。他相信每一片被掩埋的土地都有自己的脾气，挖掘时必须先读懂风向、水痕和当地人的沉默。别人说他“掘地三尺”是在贪图宝物，他却更愿意把自己称作替遗忘之物开门的人。",
        prefix: "",
        skills: ["vl_taber_jj", "vl_taber_sj"],
        addition: [],
        pack: "Valyana",
        vp: 0,
        sort: "youdangzhe",
        rank: "epic",
    },
    vl_telina: {
        enable: true,
        name: "特丽娜",
        title: "预见之眼",
        gender: "female",
        bloc: "vl_langzu",
        hp: 3,
        intro: "特丽娜拥有特殊的「未来视」能力，她能够预知近至下一秒，远至数年的所有事件。在「瓦尔亚那百科全书」完成编写后，精灵族就在寻找拥有预言能力的人。因此特丽娜成为第一个受邀进入万灵之森的兽人。",
        prefix: "",
        skills: ["vl_telina_hs", "vl_telina_th"],
        addition: [],
        pack: "Valyana",
        vp: 0,
        sort: "wanling",
        rank: "junk",
    },
    vl_terlk: {
        enable: true,
        name: "特尔里克",
        title: "披荆斩棘",
        gender: "male",
        bloc: "vl_quanzu",
        hp: 4,
        intro: "特尔里克来自克拉北境的犬族驿路，家族世代护送商队穿过山林与雪原。他少年时不擅长华丽剑术，却有极强的耐力和方向感，能在暴风雪里凭气味和脚印找到断裂的道路。一次护送任务中，山贼烧毁栈桥、封死峡谷，特尔里克硬是带着幸存者劈开旧林道走出包围，从此被商会记住。<br>他穿着朴素的旅装，常抱臂站在队伍最前方，像一块不肯挪开的路标。特尔里克不喜欢空谈理想，只相信一刀一斧开出的道路。所谓“披荆斩棘”，对他而言不是豪言，而是每一次带人抵达下一座灯火时必须付出的辛苦。",
        prefix: "",
        skills: ["vl_terlk_zj", "vl_terlk_pj"],
        addition: [],
        pack: "Valyana",
        vp: 0,
        sort: "kela",
        rank: "rare",
    },
    vl_tery: {
        enable: true,
        name: "特瑞",
        title: "千变万化",
        gender: "male",
        bloc: "vl_langzu",
        hp: "1/4",
        intro: "特瑞，出生于迦奈尔联邦，其能力极为罕见，虽在大量禁魔矿脉附近，却依然能够释放魔法，其能够从其他人释放的魔法中解析咒文，并快速学习。但其能力仍有限制，其对于不使用魔法或魔法能力过强者无法复制。后来，特瑞加入了「暗影」刺杀队并成为了其中的二把手，主要负责高难度人物和照顾团队起居。",
        prefix: "",
        skills: ["vl_tery_hx", "vl_tery_sg"],
        addition: [],
        pack: "Valyana",
        vp: 0,
        sort: "franying",
        rank: "legend",
    },
    vl_thunder: {
        enable: true,
        name: "兰德",
        title: "雷光跃动",
        gender: "male",
        bloc: "vl_langzu",
        hp: 4,
        intro: "兰德出生于迦奈尔联邦东部的高楼城区，少年时便在雷暴夜里展现出异常的导电体质。联邦研究所曾试图将他培养成军用能源适配者，但兰德无法忍受被关在实验室中反复测试，最终逃入城市地下的旧电网。多年后，他以雇佣兵身份重新出现，身上的灰蓝披风与金属护具都带着改造痕迹。<br>兰德能让电流在肌肉与武器之间短暂跃迁，行动时像一道从阴影里窜出的雷光。他并不热衷破坏，却讨厌被束缚和计算。每当城市灯光忽明忽暗，人们便知道兰德可能已经经过附近；若有人试图再次给他套上编号，等待对方的往往是一场无法预测的短路风暴。",
        prefix: "",
        skills: ["vl_thunder_fz", "vl_thunder_lj"],
        addition: [],
        pack: "Valyana",
        vp: 0,
        sort: "jianaier",
        rank: "epic",
    },
    vl_tiger: {
        enable: true,
        name: "泰格尔",
        title: "混元一气",
        gender: "male",
        bloc: "vl_huzu",
        hp: 4,
        intro: "泰格尔，来自兽人王国克拉西部的斯特赖城区域，这里的人们习惯使用剑技来作为防身手段。米亚和科里科特曾在执行任务的时候与其相遇，米亚曾施展所有功力与其切磋，米亚指导其剑术并指出其弱点并与其成为好友。",
        prefix: "",
        skills: ["vl_tiger_hy", "vl_tiger_kf"],
        addition: [],
        pack: "Valyana",
        vp: 0,
        sort: "kela",
        rank: "epic",
    },
    vl_ventus: {
        enable: true,
        name: "凡图斯",
        title: "泣血之刃",
        gender: "male",
        bloc: "vl_langzu",
        hp: 4,
        intro: "凡图斯曾是克拉边境的狼族剑士，因一场讨伐深渊裂隙的行动而染上血色魔痕。那道力量让他在重伤时仍能站起，也让他的情绪和生命力长期处在危险的拉扯中。为了不牵连故乡，他离开军队，独自追查魔痕源头，后来多次出现在深渊地带附近的废墟。<br>凡图斯身上的暗红光芒并非装饰，而是他时时压制的诅咒回流。他的剑法凶狠，却带着近乎自毁的克制，每一次出手都像是在用自己的血偿还某种债。有人称他为“泣血之刃”，因为他从不解释过去，只把所有痛苦都磨进刀锋，继续向裂隙深处前进。",
        prefix: "",
        skills: ["vl_ventus_nx", "vl_ventus_yc"],
        addition: [],
        pack: "Valyana",
        vp: 0,
        sort: "dalu_lingmian",
        rank: "common",
    },
    vl_wore: {
        enable: true,
        name: "沃尔",
        title: "千变万化",
        gender: "male",
        bloc: "vl_langzu",
        hp: 4,
        intro: "沃尔，生活在迦奈尔联邦，职业为心理医生，曾前往克拉研习催眠术，其原本为沃尔为免服役人员，但在其强烈要求下，进入联邦军队成为战地心理医生。在服役五年后又要求回到家乡科马——联邦南部的一座小城市",
        prefix: "",
        skills: ["vl_wore_hy"],
        addition: ["zhu"],
        pack: "Valyana",
        vp: 0,
        sort: "jianaier",
        rank: "rare",
    },
    vl_zenia: {
        enable: true,
        name: "泽妮雅",
        title: "余音绕梁",
        gender: "female",
        bloc: "vl_hulizu",
        hp: 3,
        intro: "泽妮雅是米兰寺巡回乐班收养的狐族歌者。她幼年时嗓音微弱，常被安排在后台整理乐谱，却能记住每一段旋律的起伏。一次寺中镇魂仪式失败，躁动的亡灵几乎冲破经堂，泽妮雅在惊惧中唱出残缺的安魂曲，意外让灵潮平息。自那以后，她开始学习以音律牵引情绪与灵息。<br>泽妮雅常抱着乐器坐在灯影里，金色长发与柔软狐耳让她看上去像不谙世事的贵族少女。真正听过她歌声的人却明白，她的旋律能抚平伤痛，也能让压抑多年的执念浮出水面。她被称为“余音绕梁”，因为她离开后，许多人仍会在梦中听见那段未唱完的曲子。",
        prefix: "",
        skills: ["vl_zenia_yy", "vl_zenia_ys", "vl_zenia_ld"],
        addition: [],
        pack: "Valyana",
        vp: 0,
        sort: "milan",
        rank: "common",
    },
}
