export const furryCharacter = {
    vl_baliqiao: {
        enable: true,
        name: "八狸桥",
        title: "",
        gender: "male",
        bloc: "vl_hulizu",
        hp: 3,
        intro: "",
        prefix: "",
        skills: ["vl_baliqiao_bl", "vl_baliqiao_sj", "vl_baliqiao_qm"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "vl_furry_migration",
        rank: "epic",
    },
    vl_bwol: {
        enable: true,
        name: "鲍尔",
        title: "爆炸艺术家",
        gender: "male",
        bloc: "vl_baozu",
        hp: 3,
        intro: "",
        prefix: "",
        skills: ["vl_bwol_mb", "vl_bwol_zj"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "vl_furry_migration",
        rank: "epic",
    },
    vl_siji: {
        enable: true,
        name: "司稷",
        title: "司农之祖",
        gender: "male",
        bloc: "vl_langzu",
        hp: 3,
        intro: "司稷，生于长河中流，瑞江边的一个部落。刚出生时，因其父未知而被认为是不详，母亲屡次将他抛弃在了山野，却也屡次被动物救助，经此三次后，母亲终于妥协将他带回家中。司稷少时对农业极具兴趣，长大后，改良谷种，并使粮食收获大幅提高，使族民彻底摆脱粮食问题。此后其一生致力于农业，被受命掌管农事与祭祀事物。最后的生命在家中安然睡去。死后被后世封为稷神、司农之祖、农圣。",
        prefix: "",
        skills: ["vl_siji_sx", "vl_siji_jg", "vl_siji_ys"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "vl_furry_migration",
        rank: "epic",
    },
    vl_youying: {
        enable: true,
        name: "游影",
        title: "挥剑如歌",
        gender: "male",
        bloc: "vl_langzu",
        hp: 4,
        intro: "游影，出生于万灵之森边陲的小镇“米埃”。自幼跟随父亲修行剑法，后出门远行前往米兰寺求学，经介绍后跟随米亚学习剑术，但最后因理念不同而分道扬镳。游影的剑法诡谲，翩若惊鸿，宛若游龙。剑法精妙，如诗般令人赏心悦目。",
        prefix: "",
        skills: ["vl_youying_jg", "vl_youying_qy"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "youdangzhe",
        rank: "epic",
    },
    vl_rabby: {
        enable: true,
        name: "瑞比",
        title: "刑事拘留",
        gender: "female",
        bloc: "vl_tuzu",
        hp: 3,
        intro: "对瑞比来说，每天最为惊心动魄的时刻大概就是追捕犯人。出生于迦奈尔联邦的她，从小便幻想自己是超级英雄，能够消灭一切邪恶。后来她不出所料成为了迦奈尔联邦警局的一员。",
        prefix: "",
        skills: ["vl_rabby_qj", "vl_rabby_xj"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "vl_furry_migration",
        rank: "epic",
    },
    vl_charlin: {
        enable: true,
        name: "查尔林",
        title: "指鹿为马",
        gender: "male",
        bloc: "vl_luzu",
        hp: 3,
        intro: "查尔林，从小就是众人眼中的天之骄子，诞生于克拉贵族家庭的他从小就受到了极其严苛和专业的教导，而他也对哲学和修辞学尤为喜爱，并跟从多戈进行学习。觉醒了精神系能力的他，能够让任何人在短时间内相信他所说的一切，他也因此能力被克拉的老国王选为了祭祀。在老国王死后，他则负责太子盖尔德鲁的伴读和老师，而盖尔德鲁也对他极其信赖。但是不要被他的外表所迷惑，看似亲和的外表下隐藏的却是残忍而嗜血的内心，他为了达成自己的目的不择手段。有传言称国王盖尔德鲁后期的昏聩和位极人臣的查尔林的诱导脱不开关系，另有传言称其害死了他的老师。",
        prefix: "",
        skills: ["vl_charlin_fs", "vl_charlin_qs"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "vl_furry_migration",
        rank: "legend",
    },
    vl_mokalin: {
        enable: true,
        name: "莫卡林",
        title: "坚如磐石",
        gender: "male",
        bloc: "vl_xiongzu",
        hp: 4,
        intro: "莫卡林，随着一阵强光从天而降的神秘熊人。路过万林之森的米亚和科里科特师徒发现了衣不蔽体的他。醒来后，莫卡林虽然尝试与他们沟通，但操着一口异世界的语言的他在尝试融入新世界的路上渐行渐远...<br>即使如此，米亚还是欣然接受了莫卡林进入自己的队伍，并踏上了新的旅程。据莫卡林所言，其是来自另一个世界的某部落首领（科里科特表示怀疑），无意间踏进空间裂隙来到此地，目前还在寻找回去的方法，在了解到这个世界的兽人处境后，他表示很乐意先做些什么再走。",
        prefix: "",
        skills: ["vl_mokalin_sy", "vl_mokalin_dh"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "tuozhanliandong",
        rank: "epic",
    },
    vl_mierk: {
        enable: true,
        name: "米尔克",
        title: "力争神辩",
        gender: "male",
        bloc: "vl_langzu",
        hp: 3,
        intro: "米尔克，米勒的哥哥，生于克拉贵族家庭的他从小就跟随师傅查尔林学习修辞学。后来因为与其师傅的理念不同而分道扬镳，离开了王城。也正因此躲过了后来的政治风波。",
        prefix: "",
        skills: ["vl_mierk_jc", "vl_mierk_fm", "vl_mierk_jingcai"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "vl_furry_migration",
        rank: "epic",
    },
    vl_baixi: {
        enable: true,
        name: "白曦&墨喑",
        title: "阴阳两仪",
        gender: "male",
        bloc: "vl_langzu",
        hp: 3,
        intro: "",
        prefix: "",
        skills: ["vl_baixi_lj", "vl_baixi_lj_change", "vl_baixi_dy", "vl_baixi_bm"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "kechuanjuese",
        rank: "epic",
    },
    vl_akain: {
        enable: true,
        name: "阿卡因",
        title: "风云变幻",
        gender: "male",
        bloc: "vl_langzu",
        hp: 3,
        intro: "",
        prefix: "",
        skills: ["vl_akain_bx", "vl_akain_ys", "vl_akain_fy", "vl_akain_jh"],
        addition: ["doublegroup:wei:shu"],
        pack: "FurryExt",
        vp: "1/3",
        sort: "vl_furry_migration",
        rank: "epic",
    },
    vl_luyezhi: {
        enable: true,
        name: "鹿野灸",
        title: "大总攻",
        gender: "male",
        bloc: "vl_luzu",
        hp: 3,
        intro: "",
        prefix: "",
        skills: ["vl_luyezhi_zy", "vl_luyezhi_zye"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "kechuanjuese",
        rank: "epic",
    },
    vl_souls: {
        enable: true,
        name: "莎尔丝",
        title: "魔法少女",
        gender: "female",
        bloc: "vl_hulizu",
        hp: 3,
        intro: "",
        prefix: "",
        skills: ["vl_souls_ch", "vl_souls_mj", "vl_souls_md"],
        addition: [],
        pack: "FurryExt",
        vp: "1/3",
        sort: "vl_furry_migration",
        rank: "epic",
    },
    vl_aak: {
        enable: true,
        name: "阿",
        title: "神医",
        gender: "male",
        bloc: "vl_shizu",
        hp: 4,
        intro: "",
        prefix: "",
        skills: ["vl_aak_yj", "vl_aak_hy", "vl_aak_gj"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "vl_furry_migration",
        rank: "common",
    },
    vl_mountainbear: {
        enable: true,
        name: "山熊",
        title: "力透千钧",
        gender: "male",
        bloc: "vl_xiongzu",
        hp: "3/3/4",
        intro: "&nbsp&nbsp&nbsp&nbsp山熊，原本是一只栖息在矮人之心洞穴周围的强大魔兽。它的存在一直是矮人部落的威胁，不断地对部落成员构成威胁。然而，山熊的命运在一次决定性的战斗中发生了巨变。在那场战斗中，山熊遭到了路西法的父亲的挑战。这场战斗激烈而残酷，但最终，路西法的父亲以出色的战斗技巧和坚韧不拔的意志，战胜了山熊。这场胜利被看作是路西法的父亲的一项英勇壮举，也标志着山熊的命运将发生改变。\n            <br>&nbsp&nbsp&nbsp&nbsp作为成年礼的礼物，路西法的父亲决定将山熊送给他的儿子。这个决定改变了山熊的生活轨迹，也让它与路西法的命运紧密交织在一起。在路西法的成年礼上，他通过强大的战斗技巧获得了山熊的认可。这次战斗是他们之间的一场考验，也是他们友谊的开始。山熊看到了路西法的坚决和勇气，开始信任他，并与他签订了一份特殊的契约。\n            <br>&nbsp&nbsp&nbsp&nbsp多年来，山熊和路西法成为了一对默契无间的伙伴。他们已经可以通过思想交流，将彼此的意愿传达得非常清晰，这是一种深厚的信任和默契的体现。他们的生命似乎已经通过契约而紧密连接，无论在战斗还是在日常生活中，他们总是互相扶持，守护着彼此。山熊生性暴戾，在没有兽语者控制的情况下。它可能会表现出随意伤人的行为，因此，只有路西法的存在和指导才能确保山熊不会陷入暴怒之中，保持友善和控制。\n            <br>&nbsp&nbsp&nbsp&nbsp山熊和路西法的故事是一段关于友情和信任的传奇。他们的契约将继续引领他们前行，不仅是伙伴，也是彼此的支持和保护者。这个不寻常的友情，已经成为了他们生命中最宝贵的财富。",
        prefix: "",
        skills: ["vl_mountainbear_xs", "vl_mountainbear_xj"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "vl_furry_migration",
        rank: "common",
    },
    vl_guotang: {
        enable: true,
        name: "果糖",
        title: "果糖含量",
        gender: "male",
        bloc: "vl_langzu",
        hp: 3,
        intro: "",
        prefix: "",
        skills: ["vl_guotang_yl", "vl_guotang_xq", "vl_guotang_st"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "vl_furry_migration",
        rank: "common",
    },
    vl_lucifer: {
        enable: true,
        name: "路西法",
        title: "",
        gender: "male",
        bloc: "vl_langzu",
        hp: 3,
        intro: "路西法，目前为居住在矮人之心洞穴附近的兽人部落首领。其部落信仰生命之神——“特拉克斯”，并获得了其传承的特殊能力。该能力使得其部落的勇士能够与动物沟通，甚至训练动物成为伙伴。拥有这种特殊能力的人在《瓦尔亚那》百科中称为“兽语者”。",
        prefix: "",
        skills: ["vl_lucifer_cc", "vl_lucifer_xz"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "airenzhixin",
        rank: "rare",
    },
    vl_lans: {
        enable: true,
        name: "兰斯",
        title: "",
        gender: "male",
        bloc: "vl_weizhi",
        hp: 3,
        intro: "",
        prefix: "",
        skills: [],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "vl_furry_migration",
        rank: "rare",
    },
    vl_keste: {
        enable: true,
        name: "科斯特",
        title: "常胜将军",
        gender: "male",
        bloc: "vl_langzu",
        hp: 4,
        intro: "科斯特，迦奈尔联邦最年轻也是最年少有为的将军，曾经在与矮人族的战争——“矮人之心争夺战”中大获全胜，歼敌数万。其主导与矮人族签下的《斯兰条约》为迦奈尔联邦的贸易事业奠定了发展基础。因此，这位将军也被成为“尼拉特”将军——即矮人语中的“恶魔”。",
        prefix: "",
        skills: ["vl_keste_yg", "vl_keste_wp"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "jianaier",
        rank: "epic",
    },
    vl_neises: {
        enable: true,
        name: "内瑟斯",
        title: "",
        gender: "male",
        bloc: "vl_quanzu",
        hp: 3,
        intro: "",
        prefix: "",
        skills: ["vl_neises_hb"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "vl_furry_migration",
        rank: "junk",
    },
    vl_wind: {
        enable: true,
        name: "温迪",
        title: "且听风吟",
        gender: "male",
        bloc: "vl_langzu",
        hp: 4,
        intro: "",
        prefix: "",
        skills: ["vl_wind_fy"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "vl_furry_migration",
        rank: "rare",
    },
    vl_nine: {
        enable: true,
        name: "奈恩",
        title: "孤僻的天才",
        gender: "male",
        bloc: "vl_hulizu",
        hp: 3,
        intro: "",
        prefix: "",
        skills: ["vl_nine_fw", "vl_nine_cj", "vl_nine_dx"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "vl_furry_migration",
        rank: "legend",
    },
    vl_ming: {
        enable: true,
        name: "鸣",
        title: "能言善辩",
        gender: "male",
        bloc: "vl_huzu",
        hp: 3,
        intro: "",
        prefix: "",
        skills: ["vl_ming_yc", "vl_ming_yy"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "vl_furry_migration",
        rank: "epic",
    },
    vl_dolina: {
        enable: true,
        name: "多林",
        title: "",
        gender: "male",
        bloc: "vl_langzu",
        hp: 3,
        intro: "",
        prefix: "",
        skills: ["vl_dolina_wy", "vl_dolina_sl", "vl_dolina_qj"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "vl_furry_migration",
        rank: "common",
    },
    vl_thunder: {
        enable: true,
        name: "兰德",
        title: "雷光跃动",
        gender: "male",
        bloc: "vl_langzu",
        hp: 4,
        intro: "",
        prefix: "",
        skills: ["vl_thunder_fz", "vl_thunder_lj"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "vl_furry_migration",
        rank: "epic",
    },
    vl_mouse: {
        enable: true,
        name: "缪斯",
        title: "奇门八卦",
        gender: "female",
        bloc: "vl_shuzu",
        hp: 4,
        intro: "",
        prefix: "",
        skills: ["vl_mouse_bm"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "vl_furry_migration",
        rank: "epic",
    },
    vl_lamas: {
        enable: true,
        name: "拉马斯",
        title: "战技如神",
        gender: "male",
        bloc: "vl_shizu",
        hp: 4,
        intro: "",
        prefix: "",
        skills: ["vl_lamas_zj"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "vl_furry_migration",
        rank: "rare",
    },
    vl_blam: {
        enable: true,
        name: "布兰",
        title: "如入幻境之刃",
        gender: "male",
        bloc: "vl_langzu",
        hp: 4,
        intro: "布兰，希尔特黑帮的二把手。布兰的剑法传自其祖上的剑术大师“希诺”，能够以自身的血液让剑与自身产生共鸣，达到人剑合一的地步。据传，其曾于科里科特",
        prefix: "",
        skills: ["vl_blame_jj"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "kela",
        rank: "legend",
    },
    vl_gairtelu: {
        enable: true,
        name: "盖尔德鲁",
        title: "暴戾君王",
        gender: "male",
        bloc: "vl_huzu",
        hp: 4,
        intro: "盖尔德鲁，克拉的王室成员，作为皇室血脉的他在10岁时就成为了克拉的国王。但是作为国王的他却耽于享乐，27岁时下令建造“圣灵塔”妄图与永恒之神法斯建立连接以获得无尽的寿命。在他的任期内，国民的赋税甚至达到了恐怖1/3。后来北境爆发被称为“正裁战争”的起义将其王朝推翻，哈拉尔接替他成为国王。而盖尔德鲁从此下落不明，民间有传言称其逃到了矮人边境，也有说法称其被哈拉尔秘密处决。",
        prefix: "",
        skills: ["vl_gairtelu_sf", "vl_gairtelu_zs", "vl_gairtelu_aq"],
        addition: ["zhu"],
        pack: "FurryExt",
        vp: 0,
        sort: "kela",
        rank: "epic",
    },
    vl_tails: {
        enable: true,
        name: "塔尔斯",
        title: "灵活的机械师",
        gender: "male",
        bloc: "vl_hulizu",
        hp: 3,
        intro: "塔尔斯是一只来自异世界的机械师狐狸，可以使用两条尾巴进行甩尾飞行，且擅长使用和制造各种机械装置。因为意外，他穿越到了瓦尔亚那大陆，一些同伴和七颗神秘的混沌翡翠也一同降临。<br>为了获取散落于各地的混沌翡翠，打通回家之路，塔尔斯和同伴们加入了赏金公会。作为天才机械师，塔尔斯将他的异世界技术巧妙地结合到这个陌生的大陆上，为公会的任务提供了独特的解决方案。<br>不过，回家才是他们的主旋律，这次奇妙的旅行必将在塔尔斯年仅8岁的阅历中留下浓墨重彩的一笔。",
        prefix: "",
        skills: ["vl_tails_jd", "vl_tails_qx"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "vl_furry_migration",
        rank: "legend",
    },
    vl_zhan: {
        enable: true,
        name: "展",
        title: "束缚之厄",
        gender: "male",
        bloc: "vl_maozu",
        hp: 3,
        intro: "",
        prefix: "",
        skills: ["vl_zhan_sf", "vl_zhan_jf"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "vl_furry_migration",
        rank: "legend",
    },
    vl_rasali: {
        enable: true,
        name: "洛",
        title: "善灵指引",
        gender: "male",
        bloc: "shen",
        hp: 3,
        intro: "洛，和尧一样，是瓦尔亚那大陆信仰中的神明之一，执掌着冥界的善灵收集和引导工作。<br>他的责任是寻找那些有着良善灵魂的人们，以便在他们离开世界之前引领他们前往冥界，让他们的灵魂在冥界得到永恒的安息。洛是一位仁慈而有担当的神明，他深知自己肩负的责任，努力工作以确保每个良善的灵魂都能得到引领。他深知冥界对于那些有着良善灵魂的人意味着什么，因此他不惜一切代价来保护他们。",
        prefix: "",
        skills: ["vl_rasali_ly", "vl_rasali_hq"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "shoushen",
        rank: "legend",
    },
    vl_nashu: {
        enable: true,
        name: "尧",
        title: "恶魂使者",
        gender: "male",
        bloc: "shen",
        hp: 4,
        intro: "尧，是瓦尔亚那大陆信仰中的神明，他是冥界的统治者，负责管理和收割那些邪恶的灵魂。在瓦尔亚那大陆的历史中，尧一直是一个神秘而的存在。<br>传说中，当一个人死后，他的灵魂会被送到尧的冥界，经过他的审判和选择，才能得到永恒的归宿。因此，尧在人们的心目中拥有着无上的权威和力量，被视为神圣不可侵犯的存在。<br>尧的力量和能力是源于他所收割的灵魂。每当他收割一个灵魂，他就可以从中吸取力量，增强自己的能力。随着收割的灵魂数量的增加，尧的力量也会逐渐增强，变得越来越不可战胜。",
        prefix: "",
        skills: ["vl_nashu_th", "vl_nashu_sg"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "shoushen",
        rank: "legend",
    },
    vl_derk: {
        enable: true,
        name: "德克",
        title: "黯影随行",
        gender: "male",
        bloc: "vl_maozu",
        hp: 4,
        intro: "德克，迦奈尔联邦杰出的数学家，以其群论理论为迦奈尔的工程和社会建设提供了理论指导，并在国防领域推动了禁魔子弹的空气动力学设计，为联邦的安全和国防事业作出了卓越贡献。他是A.W.纪元之后最伟大的数学家之一。",
        prefix: "",
        skills: ["vl_derk_ly", "vl_derk_liuyan"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "vl_furry_migration",
        rank: "junk",
    },
    vl_crow: {
        enable: true,
        name: "克劳",
        title: "智谋慧者",
        gender: "male",
        bloc: "vl_yizu",
        hp: 3,
        intro: "",
        prefix: "",
        skills: ["vl_crow_my", "vl_crow_mc", "vl_crow_td"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "vl_furry_migration",
        rank: "epic",
    },
    vl_dier: {
        enable: true,
        name: "戴尔",
        title: "守龙之护",
        gender: "male",
        bloc: "vl_longzu",
        hp: 4,
        intro: "",
        prefix: "",
        skills: ["vl_dier_sb", "vl_dier_ly", "vl_dier_xy"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "dragongu",
        rank: "epic",
    },
    vl_francium: {
        enable: true,
        name: "弗兰西亚",
        title: "双舞翩翩",
        gender: "male",
        bloc: "vl_guaiwu",
        hp: 3,
        intro: "",
        prefix: "",
        skills: ["vl_francium_ch", "vl_francium_sx", "vl_francium_yl", "vl_francium_mm"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "shoushen",
        rank: "legend",
    },
    vl_kmjia: {
        enable: true,
        name: "卡米加",
        title: "教指人心",
        gender: "male",
        bloc: "vl_quanzu",
        hp: 3,
        intro: "",
        prefix: "",
        skills: ["vl_kamijia_sx", "vl_kamijia_dr"],
        addition: ["zhu"],
        pack: "FurryExt",
        vp: 0,
        sort: "vl_furry_migration",
        rank: "epic",
    },
    vl_liona: {
        enable: true,
        name: "里欧纳",
        title: "整军待战",
        gender: "male",
        bloc: "vl_shizu",
        hp: "4/5",
        intro: "里欧那，生活于兽人王国克拉的贵族家庭，从小就被作为一位战士培养。二十一岁时，在一次前往坷拉进行战斗的过程中，意外拯救了坷拉的公主，后二人暗生情愫。后来在一次战斗中下落不明。",
        prefix: "",
        skills: ["vl_liona_hz", "vl_liona_zz"],
        addition: ["zhu"],
        pack: "FurryExt",
        vp: 0,
        sort: "kela",
        rank: "epic",
    },
    vl_nanci: {
        enable: true,
        name: "南辞",
        title: "狐媚之魂",
        gender: "female",
        bloc: "vl_hulizu",
        hp: 3,
        intro: "南辞，来自人鱼之海的外围，是稀少的狐人族后裔，其天生就拥有化形的能力，能够在人类与兽人的形态之间切换。其能够接收天界的能力并作用于自身。狐人一族曾经是大陆上最为繁盛的兽人种族，但由于其族长妄图破坏大陆的平衡，开凿一个前往其他世界的隧道，法斯降下威能将大部分族人毁灭。而那个通往其他世界的隧道也因此下落不明。",
        prefix: "",
        skills: ["vl_nanci_tx", "vl_nanci_tj"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "renyu",
        rank: "legend",
    },
    vl_shark: {
        enable: true,
        name: "沙克",
        title: "其人之道",
        gender: "male",
        bloc: "vl_haizu",
        hp: 4,
        intro: "沙克，来自人鱼之海的深部，其拥有一颗宝贵的珍珠，约一桅长，此珍珠能够映射出任意人的样貌，并使得拥有者获得相同的能力，据传其和凌月之球的制作者属于同一人。",
        prefix: "",
        skills: ["vl_shark_yz"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "renyu",
        rank: "rare",
    },
    vl_tiger: {
        enable: true,
        name: "泰格尔",
        title: "混元一气",
        gender: "male",
        bloc: "vl_huzu",
        hp: 4,
        intro: "泰格尔，来自兽人王国克拉西部的斯特赖城区域，这里的人们习惯使用剑技来作为防身手段。米亚和科里科特曾在执行任务的时候与其相遇，米亚曾施展所有功力与其切磋，米亚指导其剑术并指出其弱点并与其成为好友。",
        prefix: "",
        skills: ["vl_tiger_hy", "vl_tiger_kf"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "kela",
        rank: "epic",
    },
    vl_linyan: {
        enable: true,
        name: "林&炎",
        title: "双人共舞",
        gender: "male",
        bloc: "vl_langzu",
        hp: 3,
        intro: "林和炎是一对双胞胎，自幼时被父母遗弃，后被米兰寺收养。他们从小就生活于龙之谷外围的米兰寺中，与寺庙的主持相依为命。后来霍恩为了夺取寺庙中的宝物，设计毒杀了住持，而林与炎因外出而逃过一劫。",
        prefix: "",
        skills: ["vl_linyan_kr", "vl_linyan_ys"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "milan",
        rank: "rare",
    },
    vl_horn: {
        enable: true,
        name: "霍恩",
        title: "恶灵推手",
        gender: "male",
        bloc: "vl_yangzu",
        hp: 3,
        intro: "霍恩，据传是来自深渊的恶魔，为了夺取米兰寺的珍贵宝物——豁免权杖，设计杀死了米兰寺的住持。霍恩不喜活物，他常常会放出致死的魔法，杀死周围的一切。",
        prefix: "",
        skills: ["vl_horn_ql", "vl_horn_ll"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "milan",
        rank: "epic",
    },
    vl_zhongyu: {
        enable: true,
        name: "忠与",
        title: "狂火之炎",
        gender: "male",
        bloc: "vl_quanzu",
        hp: 4,
        intro: "忠与，没有人知道其来处，但是在克拉的北部多有其传奇事迹，包括杀死了一只冰霜巨龙等等。人们不知道的是，忠与时刻与自己的内心作斗争，其内心有一只恶魔，当完全释放时，将给世界带来疯狂与灾难。",
        prefix: "",
        skills: ["vl_zhongyu_ky", "vl_zhongyu_zb"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "youdangzhe",
        rank: "legend",
    },
    vl_hynea: {
        enable: true,
        name: "哈尼亚",
        title: "登峰造极",
        gender: "male",
        bloc: "vl_quanzu",
        hp: 4,
        intro: "",
        prefix: "",
        skills: ["vl_hynea_cg", "vl_hynea_ds", "vl_hynea_rx"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "vl_furry_migration",
        rank: "rare",
    },
    vl_wore: {
        enable: true,
        name: "沃尔",
        title: "千变万化",
        gender: "male",
        bloc: "vl_langzu",
        hp: 4,
        intro: "沃尔，生活在迦奈尔联邦，职业为心理医生，曾前往克拉研习催眠术，其原本为沃尔为免服役人员，但在其强烈要求下，进入联邦军队成为战地心理医生。在服役五年后又要求回到家乡科马——联邦南部的一座小城市",
        prefix: "",
        skills: ["vl_wore_hy"],
        addition: ["zhu"],
        pack: "FurryExt",
        vp: 0,
        sort: "jianaier",
        rank: "rare",
    },
    vl_tiers: {
        enable: true,
        name: "缇尔斯",
        title: "战场玫瑰",
        gender: "female",
        bloc: "vl_tuzu",
        hp: 3,
        intro: "缇尔斯，生活在迦奈尔联邦，由于联邦周围大量禁魔矿石的影响，此处无法施展魔法，故此处的主要研究方向为科技。缇尔斯幼时丧父，与母亲相依为命，后进入联邦军队，在服役5年后因在与矮人的战争中负伤，回到家乡科马修养。",
        prefix: "",
        skills: ["vl_tiers_qp", "vl_tiers_kh"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "jianaier",
        rank: "rare",
    },
    vl_wes: {
        enable: true,
        name: "维斯",
        title: "同生共死",
        gender: "male",
        bloc: "vl_longzu",
        hp: 3,
        intro: "维斯，生活在克拉北部的小镇米拉亚纳行省，毗邻吸血鬼禁区。由于附近丰富的魔力资源影响，维斯从小便表现出了强烈的魔法亲和性，其能力能够转移其他人受到的伤害。由于其能力的特殊性，自小其就被送往当地教会培养。",
        prefix: "",
        skills: ["vl_wes_ts", "vl_wes_gs", "vl_wes_lt"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "kela",
        rank: "legend",
    },
    vl_sam: {
        enable: true,
        name: "山",
        title: "死战不休",
        gender: "male",
        bloc: "vl_huzu",
        hp: 4,
        intro: "山，克拉最大的黑帮集团——希尔特黑帮的首领，其作风狠辣，言出必行，故拥有众多拥趸。其下产业遍布大陆各处，但最大的产业是与侏儒合作的武器锻造。",
        prefix: "",
        skills: ["vl_sam_bz", "vl_sam_wh"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "kela",
        rank: "epic",
    },
    vl_fengkn: {
        enable: true,
        name: "冯·莱卡恩",
        title: "筹谋划策",
        gender: "male",
        bloc: "vl_langzu",
        hp: 4,
        intro: "",
        prefix: "",
        skills: ["vl_muli_cm", "vl_muli_yl"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "vl_furry_migration",
        rank: "common",
    },
    vl_muliy: {
        enable: true,
        name: "穆里耶",
        title: "峰回路转",
        gender: "female",
        bloc: "vl_hulizu",
        hp: 3,
        intro: "",
        prefix: "",
        skills: ["vl_mliy_lf", "vl_mliy_hx"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "vl_furry_migration",
        rank: "rare",
    },
    vl_sier: {
        enable: true,
        name: "希尔",
        title: "降龙伏虎",
        gender: "male",
        bloc: "vl_longzu",
        hp: 3,
        intro: "",
        prefix: "",
        skills: ["vl_sier_xl", "vl_sier_fh", "vl_sier_ql"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "dragongu",
        rank: "rare",
    },
    vl_klif: {
        enable: true,
        name: "克里夫",
        title: "追猎者",
        gender: "male",
        bloc: "vl_jiqi",
        hp: 3,
        intro: "",
        prefix: "",
        skills: ["vl_krif_zl", "vl_krif_lj"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "jixiezaowu",
        rank: "rare",
    },
    vl_milis: {
        enable: true,
        name: "弥斯利",
        title: "铸刃千口",
        gender: "male",
        bloc: "vl_xiongzu",
        hp: 3,
        intro: "",
        prefix: "",
        skills: ["vl_mislee_jx", "vl_mislee_tj", "vl_mislee_zr"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "vl_furry_migration",
        rank: "junk",
    },
    vl_alas: {
        enable: true,
        name: "奥拉斯",
        title: "破空断魂",
        gender: "male",
        bloc: "vl_quanzu",
        hp: 4,
        intro: "",
        prefix: "",
        skills: ["vl_olas_fh", "vl_olas_bx"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "vl_furry_migration",
        rank: "common",
    },
    vl_kesaya: {
        enable: true,
        name: "克萨亚",
        title: "无影无踪",
        gender: "male",
        bloc: "vl_huzu",
        hp: 2,
        intro: "克萨亚，暗影佣兵团个人能力最强的成员，但是行事莽撞，需要其他人的指挥。克萨亚十分仰慕团长斯克瑞，其卧室内都是斯克瑞的照片和通缉令（据雷恩斯所说）。克萨亚能够通过自己的血液将自己融入暗影，但是对自己的消耗过大，因此斯克瑞总是安排他做一些无关紧要的任务。",
        prefix: "",
        skills: ["vl_kesaya_zw", "vl_kesaya_wy", "vl_kesaya_ax"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "franying",
        rank: "legend",
    },
    vl_ken: {
        enable: true,
        name: "科恩",
        title: "机器之心",
        gender: "male",
        bloc: "vl_jiqi",
        hp: 4,
        intro: "",
        prefix: "",
        skills: ["vl_ken_jj", "vl_ken_yn", "vl_ken_pb"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "jixiezaowu",
        rank: "epic",
    },
    vl_west: {
        enable: true,
        name: "韦斯特",
        title: "仁心医者",
        gender: "male",
        bloc: "vl_quanzu",
        hp: 3,
        intro: "",
        prefix: "",
        skills: ["vl_west_pz", "vl_west_sx", "vl_west_jh"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "vl_furry_migration",
        rank: "rare",
    },
    vl_huye: {
        enable: true,
        name: "虎爷",
        title: "梦魂归乡",
        gender: "male",
        bloc: "vl_huzu",
        hp: 4,
        intro: "",
        prefix: "",
        skills: ["vl_huye_ms", "vl_huye_jj", "vl_huye_hr"],
        addition: ["zhu"],
        pack: "FurryExt",
        vp: 0,
        sort: "vl_furry_migration",
        rank: "junk",
    },
    vl_milite: {
        enable: true,
        name: "巴兹",
        title: "疑计丛生",
        gender: "male",
        bloc: "vl_longzu",
        hp: 7,
        intro: "",
        prefix: "",
        skills: ["vl_milite_sz", "vl_milite_yj"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "dragongu",
        rank: "rare",
    },
    vl_jackson: {
        enable: true,
        name: "赛特",
        title: "沙之使徒",
        gender: "male",
        bloc: "vl_quanzu",
        hp: 3,
        intro: "",
        prefix: "",
        skills: ["vl_jackson_eb", "vl_jackson_tm", "vl_site_qj"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "vl_furry_migration",
        rank: "rare",
    },
    vl_jiejie: {
        enable: true,
        name: "檞界",
        title: "饮血剑法",
        gender: "male",
        bloc: "vl_langzu",
        hp: 3,
        intro: "檞界，生活在克拉王城外郊，学习木系魔法与剑术，曾与米亚切磋剑术但是惜败。檞界的剑据说时来自深渊的矿石制成，因此天然带有魔法亲和力。据说此矿石若与禁魔石混合点燃，便会发生剧烈的爆炸，但是否有此事尚未可知。",
        prefix: "",
        skills: ["vl_jiejie_zr", "vl_jiejie_zf", "vl_jiejie_my"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "kela",
        rank: "common",
    },
    vl_sayisu: {
        enable: true,
        name: "萨伊苏",
        title: "兵不血刃",
        gender: "male",
        bloc: "vl_longzu",
        hp: 4,
        intro: "",
        prefix: "",
        skills: ["vl_sayisu_fj"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "dragongu",
        rank: "common",
    },
    vl_telina: {
        enable: true,
        name: "特丽娜",
        title: "预见之眼",
        gender: "female",
        bloc: "vl_langzu",
        hp: 3,
        intro: "特丽娜拥有特殊的「未来视」能力，她能够预知近至下一秒，远至数年的所有事件。在「瓦尔亚那百科全书」完成编写后，精灵族就在寻找拥有预言能力的人。因此特丽娜成为第一个受邀进入万灵之森的兽人。",
        prefix: "",
        skills: ["vl_telina_hs", "vl_telina_th"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "wanling",
        rank: "junk",
    },
    vl_oert: {
        enable: true,
        name: "欧尔特",
        title: "轮回使者",
        gender: "male",
        bloc: "shen",
        hp: 4,
        intro: "轮回之神欧尔特，不像其他的神那样高高在上。据传，欧尔特曾在瓦尔亚娜大陆最重要的节日“「火灵日」”，亲自来到瓦尔亚娜大陆的一座山峰上为瓦尔亚娜的百姓祈福，并参加兽人族的祭典活动。而受他惠顾的小贩说到：“神灵大人最喜欢我们家的丸子。”虽然真假未可知。",
        prefix: "",
        skills: ["vl_oert_lh", "vl_oert_wy"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "shoushen",
        rank: "epic",
    },
    vl_rest: {
        enable: true,
        name: "瑞斯特",
        title: "兴风作浪",
        gender: "male",
        bloc: "vl_haizu",
        hp: 3,
        intro: "瑞斯特，生于人鱼之海附近，虽说当地兽人族与鱼人族的关系并不融洽，但瑞斯特算是少有的与两族同时交好的人，其目前在二者之间经商。",
        prefix: "",
        skills: ["vl_rest_qf", "vl_rest_nb"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "renyu",
        rank: "rare",
    },
    vl_tery: {
        enable: true,
        name: "特瑞",
        title: "千变万化",
        gender: "male",
        bloc: "vl_langzu",
        hp: "1/4",
        intro: "特瑞，出生于迦奈尔联邦，其能力极为罕见，虽在大量禁魔矿脉附近，却依然能够释放魔法，其能够从其他人释放的魔法中解析咒文，并快速学习。但其能力仍有限制，其对于不使用魔法或魔法能力过强者无法复制。后来，特瑞加入了「暗影」刺杀队并成为了其中的二把手，主要负责高难度人物和照顾团队起居。",
        prefix: "",
        skills: ["vl_tery_hx", "vl_tery_sg"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "franying",
        rank: "legend",
    },
    vl_lens: {
        enable: true,
        name: "雷恩斯",
        title: "元素法师",
        gender: "male",
        bloc: "vl_longzu",
        hp: 3,
        intro: "雷恩斯，「暗影」刺杀队的队员之一，作为罕见的龙族，天生能够亲和各种魔法元素。其中，雷恩斯对雷和火元素的亲和最为突出。虽然其作为法师却加入了刺客佣兵团的原因或未可知，但是其出色的能力还是为整个小队带来了极大的方便。",
        prefix: "",
        skills: ["vl_lens_yl", "vl_lens_rj"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "franying",
        rank: "rare",
    },
    vl_lusiya: {
        enable: true,
        name: "卢西亚",
        title: "天慧之才",
        gender: "male",
        bloc: "vl_longzu",
        hp: 3,
        intro: "卢西亚，曾就读于人类王国「魔法学院」，与沃里克为好友。其智力超群，并且在学习魔法方面有着很高的造诣。在魔法学院的时期他曾经创立过自己的魔法研究所「时空之门」，并在某双系法师的帮助下，还原了时空魔法的原理。由此卢西亚还未毕业的时候便已经获得了学院授予的最高荣誉。",
        prefix: "",
        skills: ["vl_luciya_yc", "vl_luciya_xl", "vl_luciya_hl"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "xueyuan",
        rank: "epic",
    },
    vl_kersm: {
        enable: true,
        name: "科尔森",
        title: "盟国之约",
        gender: "male",
        bloc: "vl_baozu",
        hp: 4,
        intro: "科尔森，「流亡者」佣兵团的经理，与「赏金公会」进行任务对接。虽然科尔森看起来十分和善，但所有佣兵团的人都知道，科尔森是最不能惹的人。其特殊能力未知，但据说十分强力，能够与十级法师平手。",
        prefix: "",
        skills: ["vl_kersm_my", "vl_kersm_jq"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "yongbing",
        rank: "epic",
    },
    vl_kert: {
        enable: true,
        name: "柯尔特",
        title: "掠魂动魄",
        gender: "male",
        bloc: "vl_quanzu",
        hp: 4,
        intro: "柯尔特，「流亡者」佣兵团的最年轻的成员，由于其对枪械十分精通，因此其在火力掩护的方面有极其重要的作用。他也被团长所赏识，现在小队里都默认他将是下一任团长。柯尔特的身体曾被迦奈尔联邦改造，因此其能够适应各种极端的环境。其最出名的一次任务就是受到神秘的精灵族委托，去寻找能够复活生命之树的元素之泉。",
        prefix: "",
        skills: ["vl_kert_lp", "vl_kert_jl"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "yongbing",
        rank: "rare",
    },
    vl_keya: {
        enable: true,
        name: "苍月狼兽",
        title: "佣兵团长",
        gender: "male",
        bloc: "vl_langzu",
        hp: 4,
        intro: "苍月狼兽，「流亡者」佣兵团的现任团长，擅长于掩护队友和压制对手。苍月狼兽曾经是迦奈尔联邦的逃犯，后来进入赏金工会，受到会长的赏识，通过政治庇护免除了他的罪行。因此其现在正在为赏金工会工作。",
        prefix: "",
        skills: ["vl_kaye_jy", "vl_kaye_yj"],
        addition: ["zhu"],
        pack: "FurryExt",
        vp: 0,
        sort: "yongbing",
        rank: "rare",
    },
    vl_harald: {
        enable: true,
        name: "哈拉尔",
        title: "兽族王者",
        gender: "male",
        bloc: "vl_shizu",
        hp: 4,
        intro: "哈拉尔，生于克拉北境的贫苦农民家庭，由于国王盖尔德鲁的残暴统治和严苛税赋，哈拉尔所在的伊斯曼省份发动起义，而哈拉尔因为其的卓越军事天赋被选为领袖并成功推翻了原国王的残暴统治，哈拉尔上任后立刻开始着手修复前任国王造成的经济破坏，成功使得克拉从动荡中稳定下来。由于他的卓越功勋，受到他恩惠的人们赞颂他为“圣明王”。",
        prefix: "",
        skills: ["vl_harald_fy", "vl_harald_zb"],
        addition: ['zhu'],
        pack: "FurryExt",
        vp: 0,
        sort: "kela",
        rank: "legend",
    },
    vl_klier: {
        enable: true,
        name: "克莱尔",
        title: "坚实后盾",
        gender: "male",
        bloc: "vl_huzu",
        hp: 3,
        intro: "克莱尔，「流亡者」的成员之一，也许对于其他成员来说，克莱尔的能力并不是最为突出的，但是他确实是行事最为稳重的那个。克莱尔虽然看起来大大咧咧，但是在所有任务中，他均表现出了极其可靠的能力和细心，属于是粗中有细。据柯尔特所言，克莱尔目前似乎已经找到了自己的伴侣，而且似乎有打算退出佣兵团。",
        prefix: "",
        skills: ["vl_kelaier_dh", "vl_kelaier_ty"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "yongbing",
        rank: "rare",
    },
    vl_lint: {
        enable: true,
        name: "林特",
        title: "制衡掣肘",
        gender: "male",
        bloc: "vl_niuzu",
        hp: 4,
        intro: "",
        prefix: "",
        skills: ["vl_lint_nd"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "vl_furry_migration",
        rank: "rare",
    },
    vl_berg: {
        enable: true,
        name: "伯格",
        title: "镜花水月",
        gender: "male",
        bloc: "vl_langzu",
        hp: 3,
        intro: "",
        prefix: "",
        skills: ["vl_berg_sy", "vl_berg_jh"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "dragongu",
        rank: "epic",
    },
    vl_markn: {
        enable: true,
        name: "马克恩",
        title: "洞中窾会",
        gender: "male",
        bloc: "vl_langzu",
        hp: 3,
        intro: "",
        prefix: "",
        skills: ["vl_markn_yz", "vl_markn_yc"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "vl_furry_migration",
        rank: "epic",
    },
    vl_morly: {
        enable: true,
        name: "莫雷",
        title: "枪林弹雨",
        gender: "male",
        bloc: "vl_zhuzu",
        hp: 4,
        intro: "",
        prefix: "",
        skills: ["vl_morly_ld", "vl_morly_xd", "vl_morly_qy"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "vl_furry_migration",
        rank: "common",
    },
    vl_marxya: {
        enable: true,
        name: "马尔西亚",
        title: "谨小慎微",
        gender: "male",
        bloc: "vl_longzu",
        hp: 3,
        intro: "",
        prefix: "",
        skills: ["vl_marcia_us", "vl_marcia_jz", "vl_marcia_ql"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "dragongu",
        rank: "epic",
    },
    vl_yas_klin: {
        enable: true,
        name: "亚瑟",
        title: "祭天请神",
        gender: "male",
        bloc: "shen",
        hp: 4,
        intro: "",
        prefix: "",
        skills: ["vl_yas_klin_bj", "vl_yas_klin_js"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "vl_furry_migration",
        rank: "legend",
    },
    vl_patxi: {
        enable: true,
        name: "帕茨希",
        title: "以身殉戒",
        gender: "male",
        bloc: "vl_langzu",
        hp: 4,
        intro: "",
        prefix: "",
        skills: ["vl_patxi_fs", "vl_patxi_yw"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "vl_furry_migration",
        rank: "rare",
    },
    vl_zeron: {
        enable: true,
        name: "泽罗恩",
        title: "以牙还牙",
        gender: "male",
        bloc: "vl_haizu",
        hp: 4,
        intro: "泽罗恩，人鱼之海著名“胡子海盗团”的现任船长，他作为一位船长可谓是尽职尽责，或者对他来说每一位船员都是他的朋友。泽罗恩小时候便因父亲的家庭暴力失去了母亲，父亲整日酗酒对他不管不顾，甚至拳脚相加。这也导致泽罗恩没法上学而早早成为了一名海盗。泽罗恩成为海盗是因为他亲自手刃了自己的父亲被通缉，只能落草为寇。他信奉的信条便是“以牙还牙，以眼还眼”，如果你是他的朋友，他会对你百般纵容，如果你是他的敌人，他则会负责让你去见神明。",
        prefix: "",
        skills: ["vl_zeron_sx"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "renyu",
        rank: "common",
    },
    vl_nore: {
        enable: true,
        name: "诺尔",
        title: "观微洞察",
        gender: "male",
        bloc: "vl_langzu",
        hp: 4,
        intro: "",
        prefix: "",
        skills: ["vl_nore_dz", "vl_nore_ys"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "vl_furry_migration",
        rank: "rare",
    },
    vl_delta: {
        enable: true,
        name: "德尔塔",
        title: "破瞬之斩",
        gender: "male",
        bloc: "vl_quanzu",
        hp: 4,
        intro: "",
        prefix: "",
        skills: ["vl_delta_sy", "vl_delta_sz"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "vl_furry_migration",
        rank: "legend",
    },
    vl_edmon: {
        enable: true,
        name: "埃德蒙",
        title: "以死护全",
        gender: "male",
        bloc: "vl_langzu",
        hp: 4,
        intro: "",
        prefix: "",
        skills: ["vl_edmond_jz", "vl_edmond_jj"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "vl_furry_migration",
        rank: "common",
    },
    vl_peter_likes: {
        enable: true,
        name: "皮特莱克",
        title: "操魂控魄",
        gender: "male",
        bloc: "vl_langzu",
        hp: 3,
        intro: "皮特莱克，出生于一个传统的兽人家庭，父亲以制作玩偶为生。在一次意外之后，皮特获得了特殊的能力，能够操纵别人的意识。如此强大的能力却没有被其滥用，而是用来帮助更多人。",
        prefix: "",
        skills: ["vl_peterlk_kh", "vl_peterlk_jn"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "kela",
        rank: "legend",
    },
    vl_nulia: {
        enable: true,
        name: "怒力亚",
        title: "渡化万物",
        gender: "male",
        bloc: "vl_niuzu",
        hp: 4,
        intro: "",
        prefix: "",
        skills: ["vl_nulia_dh", "vl_nulia_hj"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "vl_furry_migration",
        rank: "rare",
    },
    vl_terlk: {
        enable: true,
        name: "特尔里克",
        title: "披荆斩棘",
        gender: "male",
        bloc: "vl_quanzu",
        hp: 4,
        intro: "",
        prefix: "",
        skills: ["vl_terlk_zj", "vl_terlk_pj"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "vl_furry_migration",
        rank: "rare",
    },
    vl_verb: {
        enable: true,
        name: "韦贝尔",
        title: "绝处逢生",
        gender: "male",
        bloc: "vl_shuzu",
        hp: 3,
        intro: "",
        prefix: "",
        skills: ["vl_verb_zy", "vl_verb_fs"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "youdangzhe",
        rank: "epic",
    },
    vl_dragon: {
        enable: true,
        name: "德拉贡",
        title: "黑焰之龙",
        gender: "male",
        bloc: "vl_longzu",
        hp: 4,
        intro: "",
        prefix: "",
        skills: ["vl_dragon_hy", "vl_dragon_ly", "vl_dragon_hn"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "dragongu",
        rank: "epic",
    },
    vl_terz: {
        enable: true,
        name: "斑点",
        title: "审时度势",
        gender: "male",
        bloc: "vl_quanzu",
        hp: 4,
        intro: "",
        prefix: "",
        skills: ["vl_terz_sp", "vl_terz_fz", "vl_terz_ts"],
        addition: ["forbidai"],
        pack: "FurryExt",
        vp: 0,
        sort: "vl_furry_migration",
        rank: "legend",
    },
    vl_jet: {
        enable: true,
        name: "杰特",
        title: "混乱之神",
        gender: "male",
        bloc: "shen",
        hp: 3,
        intro: "",
        prefix: "",
        skills: ["vl_jet_fy", "vl_jet_ww", "vl_jet_sl", "vl_jet_cl"],
        addition: ["hiddenSkill"],
        pack: "FurryExt",
        vp: 0,
        sort: "shoushen",
        rank: "legend",
    },
    vl_slen: {
        enable: true,
        name: "萨冷",
        title: "八面玲珑",
        gender: "male",
        bloc: "vl_langzu",
        hp: 3,
        intro: "",
        prefix: "",
        skills: ["vl_slen_xj", "vl_slen_gc"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "vl_furry_migration",
        rank: "epic",
    },
    vl_paers: {
        enable: true,
        name: "帕尔斯",
        title: "斗转星移",
        gender: "male",
        bloc: "vl_hulizu",
        hp: 4,
        intro: "",
        prefix: "",
        skills: ["vl_paers_fy", "vl_pares_xh"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "vl_furry_migration",
        rank: "epic",
    },
    vl_nier: {
        enable: true,
        name: "尼尔",
        title: "智解万象",
        gender: "male",
        bloc: "vl_hulizu",
        hp: 3,
        intro: "尼尔，生活在万灵之森中的神秘狐人，他曾言自己见过《瓦尔亚那百科》的原本，因此获得了强大的智慧，能够看穿事物的本质。他崇尚自然和和平，对一切破坏自然的人都会不假辞色。他在弈法和弈风前往万灵之森后看中他们的天赋，并将它们收为弟子。与其说是师傅，尼尔更不如说是他们的父亲一般的角色。",
        prefix: "",
        skills: ["vl_nier_zj"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "wanling",
        rank: "junk",
    },
    vl_pluvia: {
        enable: true,
        name: "普鲁维亚",
        title: "治疗之刃",
        gender: "male",
        bloc: "vl_langzu",
        hp: 4,
        intro: "",
        prefix: "",
        skills: ["vl_pluvia_fs", "vl_pluvia_sx", "vl_pluvia_xs"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "vl_furry_migration",
        rank: "common",
    },
    vl_ventus: {
        enable: true,
        name: "凡图斯",
        title: "泣血之刃",
        gender: "male",
        bloc: "vl_langzu",
        hp: 4,
        intro: "",
        prefix: "",
        skills: ["vl_ventus_nx", "vl_ventus_yc"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "vl_furry_migration",
        rank: "common",
    },
    vl_knier: {
        enable: true,
        name: "科妮尔",
        title: "花非花，雾非雾",
        gender: "female",
        bloc: "vl_langzu",
        hp: 3,
        intro: "",
        prefix: "",
        skills: ["vl_knier_yc", "vl_knier_wh", "vl_knier_hp"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "vl_furry_migration",
        rank: "legend",
    },
    vl_zenia: {
        enable: true,
        name: "泽妮雅",
        title: "余音绕梁",
        gender: "female",
        bloc: "vl_hulizu",
        hp: 3,
        intro: "",
        prefix: "",
        skills: ["vl_zenia_yy", "vl_zenia_ys", "vl_zenia_ld"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "vl_furry_migration",
        rank: "common",
    },
    vl_lamost: {
        enable: true,
        name: "拉莫斯特",
        title: "犹记繁华",
        gender: "male",
        bloc: "vl_langzu",
        hp: 4,
        intro: "",
        prefix: "",
        skills: ["vl_lamost_zf"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "vl_furry_migration",
        rank: "common",
    },
    vl_kasaers: {
        enable: true,
        name: "卡萨尔斯",
        title: "狂狼怒吼",
        gender: "male",
        bloc: "vl_langzu",
        hp: 4,
        intro: "",
        prefix: "",
        skills: ["vl_kasers_yz", "vl_kasers_kb"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "vl_furry_migration",
        rank: "legend",
    },
    vl_jgby: {
        enable: true,
        name: "吉岡邦彦",
        title: "狂炎灼冰",
        gender: "male",
        bloc: "vl_langzu",
        hp: 4,
        intro: "",
        prefix: "",
        skills: ["vl_jbgy_qx", "vl_jbgy_ze"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "vl_furry_migration",
        rank: "epic",
    },
    vl_liya: {
        enable: true,
        name: "莉亚",
        title: "动运千机",
        gender: "female",
        bloc: "vl_hulizu",
        hp: 3,
        intro: "莉亚生于兽人王国中部的商业中心——恩特城，是兽人王国国王哈拉尔的独女。作为贵族女子的她，自小时候便被灌输各种各样的贵族礼仪，但她的生性不羁，时时让自己的父亲紧张。她在16岁时，曾收到过哈拉尔赠送的重装机车，是她最喜欢的生日礼物。",
        prefix: "",
        skills: ["vl_liya_sz", "vl_liya_sj", "vl_liya_yy"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "kela",
        rank: "junk",
    },
    vl_laays: {
        enable: true,
        name: "拉亚斯",
        title: "镣铐游荡者",
        gender: "male",
        bloc: "vl_langzu",
        hp: 4,
        intro: "“像这样四处游荡，又过了多久呢？”拉亚斯的话语回荡在旷野上。自从那场人类与精灵的大战以人类的完全胜利为结局，拉亚斯也不知道自己游荡多久了。他是当年参加过此次战争的兽人族战士，后牺牲于战火之中。也许是生命树被毁的缘故，拉亚斯重新得到肉体复活。",
        prefix: "",
        skills: ["vl_laays_cs"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "youdangzhe",
        rank: "junk",
    },
    vl_bladewolf: {
        enable: true,
        name: "刃狼",
        title: "机魂熔炉",
        gender: "male",
        bloc: "vl_jiqi",
        hp: 4,
        intro: "刃狼，是产于迦奈尔联邦的机器人，由于其驱动需要大量的电力，因此刃狼作为该型号唯一的机器人被装载了核动力反应堆。刃狼的生产目的是为了战争，因此其功能也被特化为战争相关，并卸除了情感模块。但是后来因一些机缘巧合，被西普感化并重新获得了情感，在其死后将其带回并改造为了机械生命。",
        prefix: "",
        skills: ["vl_bladewolf_qp", "vl_bladewolf_rh"],
        addition: ["forbidai"],
        pack: "FurryExt",
        vp: 0,
        sort: "jixiezaowu",
        rank: "legend",
    },
    vl_sheep: {
        enable: true,
        name: "西普",
        title: "能机巧算",
        gender: "female",
        bloc: "vl_jiqi",
        hp: 3,
        intro: "西普，原生活于克拉，是出生于贫民窟的普通兽人；在哈拉尔国王上任前的那位国王——盖尔德鲁，是一位不折不扣的暴君，他欺压百姓并强迫贫民窟的人们前往战场。西普不幸被选中，后在战场上遇到了战争机器人——刃狼，经历一系列事件之后，西普成功使得刃狼获得了感情并相爱。后来再一次意外中，西普战死。刃狼将其带回并改造为机械生命。但是由于死去过久，其记忆没有被继承，现在将刃狼当作自己的哥哥。",
        prefix: "",
        skills: ["vl_sheep_jf", "vl_sheep_rh"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "jixiezaowu",
        rank: "legend",
    },
    vl_kulun_light: {
        enable: true,
        name: "库伦·光明",
        title: "",
        gender: "male",
        bloc: "vl_langzu",
        hp: 1,
        intro: "",
        prefix: "",
        skills: ["vl_kulun_light_sg", "vl_kulun_light_yb"],
        addition: ['unseen'],
        pack: "FurryExt",
        vp: 0,
        sort: "vl_furry_migration",
        rank: "epic",
    },
    vl_kulun_dark: {
        enable: true,
        name: "库伦·黑暗",
        title: "",
        gender: "male",
        bloc: "vl_langzu",
        hp: 1,
        intro: "",
        prefix: "",
        skills: ["vl_kulun_dark_as", "vl_kulun_dark_yb"],
        addition: ['unseen'],
        pack: "FurryExt",
        vp: 0,
        sort: "vl_furry_migration",
        rank: "epic",
    },
    vl_kulun_wind: {
        enable: true,
        name: "库伦·飓风",
        title: "",
        gender: "male",
        bloc: "vl_langzu",
        hp: 1,
        intro: "",
        prefix: "",
        skills: ["vl_kulun_wind_wx", "vl_kulun_wind_cm"],
        addition: ['unseen'],
        pack: "FurryExt",
        vp: 0,
        sort: "vl_furry_migration",
        rank: "epic",
    },
    vl_kulun_fire: {
        enable: true,
        name: "库伦·火焰",
        title: "",
        gender: "male",
        bloc: "vl_langzu",
        hp: 1,
        intro: "",
        prefix: "",
        skills: ["vl_kulun_fire_ly", "vl_kulun_fire_fz"],
        addition: ['unseen'],
        pack: "FurryExt",
        vp: 0,
        sort: "vl_furry_migration",
        rank: "epic",
    },
    vl_kulun_water: {
        enable: true,
        name: "库伦·潮汐",
        title: "",
        gender: "male",
        bloc: "vl_langzu",
        hp: 1,
        intro: "",
        prefix: "",
        skills: ["vl_kulun_water_sy", "vl_kulun_water_jy"],
        addition: ['unseen'],
        pack: "FurryExt",
        vp: 0,
        sort: "vl_furry_migration",
        rank: "epic",
    },
    vl_kulun_ice: {
        enable: true,
        name: "库伦·寒冰",
        title: "",
        gender: "male",
        bloc: "vl_langzu",
        hp: 1,
        intro: "",
        prefix: "",
        skills: ["vl_kulun_ice_hs", "vl_kulun_ice_dj"],
        addition: ['unseen'],
        pack: "FurryExt",
        vp: 0,
        sort: "vl_furry_migration",
        rank: "epic",
    },
    vl_kulun_metal: {
        enable: true,
        name: "库伦·金属",
        title: "",
        gender: "male",
        bloc: "vl_langzu",
        hp: 1,
        intro: "",
        prefix: "",
        skills: ["vl_kulun_metal_zl", "vl_kulun_metal_rh"],
        addition: ['unseen'],
        pack: "FurryExt",
        vp: 0,
        sort: "vl_furry_migration",
        rank: "epic",
    },
    vl_kulun_nature: {
        enable: true,
        name: "库伦·自然",
        title: "",
        gender: "male",
        bloc: "vl_langzu",
        hp: 1,
        intro: "",
        prefix: "",
        skills: ["vl_kulun_nature_hc", "vl_kulun_nature_tw"],
        addition: ['unseen'],
        pack: "FurryExt",
        vp: 0,
        sort: "vl_furry_migration",
        rank: "epic",
    },
    vl_kulun_dirt: {
        enable: true,
        name: "库伦·大地",
        title: "",
        gender: "male",
        bloc: "vl_langzu",
        hp: 1,
        intro: "",
        prefix: "",
        skills: ["vl_kulun_dirt_zw", "vl_kulun_dirt_zj"],
        addition: ['unseen'],
        pack: "FurryExt",
        vp: 0,
        sort: "vl_furry_migration",
        rank: "epic",
    },
    vl_kulun_thunder: {
        enable: true,
        name: "库伦·雷电",
        title: "",
        gender: "male",
        bloc: "vl_langzu",
        hp: 1,
        intro: "",
        prefix: "",
        skills: ["vl_kulun_thunder_yl", "vl_kulun_thunder_dl"],
        addition: ['unseen'],
        pack: "FurryExt",
        vp: 0,
        sort: "vl_furry_migration",
        rank: "epic",
    },
    vl_kulun: {
        enable: true,
        name: "库伦",
        title: "元素引导者",
        gender: "male",
        bloc: "vl_langzu",
        hp: 1,
        intro: "&nbsp&nbsp&nbsp&nbsp库伦，出生于克拉王国，具有卓越的魔法天赋。在魔法学院的学习年月里，库伦积累了深厚的魔法知识，并发明了一根号称“扭称”的特殊法杖，能够将两种元素力量注入其中并维持其平衡。\n            <br>&nbsp&nbsp&nbsp&nbsp后来，他偶然发现了一个神秘的泉眼，这个泉眼融合了各种元素的能量，释放着无尽的魔法力量。库伦决定将泉眼视为自己的研究对象，但随着时间的推移，他渐渐被泉眼中的力量所吸引，着魔般地渴望着占有它。他利用“扭称”进行危险的实验，试图掌握泉眼的能量。\n            <br>&nbsp&nbsp&nbsp&nbsp库伦不知道的是，当所有元素被禁锢于同一容器时，它们会相互碰撞和交织，引发了强烈的爆炸。这场爆炸不仅波及了数千人，炸毁了整个魔法师塔，还导致了一场名为“魔力大崩溃”的魔法浩劫，世界的魔力等级骤降，所有人都无法再从世界的魔网中吸取超过十阶的能量。\n            <br>&nbsp&nbsp&nbsp&nbsp魔法，曾经是克拉文明的核心，从此陷入了低谷。而库伦的研究和冒险，无论是对于魔法学的贡献还是对于后世的警示，都将被永远地铭记在瓦尔亚那的历史中。",
        prefix: "",
        skills: ["vl_kulun_gz", "vl_kulun_fs", "vl_kulun_zn", "vl_kulun_skillfilter"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "kela",
        rank: "epic",
    },
    vl_taber: {
        enable: true,
        name: "塔贝尔",
        title: "掘地三尺",
        gender: "male",
        bloc: "vl_langzu",
        hp: 4,
        intro: "",
        prefix: "",
        skills: ["vl_taber_jj", "vl_taber_sj"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "youdangzhe",
        rank: "epic",
    },
    vl_mala: {
        enable: true,
        name: "马拉尔",
        title: "龙裔之王",
        gender: "male",
        bloc: "vl_longzu",
        hp: 4,
        intro: "",
        prefix: "",
        skills: ["vl_mala_ly", "vl_mala_ht"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "shoushen",
        rank: "junk",
    },
    vl_zeta: {
        enable: true,
        name: "泽塔",
        title: "固铸何归？",
        gender: "male",
        bloc: "vl_longzu",
        hp: 4,
        intro: "",
        prefix: "",
        skills: ["vl_zeta_gz", "vl_zeta_fg"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "dragongu",
        rank: "epic",
    },
    vl_shisan: {
        enable: true,
        name: "拾弎",
        title: "察微知宏",
        gender: "male",
        bloc: "vl_longzu",
        hp: 3,
        intro: "",
        prefix: "",
        skills: ["vl_shisan_dg", "vl_shisan_tx"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "dragongu",
        rank: "legend",
    },
    vl_qiushou: {
        enable: true,
        name: "秋收",
        title: "针砭时弊",
        gender: "male",
        bloc: "vl_hulizu",
        hp: 3,
        intro: "",
        prefix: "",
        skills: ["vl_qiushou_yl", "vl_qiushou_qp"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "vl_furry_migration",
        rank: "legend",
    },
    vl_liuqing: {
        enable: true,
        name: "流青",
        title: "兵无常饰",
        gender: "male",
        bloc: "vl_huzu",
        hp: 3,
        intro: "",
        prefix: "",
        skills: ["vl_liuqing_yf", "vl_liuqing_lz"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "vl_furry_migration",
        rank: "legend",
    },
};
