export const furryCharacter = {
    vl_siji: {
        enable: true,
        name: "司稷",
        title: "司农之祖",
        gender: "male",
        bloc: "vl_langzu",
        hp: 3,
        intro: "司稷，生于长河中流，瑞江边的一个部落。刚出生时，因其父未知而被认为是不详，母亲屡次将他抛弃在了山野，却也屡次被动物救助，经此三次后，母亲终于妥协将他带回家中。司稷少时对农业极具兴趣，长大后，改良谷种，并使粮食收获大幅提高，使族民彻底摆脱粮食问题。此后其一生致力于农业，被受命掌管农事与祭祀事物。最后的生命在家中安然睡去。死后被后世封为稷神、司农之祖、农圣。",
        prefix: "",
        skills: ["vl_siji_sx", "vl_siji_jg", "vl_siji_ys"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "vl_furry_migration",
        rank: "epic",
    },
    vl_rabby: {
        enable: true,
        name: "瑞比",
        title: "刑事拘留",
        gender: "female",
        bloc: "vl_tuzu",
        hp: 3,
        intro: "对瑞比来说，每天最为惊心动魄的时刻大概就是追捕犯人。出生于迦奈尔联邦的她，从小便幻想自己是超级英雄，能够消灭一切邪恶。后来她不出所料成为了迦奈尔联邦警局的一员。",
        prefix: "",
        skills: ["vl_rabby_qj", "vl_rabby_xj"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "vl_furry_migration",
        rank: "epic",
    },
    vl_mokalin: {
        enable: true,
        name: "莫卡林",
        title: "坚如磐石",
        gender: "male",
        bloc: "vl_xiongzu",
        hp: 4,
        intro: "莫卡林，随着一阵强光从天而降的神秘熊人。路过万林之森的米亚和科里科特师徒发现了衣不蔽体的他。醒来后，莫卡林虽然尝试与他们沟通，但操着一口异世界的语言的他在尝试融入新世界的路上渐行渐远...<br>即使如此，米亚还是欣然接受了莫卡林进入自己的队伍，并踏上了新的旅程。据莫卡林所言，其是来自另一个世界的某部落首领（科里科特表示怀疑），无意间踏进空间裂隙来到此地，目前还在寻找回去的方法，在了解到这个世界的兽人处境后，他表示很乐意先做些什么再走。",
        prefix: "",
        skills: ["vl_mokalin_sy", "vl_mokalin_dh"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "tuozhanliandong",
        rank: "epic",
    },
    vl_mierk: {
        enable: true,
        name: "米尔克",
        title: "力争神辩",
        gender: "male",
        bloc: "vl_langzu",
        hp: 3,
        intro: "米尔克，米勒的哥哥，生于克拉贵族家庭的他从小就跟随师傅查尔林学习修辞学。后来因为与其师傅的理念不同而分道扬镳，离开了王城。也正因此躲过了后来的政治风波。",
        prefix: "",
        skills: ["vl_mierk_jc", "vl_mierk_fm", "vl_mierk_jingcai"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "vl_furry_migration",
        rank: "epic",
    },
    vl_baixi: {
        enable: true,
        name: "白曦&墨喑",
        title: "阴阳两仪",
        gender: "male",
        bloc: "vl_langzu",
        hp: 3,
        intro: "",
        prefix: "",
        skills: ["vl_baixi_lj", "vl_baixi_lj_change", "vl_baixi_dy", "vl_baixi_bm"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "kechuanjuese",
        rank: "epic",
    },
    vl_luyezhi: {
        enable: true,
        name: "鹿野灸",
        title: "大总攻",
        gender: "male",
        bloc: "vl_luzu",
        hp: 3,
        intro: "",
        prefix: "",
        skills: ["vl_luyezhi_zy", "vl_luyezhi_zye"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "kechuanjuese",
        rank: "epic",
    },
    vl_souls: {
        enable: true,
        name: "莎尔丝",
        title: "魔法少女",
        gender: "female",
        bloc: "vl_hulizu",
        hp: 3,
        intro: "",
        prefix: "",
        skills: ["vl_souls_ch", "vl_souls_mj", "vl_souls_md"],
        addition: [],
        pack: "FurryExt",
        vp: "1/3",
        sort: "vl_furry_migration",
        rank: "epic",
    },
    vl_aak: {
        enable: true,
        name: "阿",
        title: "神医",
        gender: "male",
        bloc: "vl_shizu",
        hp: 4,
        intro: "",
        prefix: "",
        skills: ["vl_aak_yj", "vl_aak_hy", "vl_aak_gj"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "vl_furry_migration",
        rank: "common",
    },
    vl_lucifer: {
        enable: true,
        name: "路西法",
        title: "",
        gender: "male",
        bloc: "vl_langzu",
        hp: 3,
        intro: "路西法，目前为居住在矮人之心洞穴附近的兽人部落首领。其部落信仰生命之神——“特拉克斯”，并获得了其传承的特殊能力。该能力使得其部落的勇士能够与动物沟通，甚至训练动物成为伙伴。拥有这种特殊能力的人在《瓦尔亚那》百科中称为“兽语者”。",
        prefix: "",
        skills: ["vl_lucifer_cc", "vl_lucifer_xz"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "airenzhixin",
        rank: "rare",
    },
    vl_lans: {
        enable: true,
        name: "兰斯",
        title: "",
        gender: "male",
        bloc: "vl_weizhi",
        hp: 3,
        intro: "",
        prefix: "",
        skills: [],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "vl_furry_migration",
        rank: "rare",
    },
    vl_keste: {
        enable: true,
        name: "科斯特",
        title: "常胜将军",
        gender: "male",
        bloc: "vl_langzu",
        hp: 4,
        intro: "科斯特，迦奈尔联邦最年轻也是最年少有为的将军，曾经在与矮人族的战争——“矮人之心争夺战”中大获全胜，歼敌数万。其主导与矮人族签下的《斯兰条约》为迦奈尔联邦的贸易事业奠定了发展基础。因此，这位将军也被成为“尼拉特”将军——即矮人语中的“恶魔”。",
        prefix: "",
        skills: ["vl_keste_yg", "vl_keste_wp"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "jianaier",
        rank: "epic",
    },
    vl_neises: {
        enable: true,
        name: "内瑟斯",
        title: "",
        gender: "male",
        bloc: "vl_quanzu",
        hp: 3,
        intro: "",
        prefix: "",
        skills: ["vl_neises_hb"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "vl_furry_migration",
        rank: "junk",
    },
    vl_nine: {
        enable: true,
        name: "奈恩",
        title: "孤僻的天才",
        gender: "male",
        bloc: "vl_hulizu",
        hp: 3,
        intro: "",
        prefix: "",
        skills: ["vl_nine_fw", "vl_nine_cj", "vl_nine_dx"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "vl_furry_migration",
        rank: "legend",
    },
    vl_thunder: {
        enable: true,
        name: "兰德",
        title: "雷光跃动",
        gender: "male",
        bloc: "vl_langzu",
        hp: 4,
        intro: "",
        prefix: "",
        skills: ["vl_thunder_fz", "vl_thunder_lj"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "vl_furry_migration",
        rank: "epic",
    },
    vl_mouse: {
        enable: true,
        name: "缪斯",
        title: "奇门八卦",
        gender: "female",
        bloc: "vl_shuzu",
        hp: 4,
        intro: "",
        prefix: "",
        skills: ["vl_mouse_bm"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "vl_furry_migration",
        rank: "epic",
    },
    vl_lamas: {
        enable: true,
        name: "拉马斯",
        title: "战技如神",
        gender: "male",
        bloc: "vl_shizu",
        hp: 4,
        intro: "",
        prefix: "",
        skills: ["vl_lamas_zj"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "vl_furry_migration",
        rank: "rare",
    },
    vl_tails: {
        enable: true,
        name: "塔尔斯",
        title: "灵活的机械师",
        gender: "male",
        bloc: "vl_hulizu",
        hp: 3,
        intro: "塔尔斯是一只来自异世界的机械师狐狸，可以使用两条尾巴进行甩尾飞行，且擅长使用和制造各种机械装置。因为意外，他穿越到了瓦尔亚那大陆，一些同伴和七颗神秘的混沌翡翠也一同降临。<br>为了获取散落于各地的混沌翡翠，打通回家之路，塔尔斯和同伴们加入了赏金公会。作为天才机械师，塔尔斯将他的异世界技术巧妙地结合到这个陌生的大陆上，为公会的任务提供了独特的解决方案。<br>不过，回家才是他们的主旋律，这次奇妙的旅行必将在塔尔斯年仅8岁的阅历中留下浓墨重彩的一笔。",
        prefix: "",
        skills: ["vl_tails_jd", "vl_tails_qx"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "vl_furry_migration",
        rank: "legend",
    },
    vl_rasali: {
        enable: true,
        name: "洛",
        title: "善灵指引",
        gender: "male",
        bloc: "shen",
        hp: 3,
        intro: "洛，和尧一样，是瓦尔亚那大陆信仰中的神明之一，执掌着冥界的善灵收集和引导工作。<br>他的责任是寻找那些有着良善灵魂的人们，以便在他们离开世界之前引领他们前往冥界，让他们的灵魂在冥界得到永恒的安息。洛是一位仁慈而有担当的神明，他深知自己肩负的责任，努力工作以确保每个良善的灵魂都能得到引领。他深知冥界对于那些有着良善灵魂的人意味着什么，因此他不惜一切代价来保护他们。",
        prefix: "",
        skills: ["vl_rasali_ly", "vl_rasali_hq"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "shoushen",
        rank: "legend",
    },
    vl_nashu: {
        enable: true,
        name: "尧",
        title: "恶魂使者",
        gender: "male",
        bloc: "shen",
        hp: 4,
        intro: "尧，是瓦尔亚那大陆信仰中的神明，他是冥界的统治者，负责管理和收割那些邪恶的灵魂。在瓦尔亚那大陆的历史中，尧一直是一个神秘而的存在。<br>传说中，当一个人死后，他的灵魂会被送到尧的冥界，经过他的审判和选择，才能得到永恒的归宿。因此，尧在人们的心目中拥有着无上的权威和力量，被视为神圣不可侵犯的存在。<br>尧的力量和能力是源于他所收割的灵魂。每当他收割一个灵魂，他就可以从中吸取力量，增强自己的能力。随着收割的灵魂数量的增加，尧的力量也会逐渐增强，变得越来越不可战胜。",
        prefix: "",
        skills: ["vl_nashu_th", "vl_nashu_sg"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "shoushen",
        rank: "legend",
    },
    vl_liona: {
        enable: true,
        name: "里欧纳",
        title: "整军待战",
        gender: "male",
        bloc: "vl_shizu",
        hp: "4/5",
        intro: "里欧那，生活于兽人王国克拉的贵族家庭，从小就被作为一位战士培养。二十一岁时，在一次前往坷拉进行战斗的过程中，意外拯救了坷拉的公主，后二人暗生情愫。后来在一次战斗中下落不明。",
        prefix: "",
        skills: ["vl_liona_hz", "vl_liona_zz"],
        addition: ["zhu"],
        pack: "FurryExt",
        vp: 0,
        sort: "kela",
        rank: "epic",
    },
    vl_nanci: {
        enable: true,
        name: "南辞",
        title: "狐媚之魂",
        gender: "female",
        bloc: "vl_hulizu",
        hp: 3,
        intro: "南辞，来自人鱼之海的外围，是稀少的狐人族后裔，其天生就拥有化形的能力，能够在人类与兽人的形态之间切换。其能够接收天界的能力并作用于自身。狐人一族曾经是大陆上最为繁盛的兽人种族，但由于其族长妄图破坏大陆的平衡，开凿一个前往其他世界的隧道，法斯降下威能将大部分族人毁灭。而那个通往其他世界的隧道也因此下落不明。",
        prefix: "",
        skills: ["vl_nanci_tx", "vl_nanci_tj"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "renyu",
        rank: "legend",
    },
    vl_tiger: {
        enable: true,
        name: "泰格尔",
        title: "混元一气",
        gender: "male",
        bloc: "vl_huzu",
        hp: 4,
        intro: "泰格尔，来自兽人王国克拉西部的斯特赖城区域，这里的人们习惯使用剑技来作为防身手段。米亚和科里科特曾在执行任务的时候与其相遇，米亚曾施展所有功力与其切磋，米亚指导其剑术并指出其弱点并与其成为好友。",
        prefix: "",
        skills: ["vl_tiger_hy", "vl_tiger_kf"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "kela",
        rank: "epic",
    },
    vl_linyan: {
        enable: true,
        name: "林&炎",
        title: "双人共舞",
        gender: "male",
        bloc: "vl_langzu",
        hp: 3,
        intro: "林和炎是一对双胞胎，自幼时被父母遗弃，后被米兰寺收养。他们从小就生活于龙之谷外围的米兰寺中，与寺庙的主持相依为命。后来霍恩为了夺取寺庙中的宝物，设计毒杀了住持，而林与炎因外出而逃过一劫。",
        prefix: "",
        skills: ["vl_linyan_kr", "vl_linyan_ys"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "milan",
        rank: "rare",
    },
    vl_zhongyu: {
        enable: true,
        name: "忠与",
        title: "狂火之炎",
        gender: "male",
        bloc: "vl_quanzu",
        hp: 4,
        intro: "忠与，没有人知道其来处，但是在克拉的北部多有其传奇事迹，包括杀死了一只冰霜巨龙等等。人们不知道的是，忠与时刻与自己的内心作斗争，其内心有一只恶魔，当完全释放时，将给世界带来疯狂与灾难。",
        prefix: "",
        skills: ["vl_zhongyu_ky", "vl_zhongyu_zb"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "youdangzhe",
        rank: "legend",
    },
    vl_wore: {
        enable: true,
        name: "沃尔",
        title: "千变万化",
        gender: "male",
        bloc: "vl_langzu",
        hp: 4,
        intro: "沃尔，生活在迦奈尔联邦，职业为心理医生，曾前往克拉研习催眠术，其原本为沃尔为免服役人员，但在其强烈要求下，进入联邦军队成为战地心理医生。在服役五年后又要求回到家乡科马——联邦南部的一座小城市",
        prefix: "",
        skills: ["vl_wore_hy"],
        addition: ["zhu"],
        pack: "FurryExt",
        vp: 0,
        sort: "jianaier",
        rank: "rare",
    },
    vl_sam: {
        enable: true,
        name: "山",
        title: "死战不休",
        gender: "male",
        bloc: "vl_huzu",
        hp: 4,
        intro: "山，克拉最大的黑帮集团——希尔特黑帮的首领，其作风狠辣，言出必行，故拥有众多拥趸。其下产业遍布大陆各处，但最大的产业是与侏儒合作的武器锻造。",
        prefix: "",
        skills: ["vl_sam_bz", "vl_sam_wh"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "kela",
        rank: "epic",
    },
    vl_muliy: {
        enable: true,
        name: "穆里耶",
        title: "峰回路转",
        gender: "female",
        bloc: "vl_hulizu",
        hp: 3,
        intro: "",
        prefix: "",
        skills: ["vl_mliy_lf", "vl_mliy_hx"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "vl_furry_migration",
        rank: "rare",
    },
    vl_sier: {
        enable: true,
        name: "希尔",
        title: "降龙伏虎",
        gender: "male",
        bloc: "vl_longzu",
        hp: 3,
        intro: "",
        prefix: "",
        skills: ["vl_sier_xl", "vl_sier_fh", "vl_sier_ql"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "dragongu",
        rank: "rare",
    },
    vl_klif: {
        enable: true,
        name: "克里夫",
        title: "追猎者",
        gender: "male",
        bloc: "vl_jiqi",
        hp: 3,
        intro: "",
        prefix: "",
        skills: ["vl_krif_zl", "vl_krif_lj"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "jixiezaowu",
        rank: "rare",
    },
    vl_milis: {
        enable: true,
        name: "弥斯利",
        title: "铸刃千口",
        gender: "male",
        bloc: "vl_xiongzu",
        hp: 3,
        intro: "",
        prefix: "",
        skills: ["vl_mislee_jx", "vl_mislee_tj", "vl_mislee_zr"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "vl_furry_migration",
        rank: "junk",
    },
    vl_kesaya: {
        enable: true,
        name: "克萨亚",
        title: "无影无踪",
        gender: "male",
        bloc: "vl_huzu",
        hp: 2,
        intro: "克萨亚，暗影佣兵团个人能力最强的成员，但是行事莽撞，需要其他人的指挥。克萨亚十分仰慕团长斯克瑞，其卧室内都是斯克瑞的照片和通缉令（据雷恩斯所说）。克萨亚能够通过自己的血液将自己融入暗影，但是对自己的消耗过大，因此斯克瑞总是安排他做一些无关紧要的任务。",
        prefix: "",
        skills: ["vl_kesaya_zw", "vl_kesaya_wy", "vl_kesaya_ax"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "franying",
        rank: "legend",
    },
    vl_ken: {
        enable: true,
        name: "科恩",
        title: "机器之心",
        gender: "male",
        bloc: "vl_jiqi",
        hp: 4,
        intro: "",
        prefix: "",
        skills: ["vl_ken_jj", "vl_ken_yn", "vl_ken_pb"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "jixiezaowu",
        rank: "epic",
    },
    vl_milite: {
        enable: true,
        name: "巴兹",
        title: "疑计丛生",
        gender: "male",
        bloc: "vl_longzu",
        hp: 7,
        intro: "",
        prefix: "",
        skills: ["vl_milite_sz", "vl_milite_yj"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "dragongu",
        rank: "rare",
    },
    vl_jiejie: {
        enable: true,
        name: "檞界",
        title: "饮血剑法",
        gender: "male",
        bloc: "vl_langzu",
        hp: 3,
        intro: "檞界，生活在克拉王城外郊，学习木系魔法与剑术，曾与米亚切磋剑术但是惜败。檞界的剑据说时来自深渊的矿石制成，因此天然带有魔法亲和力。据说此矿石若与禁魔石混合点燃，便会发生剧烈的爆炸，但是否有此事尚未可知。",
        prefix: "",
        skills: ["vl_jiejie_zr", "vl_jiejie_zf", "vl_jiejie_my"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "kela",
        rank: "common",
    },
    vl_sayisu: {
        enable: true,
        name: "萨伊苏",
        title: "兵不血刃",
        gender: "male",
        bloc: "vl_longzu",
        hp: 4,
        intro: "",
        prefix: "",
        skills: ["vl_sayisu_fj"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "dragongu",
        rank: "common",
    },
    vl_telina: {
        enable: true,
        name: "特丽娜",
        title: "预见之眼",
        gender: "female",
        bloc: "vl_langzu",
        hp: 3,
        intro: "特丽娜拥有特殊的「未来视」能力，她能够预知近至下一秒，远至数年的所有事件。在「瓦尔亚那百科全书」完成编写后，精灵族就在寻找拥有预言能力的人。因此特丽娜成为第一个受邀进入万灵之森的兽人。",
        prefix: "",
        skills: ["vl_telina_hs", "vl_telina_th"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "wanling",
        rank: "junk",
    },
    vl_oert: {
        enable: true,
        name: "欧尔特",
        title: "轮回使者",
        gender: "male",
        bloc: "shen",
        hp: 4,
        intro: "轮回之神欧尔特，不像其他的神那样高高在上。据传，欧尔特曾在瓦尔亚娜大陆最重要的节日“「火灵日」”，亲自来到瓦尔亚娜大陆的一座山峰上为瓦尔亚娜的百姓祈福，并参加兽人族的祭典活动。而受他惠顾的小贩说到：“神灵大人最喜欢我们家的丸子。”虽然真假未可知。",
        prefix: "",
        skills: ["vl_oert_lh", "vl_oert_wy"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "shoushen",
        rank: "epic",
    },
    vl_rest: {
        enable: true,
        name: "瑞斯特",
        title: "兴风作浪",
        gender: "male",
        bloc: "vl_haizu",
        hp: 3,
        intro: "瑞斯特，生于人鱼之海附近，虽说当地兽人族与鱼人族的关系并不融洽，但瑞斯特算是少有的与两族同时交好的人，其目前在二者之间经商。",
        prefix: "",
        skills: ["vl_rest_qf", "vl_rest_nb"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "renyu",
        rank: "rare",
    },
    vl_tery: {
        enable: true,
        name: "特瑞",
        title: "千变万化",
        gender: "male",
        bloc: "vl_langzu",
        hp: "1/4",
        intro: "特瑞，出生于迦奈尔联邦，其能力极为罕见，虽在大量禁魔矿脉附近，却依然能够释放魔法，其能够从其他人释放的魔法中解析咒文，并快速学习。但其能力仍有限制，其对于不使用魔法或魔法能力过强者无法复制。后来，特瑞加入了「暗影」刺杀队并成为了其中的二把手，主要负责高难度人物和照顾团队起居。",
        prefix: "",
        skills: ["vl_tery_hx", "vl_tery_sg"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "franying",
        rank: "legend",
    },
    vl_lens: {
        enable: true,
        name: "雷恩斯",
        title: "元素法师",
        gender: "male",
        bloc: "vl_longzu",
        hp: 3,
        intro: "雷恩斯，「暗影」刺杀队的队员之一，作为罕见的龙族，天生能够亲和各种魔法元素。其中，雷恩斯对雷和火元素的亲和最为突出。虽然其作为法师却加入了刺客佣兵团的原因或未可知，但是其出色的能力还是为整个小队带来了极大的方便。",
        prefix: "",
        skills: ["vl_lens_yl", "vl_lens_rj"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "franying",
        rank: "rare",
    },
    vl_lusiya: {
        enable: true,
        name: "卢西亚",
        title: "天慧之才",
        gender: "male",
        bloc: "vl_longzu",
        hp: 3,
        intro: "卢西亚，曾就读于人类王国「魔法学院」，与沃里克为好友。其智力超群，并且在学习魔法方面有着很高的造诣。在魔法学院的时期他曾经创立过自己的魔法研究所「时空之门」，并在某双系法师的帮助下，还原了时空魔法的原理。由此卢西亚还未毕业的时候便已经获得了学院授予的最高荣誉。",
        prefix: "",
        skills: ["vl_luciya_yc", "vl_luciya_xl", "vl_luciya_hl"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "xueyuan",
        rank: "epic",
    },
    vl_kersm: {
        enable: true,
        name: "科尔森",
        title: "盟国之约",
        gender: "male",
        bloc: "vl_baozu",
        hp: 4,
        intro: "科尔森，「流亡者」佣兵团的经理，与「赏金公会」进行任务对接。虽然科尔森看起来十分和善，但所有佣兵团的人都知道，科尔森是最不能惹的人。其特殊能力未知，但据说十分强力，能够与十级法师平手。",
        prefix: "",
        skills: ["vl_kersm_my", "vl_kersm_jq"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "yongbing",
        rank: "epic",
    },
    vl_kert: {
        enable: true,
        name: "柯尔特",
        title: "掠魂动魄",
        gender: "male",
        bloc: "vl_quanzu",
        hp: 4,
        intro: "柯尔特，「流亡者」佣兵团的最年轻的成员，由于其对枪械十分精通，因此其在火力掩护的方面有极其重要的作用。他也被团长所赏识，现在小队里都默认他将是下一任团长。柯尔特的身体曾被迦奈尔联邦改造，因此其能够适应各种极端的环境。其最出名的一次任务就是受到神秘的精灵族委托，去寻找能够复活生命之树的元素之泉。",
        prefix: "",
        skills: ["vl_kert_lp", "vl_kert_jl"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "yongbing",
        rank: "rare",
    },
    vl_keya: {
        enable: true,
        name: "苍月狼兽",
        title: "佣兵团长",
        gender: "male",
        bloc: "vl_langzu",
        hp: 4,
        intro: "苍月狼兽，「流亡者」佣兵团的现任团长，擅长于掩护队友和压制对手。苍月狼兽曾经是迦奈尔联邦的逃犯，后来进入赏金工会，受到会长的赏识，通过政治庇护免除了他的罪行。因此其现在正在为赏金工会工作。",
        prefix: "",
        skills: ["vl_kaye_jy", "vl_kaye_yj"],
        addition: ["zhu"],
        pack: "FurryExt",
        vp: 0,
        sort: "yongbing",
        rank: "rare",
    },
    vl_klier: {
        enable: true,
        name: "克莱尔",
        title: "坚实后盾",
        gender: "male",
        bloc: "vl_huzu",
        hp: 3,
        intro: "克莱尔，「流亡者」的成员之一，也许对于其他成员来说，克莱尔的能力并不是最为突出的，但是他确实是行事最为稳重的那个。克莱尔虽然看起来大大咧咧，但是在所有任务中，他均表现出了极其可靠的能力和细心，属于是粗中有细。据柯尔特所言，克莱尔目前似乎已经找到了自己的伴侣，而且似乎有打算退出佣兵团。",
        prefix: "",
        skills: ["vl_kelaier_dh", "vl_kelaier_ty"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "yongbing",
        rank: "rare",
    },
    vl_lint: {
        enable: true,
        name: "林特",
        title: "制衡掣肘",
        gender: "male",
        bloc: "vl_niuzu",
        hp: 4,
        intro: "",
        prefix: "",
        skills: ["vl_lint_nd"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "vl_furry_migration",
        rank: "rare",
    },
    vl_markn: {
        enable: true,
        name: "马克恩",
        title: "洞中窾会",
        gender: "male",
        bloc: "vl_langzu",
        hp: 3,
        intro: "",
        prefix: "",
        skills: ["vl_markn_yz", "vl_markn_yc"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "vl_furry_migration",
        rank: "epic",
    },
    vl_morly: {
        enable: true,
        name: "莫雷",
        title: "枪林弹雨",
        gender: "male",
        bloc: "vl_zhuzu",
        hp: 4,
        intro: "",
        prefix: "",
        skills: ["vl_morly_ld", "vl_morly_xd", "vl_morly_qy"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "vl_furry_migration",
        rank: "common",
    },
    vl_patxi: {
        enable: true,
        name: "帕茨希",
        title: "以身殉戒",
        gender: "male",
        bloc: "vl_langzu",
        hp: 4,
        intro: "",
        prefix: "",
        skills: ["vl_patxi_fs", "vl_patxi_yw"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "vl_furry_migration",
        rank: "rare",
    },
    vl_peter_likes: {
        enable: true,
        name: "皮特莱克",
        title: "操魂控魄",
        gender: "male",
        bloc: "vl_langzu",
        hp: 3,
        intro: "皮特莱克，出生于一个传统的兽人家庭，父亲以制作玩偶为生。在一次意外之后，皮特获得了特殊的能力，能够操纵别人的意识。如此强大的能力却没有被其滥用，而是用来帮助更多人。",
        prefix: "",
        skills: ["vl_peterlk_kh", "vl_peterlk_jn"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "kela",
        rank: "legend",
    },
    vl_nulia: {
        enable: true,
        name: "怒力亚",
        title: "渡化万物",
        gender: "male",
        bloc: "vl_niuzu",
        hp: 4,
        intro: "",
        prefix: "",
        skills: ["vl_nulia_dh", "vl_nulia_hj"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "vl_furry_migration",
        rank: "rare",
    },
    vl_terlk: {
        enable: true,
        name: "特尔里克",
        title: "披荆斩棘",
        gender: "male",
        bloc: "vl_quanzu",
        hp: 4,
        intro: "",
        prefix: "",
        skills: ["vl_terlk_zj", "vl_terlk_pj"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "vl_furry_migration",
        rank: "rare",
    },
    vl_slen: {
        enable: true,
        name: "萨冷",
        title: "八面玲珑",
        gender: "male",
        bloc: "vl_langzu",
        hp: 3,
        intro: "",
        prefix: "",
        skills: ["vl_slen_xj", "vl_slen_gc"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "vl_furry_migration",
        rank: "epic",
    },
    vl_paers: {
        enable: true,
        name: "帕尔斯",
        title: "斗转星移",
        gender: "male",
        bloc: "vl_hulizu",
        hp: 4,
        intro: "",
        prefix: "",
        skills: ["vl_paers_fy", "vl_pares_xh"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "vl_furry_migration",
        rank: "epic",
    },
    vl_nier: {
        enable: true,
        name: "尼尔",
        title: "智解万象",
        gender: "male",
        bloc: "vl_hulizu",
        hp: 3,
        intro: "尼尔，生活在万灵之森中的神秘狐人，他曾言自己见过《瓦尔亚那百科》的原本，因此获得了强大的智慧，能够看穿事物的本质。他崇尚自然和和平，对一切破坏自然的人都会不假辞色。他在弈法和弈风前往万灵之森后看中他们的天赋，并将它们收为弟子。与其说是师傅，尼尔更不如说是他们的父亲一般的角色。",
        prefix: "",
        skills: ["vl_nier_zj"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "wanling",
        rank: "junk",
    },
    vl_pluvia: {
        enable: true,
        name: "普鲁维亚",
        title: "治疗之刃",
        gender: "male",
        bloc: "vl_langzu",
        hp: 4,
        intro: "",
        prefix: "",
        skills: ["vl_pluvia_fs", "vl_pluvia_sx", "vl_pluvia_xs"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "vl_furry_migration",
        rank: "common",
    },
    vl_ventus: {
        enable: true,
        name: "凡图斯",
        title: "泣血之刃",
        gender: "male",
        bloc: "vl_langzu",
        hp: 4,
        intro: "",
        prefix: "",
        skills: ["vl_ventus_nx", "vl_ventus_yc"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "vl_furry_migration",
        rank: "common",
    },
    vl_zenia: {
        enable: true,
        name: "泽妮雅",
        title: "余音绕梁",
        gender: "female",
        bloc: "vl_hulizu",
        hp: 3,
        intro: "",
        prefix: "",
        skills: ["vl_zenia_yy", "vl_zenia_ys", "vl_zenia_ld"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "vl_furry_migration",
        rank: "common",
    },
    vl_kasaers: {
        enable: true,
        name: "卡萨尔斯",
        title: "狂狼怒吼",
        gender: "male",
        bloc: "vl_langzu",
        hp: 4,
        intro: "",
        prefix: "",
        skills: ["vl_kasers_yz", "vl_kasers_kb"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "vl_furry_migration",
        rank: "legend",
    },
    vl_jgby: {
        enable: true,
        name: "吉岡邦彦",
        title: "狂炎灼冰",
        gender: "male",
        bloc: "vl_langzu",
        hp: 4,
        intro: "",
        prefix: "",
        skills: ["vl_jbgy_qx", "vl_jbgy_ze"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "vl_furry_migration",
        rank: "epic",
    },
    vl_liya: {
        enable: true,
        name: "莉亚",
        title: "动运千机",
        gender: "female",
        bloc: "vl_hulizu",
        hp: 3,
        intro: "莉亚生于兽人王国中部的商业中心——恩特城，是兽人王国国王哈拉尔的独女。作为贵族女子的她，自小时候便被灌输各种各样的贵族礼仪，但她的生性不羁，时时让自己的父亲紧张。她在16岁时，曾收到过哈拉尔赠送的重装机车，是她最喜欢的生日礼物。",
        prefix: "",
        skills: ["vl_liya_sz", "vl_liya_sj", "vl_liya_yy"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "kela",
        rank: "junk",
    },
    vl_laays: {
        enable: true,
        name: "拉亚斯",
        title: "镣铐游荡者",
        gender: "male",
        bloc: "vl_langzu",
        hp: 4,
        intro: "“像这样四处游荡，又过了多久呢？”拉亚斯的话语回荡在旷野上。自从那场人类与精灵的大战以人类的完全胜利为结局，拉亚斯也不知道自己游荡多久了。他是当年参加过此次战争的兽人族战士，后牺牲于战火之中。也许是生命树被毁的缘故，拉亚斯重新得到肉体复活。",
        prefix: "",
        skills: ["vl_laays_cs"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "youdangzhe",
        rank: "junk",
    },
    vl_taber: {
        enable: true,
        name: "塔贝尔",
        title: "掘地三尺",
        gender: "male",
        bloc: "vl_langzu",
        hp: 4,
        intro: "",
        prefix: "",
        skills: ["vl_taber_jj", "vl_taber_sj"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "youdangzhe",
        rank: "epic",
    },
    vl_mala: {
        enable: true,
        name: "马拉尔",
        title: "龙裔之王",
        gender: "male",
        bloc: "vl_longzu",
        hp: 4,
        intro: "",
        prefix: "",
        skills: ["vl_mala_ly", "vl_mala_ht"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "shoushen",
        rank: "junk",
    },
    vl_shisan: {
        enable: true,
        name: "拾弎",
        title: "察微知宏",
        gender: "male",
        bloc: "vl_longzu",
        hp: 3,
        intro: "",
        prefix: "",
        skills: ["vl_shisan_dg", "vl_shisan_tx"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "dragongu",
        rank: "legend",
    },
    vl_qiushou: {
        enable: true,
        name: "秋收",
        title: "针砭时弊",
        gender: "male",
        bloc: "vl_hulizu",
        hp: 3,
        intro: "",
        prefix: "",
        skills: ["vl_qiushou_yl", "vl_qiushou_qp"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "vl_furry_migration",
        rank: "legend",
    },
    vl_liuqing: {
        enable: true,
        name: "流青",
        title: "兵无常饰",
        gender: "male",
        bloc: "vl_huzu",
        hp: 3,
        intro: "",
        prefix: "",
        skills: ["vl_liuqing_yf", "vl_liuqing_lz"],
        addition: [],
        pack: "FurryExt",
        vp: 0,
        sort: "vl_furry_migration",
        rank: "legend",
    },
};
